microsoft/vscode-docker

.vscode/settings.json, dockerCompose/dockerComposeCompletionItemProvider.ts, dockerCompose/dockerComposeKeyInfo.ts, dockerExtension.ts, dockerHoverProvider.ts
This addresses #17 by updating the completion provider for compose files in the following ways:
1. Updates the set of recommended properties to match the v1 spec (e.g. `hostname`, `cpu_shares`). 
2. Adds support for the new properties in v2 files, and provides the correct completion results depending on the version of the compose file being edited (e.g. If you're editing a v1 file, you won't see a `log_driver` keyword recommendation).
Additionally, this updates the hover provider to display the help text for both v1 and v2 keys. 
Longer term, we should investigate improving the way that auto-completion works, so that we can display context-based recommendations, which would make this experience much better and less error-prone. I logged #35 to track this enhancement.
Additionally, it …
=> Adding completion/hover support for compose v2 files

snippets/dockerfile.json
This update should only add in support for the new "HEALTHCHECK" instruction introduced in Docker 1.12.  This will close #23 that I opened.
=> Add HEALTHCHECK instruction

dockerfile/dockerfileKeyInfo.ts
This simply adds hover help support for the `ARG`, `HEALTHCHECK` and `SHELL` directives that were added in Docker 1.12. I also re-organized the directives alphabetically, which is the cause of the majority of the churn in this PR.
#25 adds a snippet for the `HEALTHCHECK` directive, but doesn't include support for the hover provider.
=> Adding hover help support for Docker 1.12 directives

commands/showlogs-container.ts
This addresses #39 by simply requesting that the underlying `docker logs` command keeps following stdout for the selected container, which makes it easier to monitor a container within VS Code. If a user doesn't want this functionality, they can easily `CTRL+C` or close the terminal window in VS Code, so I feel like it's easier to just always enable following the logs, as opposed to introducing a new option for the `Show Logs` command, or adding another command.
That said, I'm opening this PR for conversation, since I'm not completely sure whether this change is the right behavior for everyone, despite the fact that it's my preference, and that I think we should have a solution for it in some form.
I've been thinking of terminal windows within VS Code as largely disposeable, especially …
=> Make logs command follow stdout

commands/build-image.ts, package.json
This introduces a new `Docker: Build Image` context menu item, that simply triggers the existing command, but allows users to execute it from a specific file, as opposed to globally using the command palette.
I chose not to require that a folder be currently opened, and so you could right-click within a loose `Dockerfile` and build it's image, and it will use the parent directory as the build context. Since the convention is typically to place a `Dockerfile` within the directory which represents the build context, this behavior seemed reasonable to me, but I'd be interested in feedback. This change is the source of the churn in the `createItem` method.
cc @chrisdias
=> Adding build image context menu

commands/open-shell-container.ts, commands/utils/docker-endpoint.ts, typings/dockerode.d.ts
This change updates the `Docker: Attach Shell` command in order to properly support Windows containers. Previously, this command assumed that it could run `/bin/sh` in the selected image, whereas this change will detect a Windows container, and run `cmd` instead.
Beyond this change, we should allow configuring the default shell use, so that Windows users could toggle PowerShell and Linux users could use Bash/etc.
=> Add Windows support for shell attach

dockerfile/dockerfileKeyInfo.ts
The TypeScript file references a non-existent link on the Docker website. I've fixed it to point at the new link to the Dockerfile reference documentation.
=> Fix broken link to the Dockerfile reference

README.md, commands/utils/docker-endpoint.ts, package.json, typings/dockerode.d.ts
The dockerode library that is used by the extension already has the necessary code to connect to docker-machine instances, as long as there is a valid  DOCKER_HOST environment variable set. 
We can take advantage of this fact and let users connect to other docker daemons. 
Tested with VSCode on windows with:
- a secondary local docker-machine (HyperV)
- remote docker (setup on ubuntu and manually connected as a docker-machine)
=> Use docker-machine from environment variables

commands/docker-compose.ts, dockerExtension.ts
This simply resolves #70 by adding support for the `.yaml` extension for `docker-compose` files, in addition to the existing `.yml` support.
=> Adding yaml detection

dockerExtension.ts, dockerfile/dockerfileCompletionItemProvider.ts, helpers/suggestSupportHelper.ts
This PR simply fixes a bug with the `FROM` directive's hover and auto-completion support in `Dockerfiles`, when an image alias is added (for multi-stage builds). Without this fix, when you hover over an image name (or request auto-completion) that includes an alias, the extension would attempt to search for that string on DockerHub (e.g. `foo AS bar` instead of simply `foo`), which could lead to unpredictable results.
Sometimes the search will actually return the expected result, however, sometimes it doesn't, so this fix ensures it always returns a reasonable result (e.g. hovering over `FROM nodesource/nsolid AS build` returns info for the ASP.NET Core image, hovering over `FROM mhart/alpine-node AS base` returns info for the R-Base image).
=> Fixing hover/completion bug for image names in a multi-stage build

commands/start-container.ts, commands/utils/docker-endpoint.ts, configureWorkspace/configure.ts, typings/dockerode.d.ts
This PR updates the `Run` commands, so that they automatically infer the ports the image is exposing, and publishes them on the host machine. This makes the basic `Run` experience simpler, and provides a little more value-add on top of the developer simply executing `docker run` from the integrated terminal.
In addition, I simplified the generated `Dockerfile` for Node.js a bit, by removing the need for the temp folder for NPM installation, and removing some superfluous whitespace. I also updated the default image to use `alpine` instead of `slim`, which is much smaller.
=> Automatically publish exposed ports when running a container

configureWorkspace/configure.ts
This PR primarily updates the Docker Compose and `launch.json` support for Node, to use the inspector protocol, instead of the older v8 debug protocol. Additionally, I also simplified the `docker-compose` and `launch.json` files a bit.
=> Updating Node/Compose artifacts

configureWorkspace/configure.ts
This is another round of updates to the Node.js Docker assets, which primarily makes the following changes:
1. Updates to using Yarn (which is now part of the official Node images) instead of NPM, which allows for quicker and more deterministic builds.
2. Updates the Compose files to use version 2.1 instead of 2.0 (we could update to newer if we wanted)
3. Sets the `NODE_ENV` var to `production` as part of the `Dockerfile` itself, since it is meant to represent a production build, then has debug-time overrides applied by the debug compose file
4. Removes the superfluous `:latest` tag from the image name in the compose files, since this will use `latest` by default
=> Update Node Docker assets to use Yarn

configureWorkspace/configure.ts
This PR primarily introduces the creation of a `.dockerignore` file, as part of running the `Docker: Add docker files to workspace` command. This file can make a noticeable difference in build time, as well as helps to keep the built containers as "clean" as possible. As part of helping devs get started with best practices, I think it will be really helpful to provide this file, on top of the existing assets we generate.
As part of making this change, I decided to refactor the code for the workspace configuration code a little bit, since there was a bit of duplication. In the process, I updated some of the `Promise` code to use `async/await`, since we have access to it via TypeScript, and it makes the code so much easier on the eyes :)
The current support for the `.dockerignore` file is …
=> Generate a .dockerignore file as part of workspace configuration

commands/start-container.ts
This PR simply adds the `-d` flag when running the `Docker: Run` command. This way, you can use `Docker: Run` to spin up background tasks (and use `Docker: Show Logs`, etc. at any time), and `Docker: Run Interactive` to spin up interactive tasks. Otherwise, the non-interactive command captures your terminal, which might not be the expected behavior.
// CC @chrisdias Let me know what you think of this behavior.
=> Run non-interactive containers in the background

commands/start-container.ts
This PR simply updates the list of container mounts that are defined when running the Azure CLI. Without this change, the `az acs create` or `az acs kubernetes get-credentials` command can't be run, since they need access to your SSH keys in order to configure/authenticate with the underlying VMs. Additionally, the `az acs kubernetes get-credentials` attempts to write your k8s cluster credentials to the `~/.kube` directory, and therefore, this needs to be mounted into the container as well in order to work.
=> Updating Azure CLI mounts to support Kubernetes management

dockerCompose/dockerComposeKeyInfo.ts
Hi
I added parameters for cpu restrictions which are available in 2.2 version of docker-compose file (specifically for docker-compose 1.14).
Signed-off-by: Alexey Rokhin <arokhin@mail.ru>
=> Added cpu settings for compose file version 2.2

dockerExtension.ts, package.json
This PR resolves issue #99 by creating the necessary changes to `package.json` and `dockerExtension.ts` to get the dockerfile-language-server-nodejs npm module integrated into the vscode-docker extension.
Here is how you can test this PR:
1. Pull this PR into your repository.
2. Invoke `npm install` to install the Dockerfile LSP server. This should be relatively quick.
3. Debug > Launch Extension
4. Cross your fingers, open a Dockerfile and see if the installation has completed successfully!
Here is a sample Dockerfile that you can use to get a sense of what is currently possible with this language server. Follow the comments and have fun! Note that you should probably turn off `docker.enableLinting` to more clearly see what the server does and does not provide in terms of validation. …
=> Adopt the dockerfile-language-server-nodejs npm module

package.json
In 6343e3f651c443142b7b6fafb179b8227efc7a3e, the `docker.showExplorer` configuration property is removed, which breaks the docker sash. This PR fix this issue.
=> Fix missing explorer issue

package.json
Hi all, I published version 0.0.7 of my language server to npm yesterday.
You can get a quick overview of the changes [here](https://github.com/rcjsuen/dockerfile-language-server-nodejs/blob/8098d8231b667ac112ea300b36b029198a5428a4/CHANGELOG.md). Probably the most interesting changes are support for signature help as well as the suggestion of image tags in `FROM` instructions (requested in #26).
This is not an exhaustive list but please feel free to use the following Dockerfile for trying out the new features.
```Dockerfile
FROM alpine AS base
FROM busybox AS #invalid
FROM ubuntu: AS ubuntu-stage
FROM fedora: AS fedora-stage
FROM node: AS node-stage
ADD
ARG
CMD
FROM
RUN
SHELL
USER
ARG name
COPY --from
HEALTHCHECK --interval
COPY --
COPY --from=
```
=> Update extension dependency to use version 0.0.7 of the language server

package.json
Although there aren't [that many changes](https://github.com/rcjsuen/dockerfile-language-server-nodejs/blob/a7ff955d293efb6aa9f33c3e925c71a7374a2c4d/CHANGELOG.md) between versions 0.0.7 and 0.0.9, 0.0.8 and 0.0.9 includes two features that have been added to the builder in Docker CE 17.09.
0.0.8 adds support for the `--chown` flag that has been added for `ADD` and `COPY` and will fix #133 and 0.0.9 adds support for warning the user about empty continuation lines.
Please use the following Dockerfile to try out some of the new features.
```Dockerfile
FROM node
HEALTHCHECK --flag=5 CMD ls
RUN echo "a" && \
echo "b"
run x
COPY --flag=x . .
ADD --
COPY --
```
=> Update to the 0.0.9 release of the language server

commands/restart-container.ts, dockerExtension.ts, package.json
Currently user can stop container and remove stopped container from the context menu. To start existing one (stopped) they need to use console command. I propose implementation of 'Restart' command which allows to restart running containers as well as start stopped.
=> Add 'Restart' command for containers.

dockerExtension.ts, package.json
The current matches are too permissive and cause false positives.
Fixes #134
=> Only match Dockerfile and *.dockerfile

dockerExtension.ts, package.json
VS Code's workspace feature will now allow resources to have settings that are scoped to the given resource's folder hierarchy. We need to add support to the `workspace/configuration` language server protocol request that's currently being proposed so that the extension can send changes to scoped settings to the language server.
=> Support workspace folders for the language server's settings

commands/build-image.ts, package.json
I have a multiple docker project which has common pip requirements.
Project files are:
- docker
- local
- app
- Dockerfile
- production
- app
- Dockerfile
- requirements
- requirements.txt
And Dockerfile is like:
`
FROM python:3.6
COPY ./requirements /requirements/
RUN pip install -r /requirements/requirements.txt
...
`
I was trying to build image from "Build Image" context menu, 
but build was failed on COPY line with some error:
> "COPY failed: stat /var/lib/docker/tmp/docker-builder282882071/requirements: no such file or directory"
VSCode generated below command:
`
docker build local-app -f docker/local/app/Dockerfile  docker/local/app/Dockerfile
`
Since 'docker build' send files below build context path to docker-machine to build image,
and do not see parent directories [SO …
=> Add a preference option to set docker build context path

commands/open-shell-container.ts, package-lock.json, package.json
Allows the user to specify the shell command to be used when attaching to containers by using the settings
`docker.attachShellCommand.LinuxContainer` and `docker.attachShellCommand.windowsContainer`
Defaulting to the current commands `/bin/sh` and `powershell`
This closes, or partly closes, #60.
Depending on if you want the user to be able to specify the shell command to run in "runtime" or only using the settings as this PR provides. 
(the former makes the ease of just right clicking a container and pressing `Attach Shell` a bit worse in my opinion since you would then have to specify the attach command anyways)
=> Make the shell attach command customizable

configureWorkspace/configure.ts
seems more common in Node.js apps.
ideally, this would be a setting or a snippet-like placeholder
cc @chrisdias
=> rename app.js to index.js

package.json
While there have been no new features added to the 0.0.11 release, this new release includes fixes for both #165 and #167.
Please use the following Dockerfile to verify the two fixes.
```Dockerfile
FROM openjdk:8-jre-alpine
ENV ZOO_PORT=2181
#
EXPOSE $ZOO_PORT
```
=> Update to the 0.0.11 release of the language server

configureWorkspace/configure.ts
Address https://github.com/Microsoft/vscode-docker/issues/176
- Use `golang:alpine` since `golang:onbuild` is deprecated and discouraged from being used.
- Use multi-stage build
- use `ca-certificates` to enable SSL certificate check
=> use golang:alpine for golang docker image

configureWorkspace/configure.ts
This will ensure that, when present, package-lock.json will be copied in the container and will be used for `npm install`.
=> Add package-lock.json to Node.js Docker template

package.json
The documentation for the `--chown` flag for `ADD` and `COPY` was finally published to the Docker website so I've extracted a small blurb from the documentation and added it to the language server.
I also fixed a bug with parameter hints showing up in a comment that is embedded in a multiline instruction.
Please verify the behaviour with the following Dockerfile before and after upgrading. Thanks!
```Dockerfile
FROM scratch
ADD --cho
COPY --cho
ADD --chown=root . .
COPY --chown=root . .
ENV a=b \
c=d
```
=> Update to the 0.0.13 release of the language server

package.json
Relates to #183
Clicking System Prune does not produce the necessary warnings that Docker normally products when you run a system prune. The icon is also unlabelled and easy to mis-click so close the to the Refresh and resize grabber. It also insufficiently explains purpose.
This will restore the prompt that was there before as a default but allow those that are fully aware of consequences to disable the prompt, so that any new users are fully informed of consequences. Might be worth checking the messaging explains that volumes are removed too as that was a little unexpected.
=> Change promptOnSystemPrune default

configureWorkspace/config-utils.ts, configureWorkspace/configure.ts
While I tested the Dockerfile template, the other aspects I simply copy and pasted as I do not have extensive Docker experience.
=> Add Python support

configureWorkspace/config-utils.ts, configureWorkspace/configure.ts, package-lock.json, package.json
Signed-off-by: Jinbo Wang <jinbwan@microsoft.com>
Implement the feature https://github.com/Microsoft/vscode-docker/issues/191, generate dockerfile for a typical maven/gradle java app.
=> Generate dockerfile for java app

dockerExtension.ts, package-lock.json, package.json
It's been two months since version 0.0.13! There are of course both bug fixes and features but the biggest change is probably the internal refactoring that happened inside the npm module. Assuming everything went fine, you shouldn't be able to notice the difference. :) This release includes the fix for #218.
As always, please use the following Dockerfile to test out the latest changes!
```Dockerfile
#escape=`
FROM node
FROM microsoft/dotnet
ARG x=y
RUN `
`
ls
HEALTHCHECK --interval=5s-10ms CMD ls
HEALTHCHECK --timeout=5s.1ms CMD ls
ADD x y z
COPY x y z
ADD x y z/
COPY x y z/
ADD x y z\
COPY x y z\
FROM alpine@
FROM alpine@sha25:x
FROM alpine:
FROM alpine:^
FROM alpine:a66^
STOPSIGNAL 9
ARG FTP_PROXY
RUN $FTP
FROM scratch
ENV xyz=y
FROM alpine
RUN echo $x
STOPSIGNAL $
FROM alpine …
```
=> Update to version 0.0.14 of the language server

dockerExtension.ts
This PR simply updates the LSP client to use the same file-scheme-based document filter that the `Dockerfile` and YAML completion providers already use. Aside from consistency, this also prepares this extension for [Visual Studio Live Share](https://aka.ms/vsls) adding support for "guests" to receive remote language services for Dockerfiles. This way, when someone has the Docker extension installed, and joins a Live Share session (where files use the `vsls:` scheme), their language services will be entirely derived from the remote/host side, which provides a more accurate and project-wide experience.
=> Restrict LSP client to files

dockerExtension.ts, package-lock.json, package.json
Previously, version 0.0.14 was adopted in #233 but two bugs were discovered that caused the change to be reverted. These two issues have now been fixed in 0.0.17.
- rcjsuen/dockerfile-language-server-nodejs#216
- rcjsuen/dockerfile-language-server-nodejs#217
Two other issues (#237 and #238) unrelated to the 0.0.14 upgrade were reported and they have also been implemented and fixed. And of course, #218 that was fixed in 0.0.14 has not regressed and is fixed in 0.0.17.
Please use the following Dockerfile to test the update to 0.0.17 from 0.0.13. Thank you!
```Dockerfile
#escape=`
###################################################
###################################################
FROM node
FROM microsoft/dotnet
ARG x=y
RUN `
`
ls
HEALTHCHECK --interval=5s-10ms CMD ls
HEALTHCHECK …
```
=> Adopt version 0.0.17 of the language server

package.json
I released a new release of my Dockerfile language server on Saturday. This release includes long-awaited fixes for the code completion error in #271 and the linting error related to private registries in #269, #280, and #288. As always, thank you to the vscode-docker community for your bug reports!
To test the new bug fixes and features of this release, please use the following four Dockerfiles to compare the behaviour of 0.0.17 and 0.0.18!
```Dockerfile
FROM microsoft/dotnet:2.1-
FROM example.registry.com:12345/base/image:1.0.0
FROM repository.mycompany:5000/tomcat:8.0
FROM my.private.repo.com:5000/some-image:latest
FROM host:5000/abc:9.0.0
ARG bbb=value
ARG aaa=${bbb:x}
ARG =value
ARG BUNDLE_WITHOUT
ENV BUNDLE_WITHOUT=${bundle_without:-'development test'}
ENV "a.b.c=xyz"
ENV "a.b.c=xyz …
```
=> Adopt version 0.0.18 of the language server

commands/docker-compose.ts, dockerExtension.ts, package.json
=> Add docker compose restart

README.md
Note the need for a DOCKER_CERT_PATH environment variable when using TLS.
The `docker-machine` section of the README calls out the need for a DOCKER_HOST environment variable, but does not mention the DOCKER_CERT_PATH environment variable.
Failure to have DOCKER_CERT_PATH set when using TLS causes strange looking TLS errors, which are only reported to the user as "Could not connect to docker daemon".  
This seems to cause a fair amount of confusion; see [here](https://github.com/Microsoft/vscode-docker/issues/146), [here](https://github.com/Microsoft/vscode-docker/issues/229), and [here](https://stackoverflow.com/questions/51402080/vscode-docker-extension-cannot-connect-to-docker-machine).
=> Improve docker-machine documentation.

dockerExtension.ts, package.json
Part of #347
@chrisdias just FYI mostly.  The shared registerCommand code has several advantages:
1) It records success and failures
2) It takes care of error handling and other things
3) Each command gets its own event name (rather than eventname='command' + property), which makes analyzing telemetry easier
4) We'll get better synchronization with the dashboard (e.g. event and error tracking)
5) It's automatically done for every event registered with registerCommand
This doesn't yet remove the old telemetry calls, that still needs to be done.  Right now we get both, e.g.:
```
NEW EVENTS >>>
** TELEMETRY("vscode-docker/vscode-docker.explorer.refresh", 0.1.1-alpha) properties={"isActivationEvent":"false","cancelStep":"","result":"Succeeded","error":"","errorMessage":""}, …
```
=> Switch to shared telemetry

commands/start-container.ts, commands/utils/docker-endpoint.ts
=>  Change getExposedPorts to return port w/ protocol

package.json
I made a breaking change to the wizardContext in the UI package which doesn't affect this repo. Bumping the version so that you'll also get Stephen's recent fix to allow an empty string in the input box
=> Update UI package due to latest breaking change

README.md, commands/push-image.ts, commands/tag-image.ts, dockerExtension.ts, package.json
Functionally important changes in the title
Chronologically - 
- Refactor RegisterCommand due to the max func length tslint rule - the function was at the limit of the number of lines. This prevents any change from happening there until this was addressed. 
- combine two workspace settings (defaultRegistry&defaultRegistryPath)
- Prompt user on first push (containing a prefix) to store the path
Fix #396 
Addresses #334
=> Prompt user on first push (containing a prefix) to store the path; combine defaultRegistry&defaultRegistryPath

commands/tag-image.ts
Fixes #406 
I don't expect a merge conflict here. 
Heads-up: The separatorLastIndex can be -1 (when there's no slash in the imageName). I tested for that, and the range given then highlights the whole input (mirroring previous behavior). It works, and I feel the extra effort in clarifying it here may not be warranted. If you feel differently, I'll make that change too.
=> Add valueSelection -> highlights path in tag image inputbox

package.json
I released version 0.0.19 of the language server this morning.
It includes:
- folding support for comments
- fix for #338
- support for handling SCTP ports in `EXPOSE` instructions per Docker CE 18.03
- optional warning/error for `WORKDIR` instructions that are not absolute paths (to try to enforce good practices per the official [guidelines and recommendations document](https://github.com/docker/docker.github.io/blob/c0be65e755be1d8155891fb5d1b457e52bed6cf1/develop/develop-images/dockerfile_best-practices.md) for Dockerfiles
As always, please use the following Dockerfile to test before and after behaviours!
```Dockerfile
FROM node
LABEL "a"="b" \
"c"="d" \
"e"="f"
ENV "a"="b" \
"c"="d" \
"e"="f"
EXPOSE 8080/sctp
WORKDIR abc
WORKDIR $abc
WORKDIR /abc
WORKDIR C:\\abc
```
=> Adopt version 0.0.19 of the language server

README.md, package.json
- Add missing setting from package.json into Readme
- Readme settings desciption : remove eol periods
- Package.json settings desciption : remove eol periods
Moving the use of `askToSaveRegistryPath` from package.json into `ext.context` will be done separately.
=> Consistency and parity of settings

commands/open-shell-container.ts, commands/start-container.ts, commands/utils/docker-endpoint.ts, dockerExtension.ts
=> Read attach setting every time, plus update telemetry

configureWorkspace/configure_dotnetcore.ts, extensionVariables.ts, helpers/windowsVersion.ts, test/configure.test.ts, test/windowsVersion.test.ts
1) Get images based on host Windows version
2) Update templates to match correct VS ones (double quotes, deal with missing port)
=> Tie .NET core image versions with the host Windows version

CHANGELOG.md, configureWorkspace/configure.ts, configureWorkspace/configure_other.ts, package.json, test/configure.test.ts
=> Fix 'Other' platform generation (hotfix 0.3.1)

dockerExtension.ts, package.json
> From: Erich Gamma 
> The report issue link is derived from the extension´s package.json and its repository link. It appears that the Docker extension doesn´t include the type property in its repository attribute. This is how it is done in the vscode-tslint extension.
>
>  "repository": {
>    "type": "git",
>    "url": "https://github.com/Microsoft/vscode-tslint.git"
>  },
=> Add simple activation perf telemetry and fix git type

commands/azureCommands/create-registry.ts, commands/azureCommands/delete-registry.ts, commands/utils/quick-pick-azure.ts, dockerExtension.ts, explorer/dockerExplorer.ts, explorer/models/azureRegistryNodes.ts, explorer/models/registryRootNode.ts, explorer/models/rootNode.ts, explorer/utils/browseAzurePortal.ts, utils/Azure/acrTools.ts, utils/Azure/common.ts, utils/Azure/models/repository.ts, utils/azureUtilityManager.ts
Delays loading azure account extension until after activation
Part of #535
=> Delay loading of Azure Account extension

README.md, debugging/coreclr/dockerDebugConfigurationProvider.ts, debugging/coreclr/prereqManager.ts, package.json
After a little testing, it appears that we can debug .NET Core console applications in Docker using the same infrastructure as ASP.NET applications.  Given that, this PR removes the "ASP.NET" qualifier from the documentation and configuration scaffolding to refer to .NET Core debugging in general.
=> Remove ASP.NET qualifier to .NET Core debugging scenario.

package.json
By specifying _.dockerignore_ as an ignore file, support is added for syntax highlighting and toggling of comments.
This is analogous to for example _.gitignore_ and _.eslintignore_.
=> Specify .dockerignore language

.vscode/tasks.json
Fix this error from vscode when opening project:
Error: the description can't be converted into a problem matcher:
{
"base": "$tslint5",
"fileLocation": "absolute"
}
=> Fix lint task warning

README.md, debugging/coreclr/commandLineBuilder.ts, debugging/coreclr/dockerClient.ts, debugging/coreclr/dockerDebugConfigurationProvider.ts, debugging/coreclr/dockerManager.ts, package.json, test/debugging/coreclr/commandLineBuilder.test.ts, test/debugging/coreclr/dockerManager.test.ts, test/debugging/coreclr/lineSplitter.test.ts, test/debugging/coreclr/prereqManager.test.ts, thirdpartynotices.txt
Allows users to further customize Docker images and containers used during debugging.  
The following build customizations were added:
- **`args`:** Set or override build arguments (i.e. `ARG`) declared in the `Dockerfile`
- **`labels`:** Dynamically apply labels to the image
The following run customizations were added:
- **`env`:** Set or override environment variables applied to the container
- **`envFiles`:** Apply sets of environment variables, defined in arbitrary files, to the container
- **`labels`:** Dynamically apply labels to the container
This brings the Docker debugging customizations closer to parity with VS.
> NOTE: This PR adds a dependency on [deep-equal](https://github.com/substack/node-deep-equal)
=> Support additional Docker build and run customization

.travis.yml
I've updated the travisci pipeline to use jobs instead only a script, because it's faster, cleaner and you can see better the errors in the pipeline.
An example is here -> https://travis-ci.org/wachino/vscode-docker/builds/447113342
=> pipeline: use jobs instead of only script

explorer/models/taskNode.ts, gulpfile.js, test/index.ts, test/testUrl.ts, utils/getTrustedCertificates.ts
Thoughts?  This makes it possible to have multiple reporters (currently we don't get any feedback from tests when run locally, and you have to know to click on 'Tests' to see feedback on Azure Pipelines (which I didn't at first).  Also allows adding JSON to MOCHA_ vars (since an object is required to configure the multiple reporters).
The simpler option would be to simply define the reporter as a variable in the pipeline.
=> Support multiple reporters

configureWorkspace/configDebugProvider.ts, package.json
fixes #612
This PR simplifies the generated `launch.json` in the following ways:
* The snippets do not have the default fields any more, making them more concise. The missing fields should be nicely added by node
* When the initial configuraiton is provided we ask the user for the remoteRoot, making it clearer what is the attribute that users change the most
What still needs to be done imho:
* We should read the dockerfile, such that we see the value of the dockerfile WORKDIR and take that as the default, not the hardcoded `/usr/src/app`
* Read the dockerfile and see if the userconfigured a remote port, if he did than insert the port in the configuration. Currently we do not set any because the node debug will corectly pick the port based on node version
* Tune the wording of the input …
=> make the launch.json generation leaner

debugging/coreclr/dockerDebugConfigurationProvider.ts, debugging/coreclr/prereqManager.ts, debugging/coreclr/registerDebugger.ts, extension.ts, test/debugging/coreclr/prereqManager.test.ts
Adds a prerequisite check that verifies the existence of the `Dockerfile` inferred or specified by the user.  If the `Dockerfile` does not exist, the error message prompts the user to run the scaffolding task.
Resolves #681.
=> Add prerequisite check for missing Dockerfile

configureWorkspace/configure_python.ts
This reverts commit d4c1b3e8bf7783beb2a8683394510672fded9a73.
There is currently some question as to the correct fix.  Reverting until resolved.  Created issue #693 to track.
=> Revert "Create requirements.txt if it doesn't exist (#647)"

utils/getTrustedCertificates.ts
=> fix null ref from importCertificates

package-lock.json, package.json, webpack.config.js
=> Fix user cancel showing messages

README.md, debugging/coreclr/dockerClient.ts, debugging/coreclr/dockerDebugConfigurationProvider.ts, debugging/coreclr/dockerManager.ts, package.json
Extend Docker Run configuration to add more customisations on the containers.
Now the `DockerRun` config on `launch.json` file can accept the following elements:
```json
"dockerRun": {
"containerName": "my-container",
"env": {
"var1": "value1",
"var2": "value2"
},
"envFiles": [
"${workspaceFolder}/staging.env"
],
"labels": {
"label1": "value1",
"label2": "value2"
},
"ports": [
"80:80",
"443:443"
],
"externalHosts": [
"some-hostname:some-ip",
"some-other-hostname:some-other-ip"
],
"volumes": [
{
"localPath": "path-on-host-machine",
"containerPath": "path-inside-container",
"permissions": "ro|rw"
}
]
}
```
=> Allow more customization of docker run command

README.md, debugging/coreclr/dockerClient.ts, debugging/coreclr/dockerDebugConfigurationProvider.ts, debugging/coreclr/dockerManager.ts, package.json
Adds a `network` option to the Docker run section of the Docker debug configuration.  This option corresponds to the  `--network` option of the `docker run` command.
Also resolves an issue introduced with #690 which causes debugging to fail if the `volumes` configuration option is not specified (i.e. is `undefined`).  (In that case, the workaround until this fix is committed and released is to set it to an empty array.)
=> Add `network` option to Docker run configuration

utils/getTrustedCertificates.ts, webpack.config.js
Not positive if this is the correct fix (it might be), or just a work-around, but it does fix the issue, and we need a fix before vscode ships next week.
#733 
Note that mac-ca works differently (spawns a mac exe) so does not have this same problem.
=> Use win-ca fallback logic since nAPI isn't currently compatible with Electron

package-lock.json, package.json
This new update to version 0.0.20 of the language server includes a few bug fixes in addition to the ability of folding instructions that span multiple lines.
Please use the following Dockerfile to try out the new changes.
```Dockerfile
FROM node
COPY a bunch of files ${DESTINATION_DIR}
RUN echo && \
echo && \
echo && \
echo && \
echo && \
echo && \
echo && \
echo && \
echo && \
echo
FROM node as setup
COPY --from=sETUp . .
COPY --from=seTUp . .
COPY --from=sETup . .
```
=> Upgrade language server version to 0.0.20

CHANGELOG.md, package.json, utils/getTrustedCertificates.ts, webpack.config.js
Port bug fix "Use win-ca fallback logic since nAPI isn't currently compatible with …  …"
and
Prepare for v0.5.2 hotfix release
=> Prepare for v0.5.2 hotfix release

README.md, debugging/coreclr/dockerDebugConfigurationProvider.ts
Resolves the `localPath` debug configuration of volumes to allow the use of the `${workspaceFolder}` variable.  This allows users to specify workspace-relative volumes rather than absolute volumes, which helps users share launch configurations.
Resolves #785.
=> Resolve local volume paths

README.md, debugging/coreclr/debuggerClient.ts, debugging/coreclr/dockerClient.ts, debugging/coreclr/dockerManager.ts, debugging/coreclr/registerDebugger.ts, debugging/coreclr/vsdbgClient.ts
Adds support for debugging Linux images based on the "Alpine" set of .NET Core base images.
Alpine images require a different variant of the .NET Core debugger (`vsdbg`) than used for the "standard" images currently supported.  Determining which variant is necessary must be done *after* the container is running, by executing a script on the container which returns the image type.
Currently, the debugging provider volume mounts only the folder of a specific variant of debugger, and has the debugging engine use that variant.  This change updates the debugging provider such that containers volume mount the *root* folder for all cached debugging variants (as that must happen during container creation), then starts the container, then runs the script to determine the needed variant, and *then* …
=> [.NET Core Debugging] Add support for Alpine images

debugging/coreclr/debuggerClient.ts, debugging/coreclr/registerDebugger.ts
gdziadkiewicz had discovered that I broke debugging .NET Core in Docker on Windows with the previous Alpine support commit, and was also kind enough to suggest a workaround in PR #795 (a larger change to support F# project debugging).
For simplicity, I've split that workaround into a separate PR and updated/verified it to work across Mac/Ubuntu/Windows.  The changes are:
- Use a double-quoted script string to obtain the container debugger type when VS Code is running on Windows.
- Normalize the relative (host) path returned by the debugging client for the target (i.e. container's) platform.
=> Resolve .NET Core debugging on Windows

configureWorkspace/configure_dotnetcore.ts, extension.bundle.ts, helpers/osVersion.ts, test/configure.test.ts
Add support for Redstone 5 which should generate Dockerfiles referencing -1809 images
Fixes #805
=> Add support for Redstone 5

README.md, configureWorkspace/configure.ts, configureWorkspace/configure_dotnetcore.ts, debugging/coreclr/dockerDebugConfigurationProvider.ts, test/configure.test.ts
**Tested only on Windows 10 machine with Docker for Windows** using template generated fsharp app and generated dockerfile.
~~After refreshing my branch with master the debugging feature stopped working for my setup and the changes in commit e6cc443 are workarounds for those problems:~~
1. ~~Before changing the  single quotes to double quotes in platform checking docker exec call it resulted in `Syntax error: Unterminated quoted string`  error.~~
2. ~~The call to ` this.debuggerClient.getDebugger` was returning path with backslashes. This also caused error. Please confirm that this is the right place to do the normalization if you decide to merge this.~~
=> Add debugging and dockerfile creation for fsharp dotnet core projects.

.vscode/extensions.json, .vscode/settings.json, commands/azureCommands/create-registry.ts, commands/azureCommands/delete-image.ts, commands/azureCommands/delete-registry.ts, commands/azureCommands/delete-repository.ts, commands/remove-container.ts, commands/restart-container.ts, commands/stop-container.ts, explorer/models/azureRegistryNodes.ts, explorer/models/registryRootNode.ts, explorer/models/rootNode.ts, explorer/utils/dockerHubUtils.ts, extension.ts, extensionVariables.ts, package.json
Fixes #429, fixes #375, fixes #817 
The current experience only allows you to log in when you try to expand the Docker Hub tree. I changed it to instead mimic the Azure experience...
=> Improve Docker Hub login experience

explorer/deploy/webAppCreator.ts
Fixes #550 
Code incorrectly assumed that no username or password meant using ACR.
=> Fix deploying to private registry with no auth

explorer/models/registryRootNode.ts
Don't ask why Azure uses Sign In and Docker Hub uses Log In, but I kept our terminology consistent with those.
Fixes #829
=> Use Log In/Out consistently for Docker Hub

debugging/coreclr/dockerManager.ts
Previously the NuGetFallbackFolder mounted into the container used for
debugging was hardcoded to /usr/local/share/dotnet/sdk/NuGetFallbackFolder
for all non-windows platforms. However this path is only the valid
default for OSX. On Linux /usr/share/dotnet/sdk/NuGetFallbackFolder is
the default installation location. This patch corrects that behavior.
=> Fix nuget fallback volume mount for dotnet debugging

README.md, debugging/coreclr/dockerClient.ts, debugging/coreclr/dockerDebugConfigurationProvider.ts, debugging/coreclr/dockerManager.ts, package.json
Adds the `networkAlias` option to the Docker .NET Core debugging run configuration. This option corresponds to the `--network-alias` option of the `docker run` command.  This resolves #884.
=> Add `networkAlias` option to Docker run configuration

debugging/coreclr/appStorage.ts, debugging/coreclr/fsProvider.ts, debugging/coreclr/vsdbgClient.ts
Ensure the debugger directory exists prior to starting the container (or, rather, before any possible use of the directory), to prevent it potentially being created with permissions different than those used by VS Code (to actually acquire the debugger).
This resolves #897.
=> Ensure debugger directory exists

commands/azureCommands/acr-logs-utils/tableViewManager.ts, package-lock.json, package.json
The pacakge-lock.json has a lot of https -> http conversions. I've update npm to the latest version and cleaned/rebuilt node_modules, but the issues still persist. Any ideas?
=> Remove usage of clipboardy

configureWorkspace/configure_dotnetcore.ts, test/configure.test.ts
Microsoft has started moving images from Docker Hub Registry to Microsoft Container Registry (MCR). See https://azure.microsoft.com/en-us/blog/microsoft-syndicates-container-catalog/.
.NET Core 2.1+ images are now published to MCR. See details here:
https://devblogs.microsoft.com/dotnet/net-core-container-images-now-published-to-microsoft-container-registry/.
Therefore, I updated images repos from `microsoft/*` to `mcr.microsoft.com/*` for .NET Core 2.1+.
=> [Post-Build] Update .NET Core Images from microsoft/* to mcr.microsoft.com/*.

commands/azureCommands/acr-logs.ts, commands/azureCommands/pull-from-azure.ts, commands/remove-container.ts, commands/showlogs-container.ts, configureWorkspace/config-utils.ts, configureWorkspace/configure_cpp.ts, configureWorkspace/configure_dotnetcore.ts, debugging/coreclr/dockerDebugConfigurationProvider.ts, debugging/coreclr/dockerManager.ts, debugging/coreclr/netCoreProjectProvider.ts, dockerCompose/dockerComposeCompletionItemProvider.ts, dockerHubSearch.ts, explorer/deploy/azureAccountWrapper.ts, explorer/deploy/util.ts, explorer/models/azureRegistryNodes.ts, explorer/models/customRegistryNodes.ts, explorer/models/dockerHubNodes.ts, explorer/models/getImageLabel.ts, explorer/models/rootNode.ts, explorer/utils/dockerHubUtils.ts, test/configure.test.ts, test/customRegistries.test.ts, test/nonNull.test.ts, tsconfig.json, utils/httpRequest.ts
A few notes:
1. `verifyTelemetryProperties` wasn't used in the configure tests, but seems somewhat useful so I added it and fixed the failing tests
1. the cpp generation was ignoring `exposeStatements`, but I assume that's fine since it says `// We don't open a port for Cpp` a few lines above. Updated the cpp test to reflect this
=> Turn on noUnusedLocals

gulpfile.ts, package.json, src/extension.ts, src/extensionVariables.ts, src/tree/LocalRootTreeItemBase.ts, src/utils/TerminalProvider.ts, src/utils/addDockerSettingsToEnv.ts
Previously we only supported "docker.host" (aka "DOCKER_HOST") as a VS Code setting. I added support for the 4 main environment variables used in [docker machine](https://docs.docker.com/machine/get-started/). Users want these as VS Code settings so that they can have per-workspace setups and so that they can modify a setting without reloading VS Code or changing their environment variables.
Also we were parsing "docker.host" ourselves in the past, which led to a lot of problems because our parsing logic was _very_ simplistic. Instead, I will let docker_modem (a dependency of Dockerode) do all the parsing for us. See [here](https://github.com/apocas/docker-modem/blob/master/lib/modem.js#L26) for more info.
Fixes https://github.com/microsoft/vscode-docker/issues/962
Fixes …
=> Support all `DOCKER_*` environment variables as VS Code settings

CHANGELOG.md, extension.ts, package-lock.json, package.json
Potential temporary workaround for https://github.com/microsoft/vscode-docker/issues/1008
Still testing, but wanted to get eyes on it ASAP. I basically check if both extensions are installed and defer to the old publisher for all functionality.
=> Workaround for multiple publishers installed

package-lock.json, package.json
This new update is mainly focused around improvements to the validation to correct some false positives (fixes #952) in addition to a fix to how variables were being resolved. Now the language server only considers alphanumeric and underscore characters as part of a variable's name.
As always, please use the following Dockerfile before and after the pull request to verify the changes:
```Dockerfile
FROM node
VOLUME [ "/data" ]
VOL
FROM scratch
RUN echo ${bbb:?}
RUN echo ${Env:Temp}
FROM $image
FROM scratch
ARG ARG_VAR=1234
ENV ENV_VAR $ARG_VAR
EXPOSE "$ENV_VAR"
FROM scratch
ARG ARG_VAR=1234
EXPOSE "$ARG_VAR"
FROM alpine
ENV var value
RUN echo $var:test
FROM alpine
ENV var value
RUN echo $var:test
FROM alpine
ENV var value
RUN echo $var:test
FROM alpine
ENV var value
RUN echo $var:test …
```
=> Upgrade language server version to 0.0.21

src/tree/images/ImagesTreeItem.ts
Before:
After:
Fixes https://github.com/microsoft/vscode-docker/issues/1003
Fixes https://github.com/microsoft/vscode-docker/issues/209
=> Improve display of images with no RepoTags

src/tree/images/ImageTreeItem.ts
In all other cases I think it still makes sense to use the "application" icon. For example:
Fixes https://github.com/microsoft/vscode-docker/issues/1076
=> Use tag icon if label is set to "Tag"

src/tree/containers/ContainerTreeItem.ts, test/tree/containersTree.test.ts, test/tree/validateTree.ts
The "Attach Visual Studio Code" command is contributed by the [remote containers](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers) extension and it doesn't work with the new explorer as-is. Fixed that and added a test to make sure we don't break this in the future.
=> Add back support for "Attach Visual Studio Code" command

src/tree/LocalGroupTreeItemBase.ts
Take this tree item as an example:
An image's id is currently `fullTag + id`. A group's id is the same as the label. This results in the following full ids for the above screenshot:
* `/erijiz2/helloacrtasks`
* `/erijiz2/helloacrtasks:v1sha256:3700e2efe77f976cb8cc80b3ae3315baaaab4e9068857da491c1e99aaf555059`
However, if you change the grouping to "None" that confuses VS Code resulting in a broken view because the id for the image is still the same (just without a parent). Here are the new full ids:
* `/erijiz2/helloacrtasks|LocalGroup`
* `/erijiz2/helloacrtasks|LocalGroup/erijiz2/helloacrtasks:v1sha256:3700e2efe77f976cb8cc80b3ae3315baaaab4e9068857da491c1e99aaf555059`
=> Fix weird grouping bug

src/configureWorkspace/configureDotNetCore.ts, test/configure.test.ts
The Dockerfile we scaffold calls build and publish with the same target directory. In .NET Core 3 this causes a problem because some build artifacts are left over in the publish output. See: https://github.com/aspnet/AspNetCore/issues/11609
=> Updating netcore Dockerfile to use separate directory for publish

src/tree/registries/RegistriesTreeItem.ts
I've seen some cases of "No resources found" in telemetry, which implies people are trying to run commands without connecting anything yet
=> Include "Connect Registry..." in command palette

src/debugging/coreclr/CommandLineDotNetClient.ts, src/debugging/coreclr/dockerDebugConfigurationProvider.ts, src/debugging/coreclr/dockerManager.ts
* Add <UserSecretsId> property when < 3.0 dotnet CLI is present
* Pass in ASPNETCORE_HTTPS_PORT env var to enable automatic redirection to SSL page
* Automatically infer if the app is SSL-enabled
#1144
=> Improvements to ASP.NET Core SSL support

src/commands/registries/disconnectRegistry.ts, src/tree/registries/RegistriesTreeItem.ts
A user was able to connect a registry with an empty URL and get in a situation where they couldn't disconnect it because `ext.registriesTree.showTreeItemPicker` would throw an error. Instead, I will circumvent the tree and use the registry cache more directly to show the quick pick.
Related to https://github.com/microsoft/vscode-docker/issues/1155 (emphasis on _related to_. There's still other aspects of that bug that I want to address, like preventing users from entering empty urls, etc.)
Example screenshot:
=> Make disconnect registry more robust to errors

package.json, src/commands/registries/disconnectRegistry.ts, src/tree/registries/RegistriesTreeItem.ts
The final piece that fixes https://github.com/microsoft/vscode-docker/issues/1155
Now if an invalid registry is connected, it'll be displayed in the tree and users can right click on it to disconnect:
=> Allow user to disconnect invalid registry from tree

src/configureWorkspace/configureNode.ts, test/configure.test.ts
It appears that we are looking for an `npm` script which directly references `node` in order to generate the proper debug configuration (--inspect=0.0.0.0:9229). But directly referencing `node` isn't required for an `npm start` script. For instance, the following is valid...
```
"scripts": {
"start": "./server.js"
}
```
I had this configuration and it took me quite a while to figure out why the debugger wouldn't attach.
It seems to me that we should always generate the proper host:port configuration for the `debug.yml`. What is the use case for not doing that if we don't find "node" as a command in the `package.json` scripts section? If the user has already selected "node", then node is explicit.
=> Always Add host and port to `compose.debug.yml`

src/commands/registries/azure/DockerWebhookCreateStep.ts
Resolves issue uncovered while investigating #1243, where users missing (i.e. not actively dismissing) the prompt to create a web hook during deployment of a Docker Hub image to Azure App Service can inadvertently lead to deployment appearing to take forever.
Deployment will not complete until the notification has been dismissed, but VS Code will automatically shift such notifications to the (hidden by default) notifications pane, effectively hiding them from the user and leaving only the initial "deploying..." notification shown.
This change makes handling responses to the web hook notification independent of the deployment process, so it will complete whether the users notices (and responds to) it or not.
=> Make web hook message independent of wizard.

package.json, src/commands/registerCommands.ts, src/commands/registerWorkspaceCommand.ts, src/constants.ts, src/tree/LocalRootTreeItemBase.ts, src/utils/getVSCodeRemoteInfo.ts
Fixes https://github.com/microsoft/vscode-docker/issues/954. See that issue for more info on _why_ we want to default to workspace extension instead of ui extension.
In addition to changing the default (which is the most important change), I added some helpful error messages to common scenarios.
User has Docker installed as "ui" extension. Currently they will see a bunch of random errors for unsupported actions like this:
I added this error message instead:
User has Docker installed as "workspace" extension in dev container. "Add Docker Files to Workspace" should work, but any commands using the terminal won't work and the explorer won't show anything.
All I did was add a link in the explorer. The docs still need to be written, but we will likely direct them to one of these options:
1. …
=> Change extension to run in remote workspace by default

src/commands/registries/azure/DockerWebhookCreateStep.ts
If my username is "exampleuser" and I try to deploy to organization "exampleorg", the prompt will take me to:
```
https://cloud.docker.com/repository/docker/exampleuser/nodejs-docs-hello-world/webHooks
```
when it should take me to:
```
https://cloud.docker.com/repository/docker/exampleorg/nodejs-docs-hello-world/webHooks
```
=> Fix webhook link for DockerHub organization

src/commands/registries/azure/DockerWebhookCreateStep.ts, src/debugging/coreclr/CommandLineDotNetClient.ts, src/utils/randomUtils.ts
Fixes https://github.com/microsoft/vscode-docker/issues/1270
Per the portal, a webhook name has these requirements
But a site name has looser requirements (allows hyphens and 3-64 characters I think). I scrapped the existing logic to generate a name and based it more closely off what the portal does:
=> Ensure webhookName meets requirements

src/commands/images/buildImage.ts
If Git bash is the default VS Code shell, building an image from the Dockerfile context menu could fail if the build context contains directory separators (as the Windows separator would be interpreted as an escape character by Git bash).  Enclosing with quotes prevents the confusion.
Resolves #902
=> Resolve Docker build issue when using Git bash on Windows

package.json
Enable YAML suggestions by default so that Docker Compose IntelliSense provided by this extension is displayed without requiring CTRL+SPACE.  This is also what the [YAML extension](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml) does.
Users can disable this by setting `[yaml].editorQuickSuggestions.strings` to `false` in their settings.
Resolves #243.
=> Enable YAML suggestions by default

package.json, src/tasks/netcore/NetCoreTaskHelper.ts
* Enable edit-refresh in ASP.NET Core with DOTNET_USE_POLLING_FILE_WATCHER environment variable, resolves #1302 
* Fix unrelated bug where debug resolve didn't activate the extension
=> Enable edit-refresh in ASP.NET Core

.github/CODEOWNERS
I mentioned this offline in an email a while ago, but there are a lot of people on the `vscodeazuretools` team that don't want emails about every single PR. We already changed the CODEOWNERS in other repos to a smaller "dev" team subset (see [here](https://github.com/microsoft/vscode-azurefunctions/pull/1486) as an example), but that team didn't feel accurate for this repo. @philliphoff @bwateratmsft you can create a new team here if you want: https://github.com/orgs/microsoft/teams/vscodeazuretools/teams
=> Don't send PR emails to vscodeazuretools team

extension.bundle.ts, main.js, src/extension.ts
The whole of `deactivateInternal` can be refactored to be disposables pushed onto `ctx.subscriptions`. This is assuming that calling `dispose()` on the Disposable from `start()` is equivalent to, or at least also calls, `stop()`.
=> Use ctx.subscriptions to manage disposables

package.json, src/commands/containers/selectContainer.ts, src/commands/registerCommands.ts
Resolves https://github.com/microsoft/vscode-docker/issues/1235.
Enables scenario like this: 
```json
{
"name": ".NET Core Docker Attach",
"type": "coreclr",
"request": "attach",
"processId": "${command:pickRemoteProcess}",
"pipeTransport": {
"pipeProgram": "docker",
"pipeArgs": ["exec", "-i", "${command:vscode-docker.containers.select}"],
"debuggerPath": "/vsdbg/vsdbg",
"pipeCwd": "${workspaceRoot}",
"quoteArgs": false
}
}
```
Blocked by https://github.com/microsoft/vscode/issues/80219.
=> Adding vscode-docker.containers.select

src/tree/registries/RegistriesTreeItem.ts
Resolves #1310
The user will see a clear warning message instead:
=> Clearer error message for duplicate registry

package.json, src/tree/LocalRootTreeItemBase.ts
Related to #1292, #1225. Resolves #1351.
This was suggested by @EricJizbaMSFT in [this comment](https://github.com/microsoft/vscode-docker/issues/1225#issuecomment-525368211).
=> Only refresh if VSCode is in focus

package.json, resources/dark/add.svg, resources/light/add.svg, src/commands/networks/createNetwork.ts, src/commands/registerCommands.ts
This was requested in https://github.com/microsoft/vscode-docker/issues/1322.
I could not find an appropriate icon for this action in the resources directory so I'm not sure that it can be merged until one is added.
=> Add a command to create the simplest network

src/extension.ts, src/utils/nps.ts
After ten sessions on different days (i.e. multiple sessions in one day count as just one), choose 15% of users to prompt to take the NPS survey for the Docker extension. Prompt has Take Survey, Remind Me Later (will remind after 3 more sessions), and Don't Show Again.
=> Ask some active users to take NPS survey

package-lock.json, package.json, resources/dark/add.svg, resources/light/add.svg, src/commands/networks/createNetwork.ts, src/commands/registerCommands.ts, src/extension.ts, src/registerListeners.ts, src/tree/LocalRootTreeItemBase.ts, src/tree/registries/RegistriesTreeItem.ts, src/utils/nps.ts
Cherry pick:
- #1339
- #1346
- #1352
- #1350
- #1364
=> Cherry pick several things for 0.8.2 release

src/configureWorkspace/configure.ts
Removes the `LICENSE` file from the `.dockerignore` file, allowing it to be part of the Docker build context.  It was found to have been required in some `Dockerfile`s and there should be little impact, optimization-wise, in allowing it.
Resolves #1331.
=> Remove LICENSE from .dockerignore file.

package.json, src/tasks/DockerBuildTaskDefinitionBase.ts, src/tasks/DockerBuildTaskProvider.ts, src/tasks/DockerRunTaskDefinitionBase.ts, src/tasks/DockerRunTaskProvider.ts, src/tasks/TaskDefinitionBase.ts, src/tasks/netcore/NetCoreTaskHelper.ts
Moves the addition of the default VS Code labels to Docker images/containers to the base task providers in order to apply to all platforms (instead of just .NET Core).  Also updates the logic so that default labels are included (by default) even if the user explicitly adds their own labels, with an option (by setting `docker[Build|Run].labels.includeDefaults = false`) to *not* include the default labels.
Resolves #1392 (except for discussion related to ports, which should be a separate PR).
=> Aggregate Docker build/run task labels with VS Code defaults

package.json, src/tasks/netcore/NetCoreTaskHelper.ts
It became necessary to add an `enableDebugging` flag like Node had. Otherwise, we map `/src`, `/app`, and others. `/app` in particular prevents the release mode from working because we overwrite the `/app` folder, containing the relevant binary directly, with the project folder on the host machine, which contains the (debug, aka wrong) binary a few folders down (`bin/Debug/netcoreapp3.0` or similar).
The SSL-related folders still need to be mapped, along with `ASPNETCORE_ENVIRONMENT=Development` in order to make SSL work. In a real production build, they would need to map in user secrets differently.
The diff is super weird; we're just guarding several volumes inside `if (helperOptions.enableDebugging)`.
=> Create a release-ish task in .NET Core apps

src/utils/spawnAsync.ts
Adds `code` and `signal` properties to errors thrown by `spawnAsync()` to better replicate what callers expect (if `exec()`) had been called.
Resolves #1424.
=> Add exit code to Error generated by spawnAsync()

src/configureWorkspace/configUtils.ts, src/configureWorkspace/configure.ts
Captures telemetry data for the "step" (i.e. prompt) at which the user cancels adding Docker files to the workspace, in order to measure if and, at what point, users change their minds about taking the action.
Also updates the wording of the Docker Compose files prompt for Node.js, to emphasize that either option is ok.
=> Adds telemetry property for "Add Docker files" command

src/commands/containers/attachShellContainer.ts, src/tree/containers/ContainerTreeItem.ts
Uses the container name instead of the image name for the VS Code shell/terminal label, which helps disambiguate multiple terminal windows for containers which share a common base image.
Resolves #1463.
=> Use container name instead of image name for shell label.

package.json
With `1.40.x` of VS Code, the `extensionKind` property of `package.json` can be an array which indicates the "preference" of the extension with respect to which "side" of the editor on which it should run. With this change, it indicates that the Docker extension should prefer the side on which the workspace is opened (e.g. the remote development side, if the extension is installed on that side), otherwise it runs on the UI side.
Resolves #1440
=> Conform to new extensionKind property schema.

src/tree/registries/RegistriesTreeItem.ts
Ancillary errors thrown while removing a registry node shouldn't prevent the tree item from being removed, so we catch (and report) exceptions when those occur.
Resolves #1480.
=> Catch errors removing passwords from cache.

src/commands/images/pushImage.ts
Updates the push image command to prompt to save a tag's registry as the default *only* if there is no currently set default registry.
Resolves #1478.
=> Only prompt to save registry if no default exists.

src/commands/networks/createNetwork.ts
Earlier static set of drivers were used during create network. Some of these drivers are not applicable for windows os. Now based on engine os version, right set of drivers are provided to user.
This fixex #1444
=> Use appropriate drives based on docker engine os

src/tasks/netcore/NetCoreTaskHelper.ts, src/tasks/node/NodeTaskHelper.ts
Sets the `pull` property to `true` when scaffolding .NET/Node.js Docker build tasks, which causes Docker to pull the latest image on build.  Previously, the property was omitted which meant that Docker would *not* pull the latest image.
Resolves #1409.
=> Add `pull` property to Docker built task scaffolding.

src/tree/images/ImageTreeItem.ts
Remove image will fail for images that are used by running container or other images. These failures are treated as error and report issue options is shown to user, which leads user to believe that it a bug in the extension. Now, these errors are shown to user as warning and no report issue button is shown.
Related to #1398.
=> Handle in-use remove image

src/tree/LocalGroupTreeItemBase.ts, src/tree/containers/ContainerGroupTreeItem.ts
Container related commands like start and stop is valid for certain containers based on state. If the containers are grouped (default), then the first level tree item picker shows all container groups. Now this is filtered to show the group that has a valid container.
Related to #1430
=> Filter and show only the container groups valid for that command

README.md
Updates the build status badge to point to the new `vscode-docker-nightly-2` build pipeline.
=> Switch badge to new build pipeline

.vscode/settings.json, tsconfig.json
When a local package is linked, it includes types from original vscode.d.ts and the one from the link. This results into duplicate type during compile.
=> Enable consuming the local package using npm link

package.json
As part of documentation revamp I did a quick pass over our extension property descriptions
- Tried to make the descriptions somewhat more direct and understandable.
- Removed references to default values (these are displayed in a separate column in the extension "Contributions" tab, so putting them in the description is redundant.
- Added list of possible values for enum-type configuration properties. Without them one needs to look at the extension source/manifest to learn what is possible.
=> Improve extension configuration property descriptions

package-lock.json, package.json, src/commands/containers/browseContainer.ts, src/commands/containers/inspectContainer.ts, src/commands/containers/removeContainer.ts, src/commands/containers/restartContainer.ts, src/commands/containers/selectContainer.ts, src/commands/containers/startContainer.ts, src/commands/containers/stopContainer.ts, src/commands/containers/viewContainerLogs.ts, src/commands/images/copyFullTag.ts, src/commands/images/inspectImage.ts, src/commands/images/pushImage.ts, src/commands/images/removeImage.ts, src/commands/images/runImage.ts, src/commands/images/tagImage.ts, src/commands/networks/inspectNetwork.ts, src/commands/networks/removeNetwork.ts, src/commands/registries/azure/untagAzureImage.ts, src/commands/registries/copyRemoteImageDigest.ts, src/commands/registries/deleteRemoteImage.ts, src/commands/registries/dockerHub/openDockerHubInBrowser.ts, src/commands/volumes/inspectVolume.ts, src/commands/volumes/removeVolume.ts
If no matching item found while selecting an item in tree item picker, then a generic error message 'No resource found' with 'report issue' button is offered to user.
Now a customized message is given (like no running container are available to stop) and the 'report issue' button is not shown to user. The azuretools extension behavior is changed to not show 'report issue' when a custom message is provided (refer https://github.com/microsoft/vscode-azuretools/pull/644).
related to #1528
=> Provide a useful error message and suppress report issue button

src/commands/containers/inspectContainer.ts, src/commands/networks/inspectNetwork.ts, src/commands/volumes/inspectVolume.ts, src/tree/networks/NetworkTreeItem.ts, src/tree/volumes/VolumeTreeItem.ts
Added error handling for volume and network inspect and delete. This will not show 'report issue' button.
related to #1528
=> Don't show 'report issue' in docker commands on volume and network inspect and delete

src/commands/containers/attachShellContainer.ts, src/commands/containers/selectContainer.ts
The attach shell command execution from command pallet was enabled on all containers. Now it is filtered to running container like how this command shows up in docker view.
Fixes #1576
=> Allow attach shell only on running containers

src/commands/compose.ts
If the workspace container only the default docker-compose files 
1. Just one file and it is named 'docker-compose.y(a)ml'
2. Two files docker-compose.y(a)ml and docker-compose.override.y(a)ml
then -f is not used and let the docker-compose pick these files.
Fixes #370
=> use default files in docker-compose

src/debugging/node/NodeDebugHelper.ts
Rename launch configuration "Docker Node.js Launch and Attach" to "Docker Node.js Launch
Fixes #1599
=> Rename docker node.js debug config

src/extension.ts
Temporarily disable the session tracking done for the purposes of prompting the user to fill out a NPS survey.
=> Disable NPS for the time being.

package-lock.json, package.json
This pull request updates the language server to the newly released version 0.0.22. This update helps fix #1337 and #1492.
Otherwise, there aren't a lot of big changes here outside of newly added support for the `--platform` flag in `FROM` instructions which was introduced in Docker CE 18.04. However, judging by the fact that no one ever reported this, this clearly doesn't bother anyone here.
Please use the Dockerfile below to compare the before/after behaviours.
```Dockerfile
FROM       scratch
FROM --platform=arm64 scratch
FROM --platform=arm64 scratch
FROM --PLATFORM= alpine
WORKDIR "/src/."
FROM store/intersystems/iris-community:
```
This update also fixes a very, very obscure bug that you can replicate with the Dockerfile below. If you have this file open and use the "Output" panel …
=> Upgrade language server version to 0.0.22

src/commands/containers/removeContainer.ts, src/commands/containers/restartContainer.ts, src/commands/containers/startContainer.ts, src/commands/containers/stopContainer.ts, src/commands/images/removeImage.ts, src/commands/networks/removeNetwork.ts, src/commands/volumes/removeVolume.ts, src/tree/registerTrees.ts, src/utils/multiSelectNodes.ts
Fixes #331, fixes #1453.
This PR is similar to #1620 (and also covers what #1494 does) but adds multi-select support to all of the explorer groups (except Registries), with multi-select support for the following commands:
Containers, Images, Networks, Volumes: Remove
Containers only: Start, Stop, Restart
It also will filter off nodes for which the action taken is not eligible (for example, parent nodes, or stopping an already-stopped container). Unfortunately it shows actions for whatever was the specific item in the selection set that was right-clicked (not actions that are valid for _all_ selected items) but we think that for the most part that will not be an issue.
Some of the remaining commands do not make sense as a multi-select (for example, Image > Copy full tag), some of the …
=> Add multi-select to context menu commands that most need it

src/utils/delay.ts, src/utils/refreshDockerode.ts
Resolves #1458 with @zifik's suggestion. Because an ssh-agent is required by the `ssh2` Node package (used by Dockerode) when using an SSH connection to a remote Docker daemon, we will show a warning with a Learn More link if SSH is in use without a working ssh-agent.
The check is done by looking at the value for `SSH_AUTH_SOCK` (which on Windows can be defaulted to `\\.\pipe\openssh-ssh-agent`), and then trying to connect to that pipe to ensure it is actually working.
The warning:
The link: https://aka.ms/AA7assy
=> Show a warning with Learn More link if SSH is in use without a working ssh-agent

src/configureWorkspace/scaffolding.ts
We get a fairly large number of spurious issues (e.g. #1559, #1628, #1629, and more) that occur because the user has not opened a workspace folder. This is not a bug and therefore should not have the Report Issue button.
=> Suppress report issue on Add Docker Files when no workspace is open

extension.bundle.ts, src/extension.ts, src/telemetry/TelemetryPublisher.ts, src/telemetry/TelemetryReporterProxy.ts, src/telemetry/surveys/activeUseSurvey.ts, test/telemetry/TelemetryPublisher.test.ts, test/telemetry/TelemetryReporterProxy.test.ts, test/telemetry/surveys/activeUseSurvey.test.ts
* Sketch hooking telemetry reporting.
* Start listening for events.
* Update global state with last event dates.
* Switch to swappable clock and disable NPS.
* Eliminate specific "clock" interface.
* Add TelemetryReporterProxy test.
* Add TelemetryPublisher tests.
* Sketch test of survey.
* Refactor to allow deterministic testing.
* Continue adding tests.
* Additional test.
* Tweaked selection.
* Add language check.
* Add tests for post-activation events.
* Test ignoring activation events.
* Fixup linter warnings.
* Refactor telemetry events.
* Fixed telemetry reporting.
* Add docs.
=> Adds "active use" tracking for survey purposes (#1626)

.vscode/launch.json, gulpfile.ts, test/assertEx.test.ts, test/configureWorkspace/configUtils.test.ts, test/debugging/coreclr/commandLineBuilder.test.ts, test/debugging/coreclr/dockerManager.test.ts, test/debugging/coreclr/lineSplitter.test.ts, test/debugging/coreclr/prereqManager.test.ts, test/nonNull.test.ts, test/tasks/TaskHelper.test.ts, test/telemetry/TelemetryPublisher.test.ts, test/telemetry/TelemetryReporterProxy.test.ts, test/telemetry/surveys/activeUseSurvey.test.ts, test/trimWithElipsis.test.ts, test/utils/nodeUtils.test.ts, test/windowsVersion.test.ts
Updates the VS Code launch configuration and Gulp tasks to allow running *only* the "unit" tests rather than *all* the tests. By not having to run the "integration" (i.e. automation) tests, the edit/build/test loop is much faster, ~10-15s instead of nearly 1 minute.
Unit tests are designated with a `(unit)` tag somewhere in the suite/test name.  Note, the test name tag was used rather than, say, re-arranging the file hierarchy to group unit/integration files as that better fits the existing build/test infrastructure.
Resolves #1640.
=> Allow unit tests to run independently

src/commands/containers/browseContainer.ts, src/configureWorkspace/configurePython.ts, src/debugging/python/PythonDebugHelper.ts, src/tasks/TaskHelper.ts, test/configure.test.ts
Changes:
- Launch tasks renamed to Docker: Python - Django, Docker: Python - Flask, Docker: Python – General
- Add "**/__pycache__" to .dockerignore
- Add a comment at the top of the requirements.txt file
- Handle executing "folders" as an app path
- Change wording for the "launchFile" prompt
- Move the "ports" prompt to be the last
=> [Python] Remove compose-debug + a couple of minor updates

src/configureWorkspace/configure.ts, src/configureWorkspace/configureDotNetCore.ts, src/configureWorkspace/scaffolding.ts, test/configure.test.ts
Now the dotnet core scaffolding will ask whether to generate compose files or not similar to node.js.
If an existing compose file is present, it will create docker-compose(n).yaml
=> .Net Core compose support

package.json, src/debugging/DockerDebugConfigurationProvider.ts, src/debugging/netcore/NetCoreDebugHelper.ts
The existing commands 'Add Docker Files to Workspace...' and 'Initialize for Docker Debugging' will add a new debug launch config 'Docker .NET Core Attach'.
This launch config does the following as part of resolve
1. Ask user to select a running container, if it is not provided in the launch config.
2. Install the remote debugger, if the remote debug path is not provided in the launch config.
3. Generate a coreclr attach launch config which will handle the actual attach.
related to #1543
=> debug dotnet by attaching to container

src/debugging/DockerServerReadyAction.ts
- Adds a `DockerLogsTracker` class that looks for the pattern in "docker logs"
- Adds `MultiOutputDockerServerReadyManager` which is essentially a combination of looking in the debug console and docker logs
- Some simple refactoring
For the most (if not all) cases, the pattern will be found in "docker logs" before it ever reaches the debug console. However, it might be safer to keep looking in the debug console just to cover cases that we might not know about.
These are pretty much @philliphoff's changes from that branch: https://github.com/microsoft/vscode-docker/compare/philliphoff-docker-logs
=> Look in Docker logs to determine if the server is ready

src/commands/images/removeImage.ts, src/commands/networks/removeNetwork.ts, src/commands/volumes/removeVolume.ts, src/utils/multiSelectNodes.ts
Fixes #1660. Because of the change from string to regexp, it matched parent nodes of the images / networks / etc. tab, in error (the RegExp did not have anchors at start/end of string). The quick pick thus returned the root node as a single object, and calling `.filter()` on the object was invalid.
Changing back to strings, and doing exact string comparison (which is what `AzExtTreeItem` does) in that case fixes it.
=> Fix filtering for Remove* multi-select commands

src/configureWorkspace/configurePython.ts, test/configure.test.ts
- Add 2 environment variables to the Dockerfile by default, one is to disable buffering logs and the other is to prevent Python from generating bytecode which can cause conflicts if the app the volume mapped
- Use explicit versions for the Python image and for the requirements file to ensure apps don't fail due to compatibility issues
- For Django, check if there exists a "wsgi.py" file in the location we think it should and if not then output a comment instructing the users to change that
=> [Python] Customer feedback items

.vscodeignore
I talked with @EricJizbaMSFT, the marketplace actually directly references the master branch for the images. When the old images were removed during restructuring of the README, the marketplace images quit working. If we wanted to fix it immediately we could just add those images back (and eventually, remove them again), but since we're planning to release soon it's probably not worth doing so.
Taking the images back out of the VSIX saves a little size (240KB), so it's worth doing.
=> Take readme images back out of VSIX

src/debugging/netcore/NetCoreDebugHelper.ts
Mac and Linux require single quote while executing the script on the target container. Handling it property now.
Fixes: #1665
=> Use proper quote based on host os while installing vsdbg

src/configureWorkspace/configurePython.ts, src/tasks/python/PythonTaskHelper.ts, src/utils/pythonUtils.ts
Switch to using the [Flask CLI](https://flask.palletsprojects.com/en/1.1.x/cli/) since it seems to be the modern way to run Flask apps and to ensure consistency with the Python extension.
=> Switch to using the Flask CLI as the entrypoint for flask apps

src/configureWorkspace/configurePython.ts, src/tasks/python/PythonTaskHelper.ts, src/utils/pythonUtils.ts
* Switch to using the Flask CLI as the entrypoint for flask apps
* Add comment explaining we override the entrypoint in debugging
=> [Cherry-pick] Switch to using the Flask CLI as the entrypoint for flask apps (#1690)

src/configureWorkspace/configureDotNetCore.ts
Do not add https port to ASPNETCORE_URLS in docker-compose.debug.yml. This results into failure to bring up a container. Not adding just the first port as http.
Fixes: #1695
=> Do not add https port to ASPNETCORE_URLS

src/debugging/netcore/NetCoreDebugHelper.ts
Check if the debugger is already installed on a container by checking the presence of the file vsdbg. If so, then skip the debugger installation.
Fixes: #1696
=> Reuse an existing debugger if present

src/configureWorkspace/configureDotNetCore.ts
The compose doesn't configure https so the 'Open in Browser' command will try to open https endpoint and will fail. So create the compose file that exposes only http.
Fixes #1720
=> expose only http port in compose

src/tasks/netcore/NetCoreTaskHelper.ts
Add the optional volume mount only when the local path is present.
Fixes: #1693
=> validate nuget package back up volume mount

src/configureWorkspace/configureDotNetCore.ts
(cherry-pick) expose only http port in compose (#1721)
Fixes: #1720
=> (cherry-pick) expose only http port in compose (#1721)

src/debugging/netcore/NetCoreDebugHelper.ts
The latest version of GetVsDbg.sh doesn't require unzip. So not installing unzip in non-alpine flavor OS
Fixes: #1727
=> don't install unzip

src/configureWorkspace/configureDotNetCore.ts
Earlier the docker file scaffolding was using the project file name as assembly name which breaks if assembly name is different than project file name. Now using the assembly name in docker file.
Fixes: #1583
=> use assembly name in entrypoint

test/configure.test.ts
These tests have been failing an awful lot lately; I'm going to disable them on Windows.
The root cause is the same for all of them, permissions error trying to open `testOutput\Dockerfile`.
=> Disable some faulty tests on Windows

src/tasks/DockerBuildTaskProvider.ts, src/tasks/DockerPseudoterminal.ts, src/tasks/DockerRunTaskProvider.ts, src/tasks/DockerTaskProvider.ts, src/utils/spawnAsync.ts
- Pass the stdErr buffer for both docker-build and docker-run task providers to ensure the error message makes its way to telemetry
- Add a new flag to the error from spawnAsync the determines if the error is already written through the handler to avoid duplication
=> Ensure stdErr is written to telemetry

src/configureWorkspace/configureDotNetCore.ts
Scaffold docker-compose with the right volume mount path for windows container.
Related: #1662
=> use correct volume mount path on windows

src/tree/registries/auth/AzureOAuthProvider.ts
Fixes #1776.
`cachedProvider.url` was empty because for Azure, that `cachedProvider` is shared across all registries in the entire Azure account. `authContext` however is specific to each ACR.
=> Fix login to Azure

package.json, src/commands/selectCommandTemplate.ts, src/tasks/python/PythonTaskHelper.ts
I added `--pull` to all of our `docker build` commands.
I'd like to do something for `docker-compose up`, but the [maintainers have spent years resisting adding such a feature](https://github.com/docker/compose/issues/3574). There _is_ the `docker-compose pull` command, however, the command lines would be ugly, and maybe incorrect because `docker-compose pull` does not allow for specifying compose files.
=> Pull by default whenever possible

src/commands/debugging/initializeForDebugging.ts, src/configureWorkspace/configureDotNetCore.ts, src/tasks/TaskHelper.ts, test/configure.test.ts, test/global.test.ts
This change will prevent user from creating docker specific tasks and config without the net core tasks.
During Net Core scaffolding, validate if the dotnet core build task is present or not and block scaffolding the docker specific tasks.
Fixes #1423, #1300
=> Validate dependency build task

package.json
This will essentially avoid reading this setting (if set in the User settings) in remote scenarios, which makes sense since the path might not make sense when running in a container/WSL.
=> Set scope to machine for imageBuildContextPath

package.json
Additional changes for #993. It seems to me that the four settings that control `DOCKER_*` environment variables ought to be machine-scoped. This might also fix #1769.
=> Make a few more settings machine-scoped

src/debugging/coreclr/CliDockerClient.ts, src/debugging/netcore/NetCoreDebugHelper.ts, src/utils/azureUtils.ts
net core 5.0 images removed the curl from base image and results into vsdbg install script on container. Now the vsdbg is copied to container from host machine.
Fixes #1794, fixes #1743
=> Copy vsdbg from host machine to container

src/commands/images/removeImage.ts, src/commands/images/runImage.ts, src/tree/containers/ContainerGroupTreeItem.ts, src/tree/containers/ContainerTreeItem.ts, src/tree/containers/ContainersTreeItem.ts, src/tree/containers/LocalContainerInfo.ts, src/tree/images/ImageTreeItem.ts, src/tree/images/LocalImageInfo.ts
Fixes #1529, #333 (both indirectly).
If we remove by name instead of by ID, then the 409 conflict error won't happen anymore. If there are child images, then this will simply remove the tag of the parent image; later on if the child is removed it will also remove this parent image (assuming there aren't any other tags).
=> Change to removing images by name

CONTRIBUTING.md
The extensions.json file has been updated to use the ESLint extension instead of TSLint.
This change removes the inconsistency.
=> Change to ESLint as recommended extension in CONTRIBUTING with the same in vscode extensions file

src/tree/registerTrees.ts, src/utils/dockerContextManager.ts
If a refresh was manually triggered (the command), then reset the timer on `docker context` checks. This will force a hash-check of the Docker config.json file; if needed then `docker context inspect` will be re-called.
As a result, clicking refresh manually should always show data from the immediately current Docker context.
NOTE: It is not needed for `vscode-docker.registries.refresh` because Dockerode is not involved in the registries.
=> If refresh is manual, reset docker ctx check timer

src/commands/debugging/initializeForDebugging.ts, src/debugging/DockerDebugConfigurationProvider.ts, src/tasks/DockerTaskProvider.ts
In order to avoid conflicts with other properties named "platform".
=> Rename platform to dockerPlatform

package.json, package.nls.json, src/tasks/DockerRunTaskDefinitionBase.ts, src/tasks/DockerRunTaskProvider.ts
This change allows the user to run a "short-term" container.
By setting this value to `true`, the container will be deleted after its use, using the `--rm` flag of the `docker run` command (default to false, current behavior).
It also helps to make the `dockerRun.containerName` parameter more useful, since a second run would block the task with this error:
> docker: Error response from daemon: Conflict. The container name "/`containerName`" is already in use [...]
Reference:
https://docs.docker.com/engine/reference/run/#clean-up---rm
**Note**: a container with the provided name **_must not exist_** to get this parameter to work (`docker run` command limitation).
=> Add cleanUp option to the docker-run task

src/configureWorkspace/configurePython.ts, src/tasks/python/PythonTaskHelper.ts
- If there isn't any chosen port that is less than 1024, then scaffold the logic to run as a low-rights user
- Else, show a warning at the top that this will be running as root
Related to #1766
=> Add logic to run with a low-rights user in Python

src/utils/dockerContextManager.ts, src/utils/refreshDockerode.ts
Fixes #1818, and along with PR #1816 gets us close enough to fix #1804.
If `~/.docker/contexts/meta` is empty then only the default, non-modifiable `DOCKER_HOST`-based context is available. Since we already handle setting `DOCKER_HOST` based on environment + VSCode setting, it is not necessary to call `docker context inspect` in this case.
I expect that for the majority of users, only the default context will be present.
=> Call `docker context inspect` only when needed

src/commands/dockerInstaller.ts, src/commands/installDocker.ts
There are several ways to get docker on Linux. So instead of trying to install using a generic script, we let the user install the docker.
=> Open docker install instruction page for linux

src/debugging/coreclr/CommandLineDotNetClient.ts, src/debugging/coreclr/LocalAspNetCoreSslManager.ts, src/debugging/coreclr/dockerManager.ts, src/debugging/coreclr/prereqManager.ts, src/utils/LocalOSProvider.ts, src/utils/platform.ts, test/debugging/coreclr/prereqManager.test.ts
Earlier osProvider.os was returning either Windows or Linux. This causes confusion because Linux could also indicate the Mac and callers had additional checks to further narrow down. So including the Mac as one of the values.
=> Update osProvider.os to include Mac

src/debugging/coreclr/CommandLineDotNetClient.ts, src/debugging/coreclr/LocalAspNetCoreSslManager.ts, src/debugging/coreclr/dockerManager.ts, src/debugging/coreclr/prereqManager.ts, src/utils/LocalOSProvider.ts, src/utils/platform.ts, test/debugging/coreclr/prereqManager.test.ts
This reverts commit 9a74120bebaacab239f6644d0d7be9a71c575862. This change is way too high risk this close to locking down for 1.1 release.
=> Revert "osProvider.Os to include Mac (#1843)"

src/configureWorkspace/configureDotNetCore.ts, src/utils/extractRegExGroups.ts
.Net 5.0 preview 3 generates the console project with below TFM
`<TargetFramework>net5.0</TargetFramework>`
During scaffolding we were looking for only netcoreapp5.0, hence it fails to identify net5.0. Also added the logic to look for the version in TargetFrameworks. Picks the first one defined in the list.
Fixes: #1856
=> adjust net core version extraction logic to handle net5.0

CHANGELOG.md
Fixes to the changelog:
- Full month name to be consistent with past entries
- Date is 20th, not 21st
This does _not_ require us to create a new build--the changelog is not included in the VSIX; the marketplace shows it directly from master branch.
=> Quick update to the changelog

package-lock.json, package.json, package.nls.json, src/extension.ts, src/utils/dockerContextManager.ts, src/utils/refreshDockerode.ts, src/utils/spawnAsync.ts
This PR does several things:
- Adds Docker Desktop installation ID to telemetry
- Captures the protocol (local pipe, TCP, SSH, HTTP(S), etc.) in more cases than just Docker context
- Captures the source of the ultimate Dockerode host choice (environment vs. VSCode setting vs. there's-only-one-Docker-context vs. default Docker context vs. custom Docker context)
- Offers a way to do totally bring-your-own-settings to Dockerode (related to #1459 or maybe fixes it)
Resolves #1819.
=> Refactor Docker context some

extension.bundle.ts, src/tasks/node/NodeTaskHelper.ts, src/utils/lazy.ts, test/utils/lazy.test.ts
(Not for 1.1)
Adds an `AsyncLazy` class that is smart enough to not re-run the task if it's currently running. Also adds lifetimes to force `Lazy`s to re-evaluate, if the caller so specifies.
One scenario where this would be useful is in places where we know we are going to query something several times in rapid succession--maybe `docker info`, as an example--and we expect no changes to occur in some time span (e.g. 1 second), but want to share the result across each of these queries to avoid re-running code unnecessarily.
=> Add an async lazy class and lazy lifetimes

package.json, src/tree/LocalRootTreeItemBase.ts, src/tree/containers/ContainerGroupTreeItem.ts, src/tree/containers/ContainerProperties.ts, src/tree/containers/ContainersTreeItem.ts, src/tree/containers/LocalContainerInfo.ts
A new property "Compose Project Name" is added to container. This will allow group by compose projects. This will also enable user to choose this new propery to be displayed on tree item label and description.
Fixes: #1846
=> Group containers by compose project name

package.json, package.nls.json, src/commands/registerCommands.ts, src/commands/registries/registryHelp.ts
Earlier the ? command on registries view was using generic help command. Now this is updated to open a registry specific help page.
Fixes #1894
=> Open a registry specific help topic from reqistry view

package-lock.json, package.json, src/telemetry/TelemetryReporterProxy.ts, test/telemetry/TelemetryReporterProxy.test.ts
Consume the latest vscode-azureextensionui that reports the error event using the latest API which filters out PII in the error message/stack.
=> telemetry changes for vscodespace

src/commands/dockerInstaller.ts, src/commands/installDocker.ts
Docker Desktop installer sometimes failed due to connection issue or proxy settings. Now we provider a better error message and also offer to manually download and install like below
Fixes: #1913 , #1926
=> Provider better error message for Docker Desktop installer download failure

src/configureWorkspace/configurePython.ts
Instead of volume mapping the debugger, we have it installed as part of the entry-point itself. The debugger is about 5.5 MB so it doesn't slow-up container start.
=> Scaffold compose-debug for Python apps

src/tree/contexts/ContextTreeItem.ts
Earlier the context tree item was using the label and when the label had a duplicate value the tree view construction failed. Now using unique id.
Fixes: #1932
=> Provide unique id for treeitem

src/commands/context/useDockerContext.ts, src/extensionVariables.ts, src/tree/LocalRootTreeItemBase.ts, src/tree/contexts/ContextTreeItem.ts
1. Show the loading icon next to the context being switched
2. New auto refresh will be blocked while context switch is in progress.
Fixes #1965
=> Show progress during context switch

src/configureWorkspace/configureDotNetCore.ts
=> Change repo for .NET 5.0+

src/commands/context/useDockerContext.ts, src/tree/LocalRootTreeItemBase.ts, src/tree/contexts/ContextTreeItem.ts
Fixes: #1965
* Show progress during context switch
* Address review feedback
* move the cache clearing logic to useDockerContext
* Apply suggestions from code review
Co-authored-by: Brandon Waterloo [MSFT] <36966225+bwateratmsft@users.noreply.github.com>
* remove unnecessary await
Co-authored-by: Brandon Waterloo [MSFT] <36966225+bwateratmsft@users.noreply.github.com>
=> Cherry pick - Show progress during context switch (#1969)

package.json, package.nls.json
=> Deprecate attach command settings

src/debugging/netcore/NetCoreDebugHelper.ts, src/utils/osUtils.ts
Earlier we were not handling the windows container during attach. Now added support. But `docker cp` command is not supported on hyper-v containers, which is the default in windows 10. So still this doesn't address most of the windows container. At least now this will provide a better error message.
Fixes: #1662
=> .Net Core Attach support for windows container

resources/python/launcher.py, src/configureWorkspace/configurePython.ts, src/debugging/DockerDebugConfigurationProvider.ts, src/debugging/python/PythonDebugHelper.ts, src/tasks/python/PythonExtensionHelper.ts, src/tasks/python/PythonTaskHelper.ts
Here is how the flow of the launch request works:
_(host) [VSCode] -> (host) [Debug Adapter] -> (host) [Custom launcher] -> (container) [Debugpy launcher] -> (container) [debugpy]_
We added our own custom launcher which doesn't do much but pass the call to the real launcher in the container using a `docker exec` command.
When debugpy gets the request, it connects back to VSCode on the specified host:port. For Windows/Mac, we use `host.docker.internal:{randomPort}`, however this doesn't work for Linux. So we use the ip address from Docker's predefined network "bridge" and it works in all of the cases I tried (we might need to check with Docker so that we're not basing off wrong assumptions).
The rest of the changes get rid of the attach logic we have.
=> [Python] Use debugpy launch

src/debugging/coreclr/dockerNetCoreDebugConfigurationProvider.ts, src/debugging/coreclr/prereqManager.ts
Fixes an issue with #1952 and also deals with the new C# extension publisher.
=> Fix issues with deprecation warning

src/commands/registries/logInToDockerCli.ts
=> Fix warning text

src/commands/containers/attachShellContainer.ts, src/commands/containers/browseContainer.ts, src/commands/containers/inspectContainer.ts, src/commands/containers/viewContainerLogs.ts, src/commands/images/copyFullTag.ts, src/commands/images/inspectImage.ts, src/commands/images/pushImage.ts, src/commands/images/runImage.ts, src/commands/images/tagImage.ts, src/commands/networks/inspectNetwork.ts, src/commands/volumes/inspectVolume.ts, src/debugging/netcore/NetCoreDebugHelper.ts, src/utils/multiSelectNodes.ts
Fixes #2029
This intentionally does _not_ do the same thing for registries and contexts, as those should not be nearly as volatile as containers especially, and to a lesser extend images, networks, volumes.
=> Refresh before running tree item picker

resources/python/launcher.py, src/utils/pythonUtils.ts
The issue here is that since we pass in the args (i.e. --host 0.0.0.0 --port 5000) as a list in order to ensure proper escaping, then each arg/value has to be its own entry in the args list. For example, it should look like this:
```
"args": [
"run",
"--no-debugger",
"--no-reload",
"--host", "0.0.0.0",
"--port", "5000"
]
```
Instead of this:
```
"args": [
"run",
"--no-debugger",
"--no-reload",
"--host 0.0.0.0",
"--port 5000"
]
```
This PR changes the scaffolding to make sure it's in the proper format, and also falls back to concatenating the args into a single string and pass that command for Python to execute. This compromises the escaping (**note**: it is already not handled in the released version, so this is not a regression), however it ensures we do not break existing projects on …
=> [Python] Fix an issue with args escaping in the custom launcher

resources/python/launcher.py, src/debugging/python/PythonDebugHelper.ts, src/tasks/python/PythonExtensionHelper.ts, src/tasks/python/PythonTaskHelper.ts
There is a recent breaking change since the location of "debugpy" changed in the Python extension. So the resolution is to use an API provided by the Python Extension to resolve the location of the debugger to be used.
=> [Python] Use the Python Extension API to get the debugger location

resources/python/launcher.py, src/debugging/python/PythonDebugHelper.ts, src/tasks/python/PythonExtensionHelper.ts, src/tasks/python/PythonTaskHelper.ts
There is a recent breaking change since the location of "debugpy" changed in the Python extension. So the resolution is to use an API provided by the Python Extension to resolve the location of the debugger to be used.
=> Cherry-pick debugpy path API

src/debugging/python/PythonDebugHelper.ts
Handle the case where the debug configuration is undefined and let VS Code show its default error message:
=> [Python] Handle the case where the debug configuration is undefined

package.json, src/commands/context/inspectDockerContext.ts, src/commands/context/removeDockerContext.ts, src/commands/context/useDockerContext.ts, src/tree/contexts/ContextTreeItem.ts, src/tree/registerTrees.ts, src/utils/refreshDockerode.ts
Fixes #2098
1. Context tree is no longer multi-select enabled (removing multiple contexts at once is not a realistic use case, and inspect and use aren't enabled anyway [use isn't even possible for multi-select nor does it make sense])
1. The default and current context cannot be removed--the "Remove" option won't even appear in the context menu, nor will the default or current context show when using "Remove" from the command palette
1. Help tree is no longer multi-select enabled (it never needed to be)
Can't remove in-use custom context, or default context, from tree:
Or from palette:
Upon switching back to default:
=> Better UX on context removal

src/commands/selectCommandTemplate.ts
Due to frequent user error of setting a command setting to an invalid value, I'm adding some robustness so that in that scenario, it will ignore the invalid value and fall back to the universal default.
#2030, #2072, #2108
=> Robustness to malformed user settings

src/debugging/DockerDebugConfigurationProvider.ts, src/tasks/DockerRunTaskProvider.ts
=> Capture if dependent tasks are found

package.json, package.nls.json, src/commands/context/aci/createAciContext.ts, src/commands/registerCommands.ts, src/docker/ContextManager.ts
Fixes (mostly) #2114. Adds support for creating an ACI context in the command palette and contexts view. The command will _not_ show up unless we can positively confirm that the new CLI is present, according to the following rules--
1. If another ACI context already exists, OR
1. If the output of `docker serve --help` starts with "Start an api server"
TODO: add screenshots
=> Support creating an ACI context from palette / contexts view

package-lock.json, package.json
This update provides the following changes:
- continued improvements and fixes to the semantic tokens parser (#2055)
- editor visuals for the deprecated `MAINTAINER` instruction
- linting fixes due to incorrect calculations of ranges
- navigation of build stages (#2043)
Please use the Dockerfile to test the new changes and bug fixes.
```Dockerfile
FROM alpine AS base
FROM base
MAINTAINER user
RUN --mount=X=Y,A echo
FROM scratch
ENV \
```
The following Dockerfiles have very specific whitespace characters to reproduce the error in question. Simply copy and paste the content into a Dockerfile and and open the Output panel and select the Dockerfile Language Server to verify that there are no errors being logged. Do not save the file as the formatter will change the integrity of the file. …
=> Upgrade language server to 0.1.0

src/commands/context/aci/createAciContext.ts, src/utils/azureUtils.ts
This substantially mitigates #1959 or possibly eliminates the issue entirely. Changing the ADAL token <=> ACR token exchange's `grant_type` to `access_token`, and not passing in the ADAL `refresh_token`, dramatically reduces the size of the obtained ACR `refresh_token`. My token's size was pretty consistently about 950 bytes, compared to > 2600 before.
It may be functionally impossible to get a token using this different mechanism that is too long for Docker CLI. We won't update people's existing Docker configs (at least not now...), but we hopefully will never need to suggest disabling Wincred again.
The disadvantage to this grant type is that if the ADAL `access_token` is near expiry, they (ACR) will not be able to use the ADAL `refresh_token` to get a new one--however, that shouldn't …
=> Use access_token grant instead of refresh_token

src/commands/context/aci/createAciContext.ts
Removes the location step from the ACI create flow, because the CLI ignores it anyway and just uses the resource group's location.
=> Remove the location list step

src/commands/compose.ts, src/docker/ContextManager.ts
=> Rewrite compose commands for ACI contexts

src/configureWorkspace/configure.ts, src/configureWorkspace/configureGo.ts, src/configureWorkspace/configureJava.ts, src/configureWorkspace/configureNode.ts, src/configureWorkspace/configureOther.ts, src/configureWorkspace/configureRuby.ts, test/configure.test.ts
Fixes #2090
NOTE: the "Other" scaffolding still uses the other form (`CMD /usr/games/fortune -a | cowsay`). I don't think there's value in changing that for two reasons--
1. The "Other" Dockerfile is little more than a demonstration of how Dockerfiles look.
1. The intended behavior of the image does not work when using the EXEC form + `sh`, `-c`. It is supposed to output a random bit of text (the output from `/usr/games/fortune`) and put it into a text box being spoken by the Docker whale (the pipe into `cowsay`). If the EXEC form is used, nothing is output to the terminal doing the `docker run`; instead the output is just into the container itself.
=> Use recommended EXEC form of commands

src/debugging/netcore/NetCoreDebugHelper.ts
Fixes issue 2186 https://github.com/microsoft/vscode-docker/issues/2186
Also adds a bit more information about debugger copying to the output
=> Fix issue 2186

src/telemetry/surveys/SurveyManager.ts
For slight performance gain we can disable the NPS survey since we do not have the experiment enabled at this time.
@BigMorty Are you OK removing this? Here's the implications--
1. Slight performance improvement
1. We can't re-enable this NPS survey from server side
NOTE: For the next NPS survey, we will need to make a code change anyway--to advance the survey ID from `nps2` to `nps4` (I skipped 3 because we called this one "NPS 3" in the experimentation service).
=> Disable NPS survey for now

src/telemetry/surveys/SurveyManager.ts
=>  Add slush time for survey activation

resources/templates/netCore/docker-compose.debug.yml.template, resources/templates/netCore/docker-compose.yml.template
Opening based on [this comment](https://github.com/microsoft/vscode-docker/issues/2228#issuecomment-692006276). A template change will make .NET friendlier to compose up. Other platforms don't typically use ports < 1024 so don't really need this.
This change allows Docker to randomly assign the host-side ports rather than them being fixed to 80 by default.
Side note: this new template-based code makes maintenance so much easier!
=> Template change to make .NET scaffolding friendlier

package.json
Fixes #2317. This "when clause" is the same as what we use for the "Build Image" context menu option for Dockerfiles, plus `isAzureAccountInstalled`. The files now counted also match what we treat as a Dockerfile for language purposes.
=> Allow building in Azure for any "Dockerfile" / "Dockerfile.*" / "*.dockerfile"

resources/templates/node/Dockerfile.template, resources/templates/python/Dockerfile.template
Hi,
In our docs.docker.com we've removed the examples that used the old syntax `ENV key value` and replaced it with the better `ENV key=value` syntax (related https://github.com/docker/docker.github.io/pull/11414). 
The old style had its problems when using multiple environment variables `ENV ONE TWO= THREE=world`
Just yesterday I used the Docker extension in preparation for a Docker beginners video course and saw that the Docker extension uses the old style.
This PR changes the templates to the new style and helps users to use the good practice.
=> Use ENV key=value in Dockerfile templates

resources/templates/docker-compose.debug.yml.template, resources/templates/docker-compose.yml.template, resources/templates/java/docker-compose.debug.yml.template, resources/templates/netCore/docker-compose.debug.yml.template, resources/templates/netCore/docker-compose.yml.template, resources/templates/node/docker-compose.debug.yml.template, resources/templates/node/docker-compose.yml.template, resources/templates/python/docker-compose.debug.yml.template, resources/templates/python/docker-compose.yml.template, src/debugging/DockerDebugScaffoldingProvider.ts, src/debugging/node/NodeDebugHelper.ts, src/scaffolding/wizard/GatherInformationStep.ts, src/scaffolding/wizard/ScaffoldDebuggingStep.ts, src/scaffolding/wizard/ScaffoldFileStep.ts, src/scaffolding/wizard/ScaffoldingWizardContext.ts, src/scaffolding/wizard/netCore/NetCoreGatherInformationStep.ts, src/scaffolding/wizard/node/NodeGatherInformationStep.ts, src/tasks/node/NodeTaskHelper.ts
Fixes #2057. Also makes locating files a little more consistent and puts the platform-specific code for that with the platforms themselves.
Tested:
=> Enable debugging node apps in subfolders

src/commands/images/runAzureCliImage.ts
Fixes #2412, fixes #474.
This switches to the new MCR image for the Azure CLI, and also maps in the workspace folder.
=> Fixes/improvements to Azure CLI command

src/commands/containers/attachShellContainer.ts, src/commands/images/runAzureCliImage.ts, src/utils/executeAsTask.ts
=> Attach shell should take focus

package.json
Fixes #2356, but even better than we expected. IMO the user experience here is the best possible.
When the user first connects to the remote session, the Extensions page directs them to install Docker in the remote (which is what we want almost everybody to do):
Once they install it in the remote, it starts working right away:
(Notice the name of the image--makes it easy to tell that it's getting this data from Docker on my SSH target)
HOWEVER! Here's the good part that I did not expect. The user can forcibly override it to use UI mode, using the setting:
```json
"remote.extensionKind": {
"ms-azuretools.vscode-docker": [
"ui"
]
}
```
When they apply this setting and reload VSCode, Docker becomes active in UI mode:
(These are images on my local machine)
=> Remove extension kind from package.json

src/docker/ContextManager.ts, src/extension.ts
Fixes #2371.
This covers:
In the most common case (no Docker contexts, therefore don't need to run CLI), the remaining time spent on activation is mostly dominated (~75%) by Dockerode loading. Nevertheless that will stay as-is; it was an improvement to lazy load the Docker client provider.
=> Improve extension activation time

src/commands/startPage/StartPage.ts
Fixes an issue where the codicons were not showing up in the bundled extension:
With the fix:
=> Fix codicons root path in bundled extension

src/docker/files/ContainerFilesUtils.ts
Updates the `stat()` metadata retrieval calls for Windows containers to retry their calls using different Docker users if the preceding call fails or does not return any data.  Resolves an issues seen on some containers where we were able to list a directory/file (e.g. because we already have retries in that logic) but then not be able to get its metadata.
=> Try, try again (with different Windows users)

src/docker/DockerodeApiClient/DockerodeApiClient.ts
Fixes #2483. The existing environment is cloned and the `DOCKER_*` variables added from VSCode's settings. I was able to successfully browse files in both local and remote Linux containers from a Windows machine.
=> Include Docker environment settings

CHANGELOG.md, package-lock.json, package.json, src/debugging/python/PythonDebugHelper.ts, src/docker/ContextManager.ts, src/tasks/python/PythonExtensionHelper.ts
According to [this comment](https://github.com/microsoft/vscode-docker/issues/2455#issuecomment-724267419), this should be the changes needed on the Docker side to fix #2455.
@int19h, if I understand the flow correctly, I think that the Python extension handles `debugAdapterPython` and `debugLauncherPython`. The `debugLauncherPython` Python interpreter will start our "launcher", which then unconditionally uses `python3` to start the real debugpy launcher inside the container: https://github.com/microsoft/vscode-docker/blob/master/resources/python/launcher.py#L17
Then, using the `"python": "python3"` option in this PR, the launcher inside the container uses `python3` to launch the app, which is what is desired.
Does all this sound right?
=> Use `python3` as the Python path within containers

resources/templates/python/Dockerfile.template
Hi,
Docker docs [suggests](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#add-or-copy) to use COPY for files and directories that do not require ADD’s tar auto-extraction capability. So there is a little change.
=> Replace ADD with COPY

src/extension.ts
This change makes it so the extension will export the needed `Memento` objects, if (and only if) the `VSCODE_DOCKER_TEAM` environment variable is set to `1`. This allows for using the [Memento Explorer extension](https://marketplace.visualstudio.com/items?itemName=bwater.memento-explorer) (shameless plug) to tweak the `Memento` storage. This makes it a lot easier to test scenarios like #2496.
=> Memento explorer capability

src/docker/ContextManager.ts
Fixes #2541. @ucheNkadiCode what do you think of the below?
Depending on whether the problem is with `DOCKER_HOST` env var or `docker.host` setting, a different message will be shown. In both cases, an "Open Settings" button is shown that takes the user directly to the `docker.host` setting.
Settings page opened to `docker.host`:
=> Improve messaging for invalid URL error

package.json, package.nls.json, src/commands/containers/files/downloadContainerFile.ts, src/commands/registerCommands.ts
Currently users can open (text) files of running containers in the VS Code editor.  This change adds a new download command that, like in VS, allows the user to instead extract files from running containers and save them in a user-selected local folder.  Multiple files can be downloaded at a given time.  If the file already exists in the selected folder, the user will be prompted to skip that file, overwrite that file, or to cancel any remaining download.
Resolves #2466.
=> Allow users to download container files

package-lock.json, package.json, src/docker/ContextChangeCancelClient.ts, src/docker/DockerApiClient.ts, src/docker/DockerodeApiClient/DockerodeApiClient.ts, src/extension.ts, src/utils/promiseUtils.ts
This new release depends on `vscode-languageclient` 7.0.0 which has introduced some API changes. It seems like it no longer re-exports some VS Code API types so I've changed imports from `vscode-languageclient` to `vscode` where applicable.
This update to 0.2.0 brings two small fixes to the editor. As always, just copy/paste the examples below in a Dockerfile editor and do not save (as auto-formatting may change the content that is being parsed).
1. Having an escaped newline as the only argument of an instruction should not be valid. This will now be flagged as an error correctly.
```
FROM alpine
USER \
```
2. This used to cause an infinite loop and break semantic highlighting. This bug has now been fixed.
```
FROM alpine
ENV a \
b
```
```
[Error - 10:15:15 AM] Request …
```
=> Upgrade to language server 0.2.0

src/scaffolding/scaffoldCompose.ts, src/scaffolding/wizard/VerifyDockerfileStep.ts
Fixes #2566.
If they click the "Add Docker Files" button, it will essentially assume that they want Dockerfiles *and* compose files, i.e. equivalent to running "Add Docker Files..." + compose = yes. In most or all cases, the user has already answered all the necessary questions, so it will not need to prompt again for them to answer.
The prompt looks like this:
=> Prompt to add Dockerfile first

src/docker/DockerServeClient/DockerServeUtils.ts
Fixes #2602.
ACI has new states "Node Pending" (which is part of startup, equivalent to "Waiting" for our purposes), and "Node Stopped" (part of shutdown, equivalent to "Terminated" for our purposes). It seems that it doesn't always go through "Node Stopped", sometimes it appears to skip directly to "Terminated". Either way, it always ends up at "Terminated". I have not seen it skip "Node Pending", but it's probably safe to assume that is a possibility.
=> Map new ACI states

package.json, resources/templates/.dockerignore.template, src/constants.ts, src/telemetry/registerListeners.ts
Fixes #2618. This will _not_ make the icons for "compose.yaml" etc. show up as the pink whale; that is controlled by the file icon theme. However, the easiest thing to do would be to ignore that issue for now, and resolve it when creating a compose language. See here for more info: https://github.com/microsoft/vscode-docker/issues/2618#issuecomment-764804032
=> Recognize "compose.yaml" as a compose file

src/constants.ts
Changing the OCI client ID based on [this comment](https://github.com/microsoft/vscode-docker/pull/2660#issuecomment-765505114) from @SteveLasker
=> Change OCI client ID based on feedback

package.json
Adds inline commands for container file open/download (which is sometimes quicker than the context menu).  Also makes the open command first (as that's most likely the one being used).
=> Add inline open/download commands and tweak order

package.json, package.nls.json, src/commands/compose/compose.ts, src/commands/registerCommands.ts, src/extension.ts
Fixes #2646. This adds a new option to launch a subset of services directly; basically it is equivalent to appending `${serviceList}` to the end of your compose command. This is gated by an experiment.
=> Subset of services experiment

src/utils/getHandlebarsWithHelpers.ts
On machines, when mapping volumes using a Compose file, the volume keeps the non-ugly Windows format. So, the regex will not match.
=> Fix bug with volume paths

src/tree/registries/gitLab/GitLabAccountTreeItem.ts, src/tree/registries/gitLab/gitLabRegistryProvider.ts
Fixes #1968 (and #2688). Using OAuth for GitLab is no longer feasible since it requires the user to register a client application and provide that app ID and secret in addition to username and password. Personal access token auth is the only realistic option at this point.
=> Change to use PAT auth for GitLab

package.json, src/docker/Images.ts, src/tree/images/imageChecker/OutdatedImageChecker.ts
This change does several things:
1. Uses the `Accept: application/vnd.docker.distribution.manifest.list.v2+json` header to enable doing `HEAD` requests--not subject to rate limiting--to check if an image is out-of-date
1. Re-enables out-of-date checking by default
1. Returns out-of-date checking to once per session instead of once per day. I don't feel strongly that it ought to be once-per-session, so if desired I can keep it at once-per-day.
I'd be OK with putting this in either 1.10.0 or 1.11.0.
=> Use `HEAD` request to get digest

package-lock.json, package.json
This version of `vscode-azureextensionui` reverts the prior change which was done to fix #2679. The upstream bug in VSCode was fixed so we no longer need to do anything special.
=> Update `vscode-azureextensionui` to 0.38.6

package.json, package.nls.json, src/tasks/DockerComposeTaskDefinitionBase.ts, src/tasks/DockerComposeTaskProvider.ts
Adds a `envFiles` property to the Docker Compose up/down tasks, which generate `--env-file` arguments on the `docker-compose` command line.
Resolves #2701.
>NOTE: Waiting to merge this PR until after 1.10 is out the door.
=> Support environment files in Docker Compose tasks

src/tasks/python/PythonTaskHelper.ts
=> Remove Python code to override entrypoint

src/tasks/python/PythonTaskHelper.ts
Fixes #2725 (for real this time).
Python is different from .NET, in that with .NET we never make it to the `ENTRYPOINT` directive since we build only the first stage of the Dockerfile. Python builds the full Dockerfile, so the `CMD` directive _is_ reached, and the image no longer has `python` as the default, idle entrypoint. Thus, we _do_ need to set an idle entrypoint of `python3` in order to work.
The code as written will now respect user input for `command` or `entrypoint`, and if both are falsy, will use `python3`.
=> Fix bug in Python entrypoint logic

src/tree/LocalRootTreeItemBase.ts, src/tree/containers/ContainersTreeItem.ts
Fixes #2744. When the tree ID changes, if you right clicked the object with the "old" ID, then choose an action--that item is lost now. It will drop the quick pick to make you go find the container again. This is really annoying.
During the first minute of a container's life, the tree ID is changing every ~2 seconds, which makes right click actions very difficult to do.
This change makes it so that we consider the container label for the purposes of deciding whether or not to refresh, but without changing its tree ID, so right click contexts isn't lost.
=> Fix up right-click behavior by not changing tree IDs so much

CHANGELOG.md, package-lock.json, src/docker/files/ContainerFilesUtils.ts
Fixes #2739. I tried out the command line that it comes up with--both the `stat` and `ls` commands--and each works on both cmd and PowerShell. (Also, of course, I tried it out in the UI)
In theory this should have no effect on Unix but I also validated on my Macbook just to be sure.
=> Change quoting on Windows hosts

package.json, src/extension.ts
This change does two small things in 1.11, since 1.12 will not come out until a bit _after_ VSCode 1.55, which contains the new compose language ID.
1. Adds an activation event for `onLanguage:dockercompose`, so that the extension will be activated.
1. Adds a document filter for all `dockercompose` documents so the hover and completion providers work.
=> Compatibility with 1.55

src/commands/containers/composeGroup.ts
=> Use project name in compose group calls

src/tree/containers/ContainersTreeItem.ts
If the Containers tree view had an error node instead of an empty array, the `areArraysEqual` implementation would throw because it was trying to do `.some()` on `undefined`. This adds a guard against one or both of the arrays being `undefined`, while mirroring the behavior of the base class' implementation if both were `undefined`.
=> Prevent uncaught background errors

package-lock.json, package.json, src/commands/registries/azure/DockerAssignAcrPullRoleStep.ts, src/commands/registries/azure/DockerSiteCreateStep.ts, src/commands/registries/azure/DockerWebhookCreateStep.ts, src/commands/registries/azure/deployImageToAzure.ts
Fixes #1685 so we can finally stop punting it. :smile:
Still need to verify:
=> Use managed service identity for pulling from ACR

src/commands/registries/azure/deployImageToAci.ts, src/tree/contexts/aci/AciContextCreateStep.ts, src/utils/azureUtils.ts
Fixes #2775.
In the "Create ACI Context" case, the user must already be signed in to the Azure Account extension--we use it to have them pick a subscription and resource group--so knowing the cloud ID is trivial.
In the "Deploy to ACI" case, the Azure Account extension is not required, simply having an existing ACI context is sufficient. There's not a good way to know what region an ACI context belongs to with any `docker context inspect` / etc. calls. So, if deployment fails due to expired token / not signed in / etc., we will have to prompt the user for which cloud to sign in to.
=> Support sovereign clouds with ACI features

resources/startPage.html.template, src/commands/startPage/StartPage.ts
Text is unchanged, but moves the What's New blurb to the bottom. Looks like this now:
=> Move the What's New section to the bottom of the page

README.md
I noticed on the installation page in vscode that linux users are recommended to enable the Docker CLI for non-root users, but this can have some significant security considerations. I am proposing to add a section before this that recommends a rootless Docker configuration. I am running Ubuntu Desktop 20.04 and rootless Docker appears to work well with the extension.
=> Updating README with guidance to use rootless Docker for linux users

resources/templates/netCore/Dockerfile.template, resources/templates/python/Dockerfile.template
Fixes #2821 using a command that works on both Alpine and Buster images, for both .NET and Python. However I think it's kind of ugly. Alternatively, we could won't-fix or use documentation. @ucheNkadiCode @karolz-ms what do you think? Personally I'd say just live with the ugliness but I'm interested to hear what you think.
=> Use `adduser` instead of `useradd`

package-lock.json, package.json
This release comes with a few fixes for some false positives in the linter and an infinite loop fix for semantic tokens. It also comes with some very rudimentary support for code completion based on `WORKDIR` instructions.
Please use the Dockerfiles below for testing.
```Dockerfile
FROM scratch
ARG a=b b
ENTRYPOINT powershell -Command \
kubectl port-forward --address ${env:address} pod/${env:podname} ${env:source}:${env:dest} -n ${env:namespace}
CMD powershell -Command \
kubectl port-forward --address ${env:address} pod/${env:podname} ${env:source}:${env:dest} -n ${env:namespace}
ENV FOO=${FOO:?}
LABEL "com.github.actions.name"="Spell Checker"\
"com.github.actions.description"="Check repository for spelling errors"\
"com.github.actions.icon"="edit-3"\
"com.github.actions.color"="red"\ …
```
=> Upgrade to language server 0.4.1

resources/templates/netCore/docker-compose.debug.yml.template, resources/templates/netCore/docker-compose.yml.template
Fixes #2825. This is basically reverting #2314. Since .NET now uses ports > 1024 by default, it isn't as important to allow Docker to randomly assign ports.
This now brings .NET to parity with all our other platforms, which also use fixed ports.
=> Use fixed ports for .NET in compose files

src/utils/quickPickWorkspaceFolder.ts
=> Use `workbench.action.files.openFileFolder` on Mac

src/scaffolding/wizard/netCore/NetCoreGatherInformationStep.ts, src/tasks/python/PythonExtensionHelper.ts
A fix in main branch for #2867. SemVer comparisons should be using `.lt()`, `.gte()`, etc. I verified the other places.
=> Fix semver comparisons

CHANGELOG.md
Cherry-picks the changelog update from #2871.
=> Cross-cherry-pick #2871: Update changelog

.github/needs_more_info.yml
Right now our front page of issues has 13 needs-more-info issues, out of 25 total. It's been getting pretty crowded lately.
Additionally, anecdotally I feel like nothing ever happens between days 14-21; I think almost all the customers who are going to respond do so within 7 days, so I think a 14 day closeout time is reasonable.
=> Shorten "needs more info" close timer from 21 to 14 days

package-lock.json, package.json
Gets rid of vulnerable dependency warning
=> Update vsce dependency

src/commands/startPage/StartPage.ts
Fixes issue https://github.com/microsoft/vscode-docker/issues/2820
The poblem is likely due to a handful of async calls done beteween when the start page view is created and when its content is set. That gives the user an opportunity to close the start page before we attempt to set its content. It is especially tempting since during the time the content is computed the already-visible start page panel is empty.
This change front-loads that async processing so that the webview creation becomes fully synchronous.
=> Fix "webview is disposed" error

package.json, package.nls.json
Adds the missing description for the `package` property of the `node` options of the Docker debug launch configuration.
Resolves #2956.
=> Add missing description for debug config property.

CHANGELOG.md, package-lock.json, package.json, src/commands/registries/azure/DockerSiteCreateStep.ts
=> Merge rel/1.13.0 to main

package.json, package.nls.json
Some users want to format instructions that span multiple lines in Dockerfiles themselves. The new setting added here will allow users to decide whether instructions that span multiple lines should be ignored by the formatter or not.
```Dockerfile
FROM scratch
RUN echo && \
echo && \
echo && \
echo
```
1. Create the Dockerfile above.
2. Format the document. The lines in the `RUN` instruction will be formatted.
3. Undo the change so that it's back to its original form.
4. Open the `settings.json` file and add the following setting.
```JSON
{
"docker.languageserver.formatter.ignoreMultilineInstructions": true
}
```
5. Format the document again. The `RUN` instruction should not be formatted.
This fixes #992 and #2004.
=> Enable formatter to skip instructions that span multiple lines

src/scaffolding/wizard/netCore/NetCoreGatherInformationStep.ts
These images provide more complete development environment than default ones. In particular, `ps` executable is included, which is not the case for the default images. This executable is used during debugger attach scenario.
=> Use Ubuntu 20.04-based images for .NET scaffolding

package-lock.json, package.json, src/scaffolding/wizard/netCore/NetCoreGatherInformationStep.ts
Somehow we did not realize that we explicitly ask the user whether they want Windows or Linux container. That makes it easy to use slightly different base image in these two cases.
Please disregard changes to package files (there is separate PR for these)
=> Use correct base image for Windows containers

package-lock.json, src/commands/registries/azure/DockerSiteCreateStep.ts, src/commands/registries/azure/WebSitesPortPromptStep.ts, src/commands/registries/azure/deployImageToAzure.ts
When deploying the app service in custom location, now provide an option for user to specify the web site port, which is needed if the app is listening on any port other than 80.
fixes #2972 #2973
=> Prompt for port during custom location deployment

package-lock.json, package.json, test/runTest.ts
vscode-test be marked as [deprecated](https://www.npmjs.com/package/vscode-test) on npmjs.org(yarnpkg.com), so just replace vscode-test with latest @vscode/test-electron for `vscode-docker`'s CI. cc @karolz-ms @bwateratmsft
=> chore: replace deprecated vscode-test with @vscode/test-electron

package-lock.json, package.json, package.nls.json, src/commands/compose/compose.ts, src/commands/images/buildImage.ts, src/commands/registries/azure/tasks/buildImageInAzure.ts, src/commands/registries/azure/tasks/runFileAsAzureTask.ts, src/scaffolding/scaffold.ts, src/scaffolding/scaffoldCompose.ts, src/scaffolding/scaffoldDebugConfig.ts
Fixes #2829. Please let me know if you think of any other actions or settings that should require trust!
**Actions that will not be enabled in an untrusted workspace**
- Building images and compose up/down/etc.
- Scaffolding
- Building images in Azure or running files as tasks in Azure
- Running tasks (disabled by VSCode entirely, no additional work for us)
- Debugging (disabled by VSCode entirely, no additional work for us)
Note, actions are disabled both by visibility (`when` clauses in package.json) and programmatically (checks to `vscode.workspace.isTrusted`).
**Settings that will not be enabled in an untrusted workspace**
- Anything pertaining to Docker target host--`docker.host`, `docker.context`, `docker.dockerodeOptions`, `docker.certPath`, `docker.tlsVerify`, `docker.machineName` …
=> Add support for Workspace Trust

src/tree/containers/ContainersTreeItem.ts
This (mostly) fixes #2983. It's not a perfect fix but it's probably about the best we can do given the limitations of the framework and VSCode's tree views, while still showing the container status in the tree node.
To summarize, the problem is happening because during the first minute of a container's life, the text for the `Status` property is rapidly changing (i.e. "Up 2 seconds", "Up 4 seconds", "Up 6 seconds"...). VSCode, or at least our tree view framework, doesn't really offer a good way to do UI-only refreshes. Consequently, the entire tree is getting refreshed, including the files node. For most of the tree this isn't really a big deal, but file ops are *far* slower due to needing to use the CLI. If a user right clicks before a refresh, then clicks a command (e.g. open file) …
=> Normalize container status to mitigate excessive refresh

src/commands/startPage/openStartPage.ts, src/extension.ts
to avoid showing the same update page to the same user on different machines over and over again
It happens in context of remote development, see for instance gitpod-io/gitpod#4566 (comment)
Also see https://github.com/microsoft/vscode-docs/issues/4699
=> [remote] sync version across different machines

src/commands/containers/browseContainer.ts, src/debugging/netcore/NetCoreDebugHelper.ts
Fixes #3019. Same fix as https://github.com/OmniSharp/omnisharp-vscode/commit/9dd0b0f12f391110520d7b56b9d7f7414b051d8d#diff-001347cc727cf0cda0ccc53a07a92207e342ab83fe88aaa789b752a9e9ea5832L303.
Also fixes unrelated #3091. A telemetry property was set as an integer value which is not allowed. This has gone unnoticed up until this point, but the recent work to add additional telemetry property masking in `vscode-azureextensionui` exposed the problem.
=> Fix regex for "Now listening..." in .NET 6

src/commands/compose/compose.ts, src/docker/ContextManager.ts, src/docker/DockerServeClient/DockerServeClient.ts, src/docker/DockerServeClient/DockerServeUtils.ts, src/tree/contexts/ContextTreeItem.ts
Partially fixes #3054; in most cases on Docker Desktop (Mac and Windows) we will be able to use the gRPC daemon for the context lookup which is quite a bit faster than the CLI.
=> Refactor context lookup logic yet again

.azure-pipelines/common/setup.yml, .github/workflows/node.js.yml
Part of #2606.
Blocked by https://github.com/microsoft/vscode-test/issues/103 at the moment.
=> Add GitHub action (and update AZDO pipeline to Node 14.x)

package.json, package.nls.json, src/commands/containers/composeGroup.ts, src/commands/registerCommands.ts
Fixes #2895. The options are added on compose groups.
**Note:** I didn't make an effort to hide "Start" when all are started or vise versa; it is probably possible but won't be particularly simple. Additionally, it's _technically_ allowed to run the command anyway, it just doesn't do anything.
As discussed in triage, we opted not to add it to files, as that menu is already pretty crowded and this won't help.
=> Add compose start/stop

src/commands/registries/azure/DockerWebhookCreateStep.ts, src/commands/registries/azure/tasks/runAzureTask.ts, src/tree/registries/azure/AzureRegistryTreeItem.ts, src/tree/registries/azure/AzureTaskRunTreeItem.ts, src/tree/registries/azure/AzureTaskTreeItem.ts, src/tree/registries/azure/AzureTasksTreeItem.ts, src/tree/registries/azure/SubscriptionTreeItem.ts, src/tree/registries/azure/createWizard/AzureRegistryNameStep.ts, src/tree/registries/azure/createWizard/AzureRegistrySkuStep.ts, src/tree/registries/azure/createWizard/IAzureRegistryWizardContext.ts
Part of #2606. After some testing with webpack I've determined there's really nothing more to do. As far as I can tell, the kind of codesplitting their docs describe applies more to older versions of webpack and/or ES and/or web-based things where network calls happen. The current approach we're using, with `await import(...)`, works as well as we need it to.
This PR will update some comments that were missed but doesn't do anything else.
We've reached a point of substantially diminishing returns on lazy loading, so at this point I'm willing to call it done. I'll keep an eye on Kensho to ensure nothing regresses.
=> Code "splitting"

src/docker/ContextLoadingClient/ContextLoadingClient.ts, src/docker/ContextManager.ts
Part of #3054, fixes a silly bug I left in #3109.
`ext.dockerContextManager` isn't being set until after is constructor, which was constructing the `ContextLoadingClient`, which in turn references `ext.dockerContextManager`. It was null-ref'ing as a result. Easiest to just pass in the context manager to `ContextLoadingClient`.
=> Fix silly bug in context loading client

package-lock.json, package.json
The latest 0.5.0 release of the Dockerfile language server introduces rudimentary support for heredoc syntax (https://github.com/moby/buildkit/pull/2132). `RUN` has some barebones support but `ADD` and `COPY` will require some further work.
Issues reported in this repository that have now been fixed:
- support heredoc syntax so we do not flag false positives when linting (#3087)
- semantic tokens fix for handling backslashes in strings (https://github.com/microsoft/vscode-docker/issues/3107#issuecomment-890417312)
Please use the Dockerfiles below for testing. Due to the nature of the parser bugs that have been fixed, please do not format the file and simply copy and paste the content into a Dockerfile editor.
Lastly, I have not forgotten about …
=> Upgrade to language server 0.5.0

src/docker/ContextManager.ts
Early results show that the API lookup is a clear winner. It is much faster on Windows, marginally faster on Mac, and a teeny bit slower on Linux but not enough to care (especially since, over time, Linux should be getting the daemon more broadly).
I expected the context load to be slower in cases where the API was not present--it adds the time to load that code and call the API. This does appear to be the case from the data, but is less prevalent than I expected--Mac is faster even up through the 90th percentile (as in, for at least 90% of users, this change helps) and Windows is faster up through the 95th percentile. Linux is a bit slower at the 90th percentile, but is just as fast at the 75th percentile.
This code removes the experimentation component and will always try the API lookup …
=> Remove experiment for context lookup

src/docker/ContextLoadingClient/ContextLoadingClient.ts, src/docker/ContextManager.ts
Fixes #3132. Pending calls through `ContextLoadingClient` will reject with the same error context loading failed with, if it fails.
=> Have `ContextLoadingClient` listen for any end-of-loading event

src/commands/registries/azure/DockerAssignAcrPullRoleStep.ts, src/commands/registries/azure/DockerSiteCreateStep.ts, src/commands/registries/azure/deployImageToAzure.ts
Fixes #3129.
This does three things:
1. Refactors the site config code to all be within `DockerSiteCreateStep`. It was difficult to follow, being split in two places. Ravi was right to put it in `DockerSiteCreateStep`, this just moves the rest.
1. For all Docker Hub deployments, it adds the `DOCKER_REGISTRY_SERVER_URL` value `https://index.docker.io`. This seems unnecessary but harmless on non-Arc deployments, but was necessary for Arc deployments.
1. Includes the `WEBSITES_PORT` on Docker Hub deployments to Arc. Previously it was prompting for that port but not actually applying the configuration.
=> Refactor app service deployment code

CHANGELOG.md, NOTICE.html, package-lock.json, package.json, src/debugging/node/NodeDebugHelper.ts
Fixes #3177. This is roughly a cherry-pick of #3179.
=> Change to `pwa-node` for Node debug (cherry-pick #3179)

package-lock.json, package.json
The new 0.6.0 release of the language server adds support for heredocs in `ADD` and `COPY` as well as allowing multiple heredocs to be defined in a single instruction. There is also a small change to flag relevant linting issues as being "unnecessary". I'm not sure how VS Code renders this and if it takes the theme into consideration at all.
```Dockerfile
#escape=`
#escape=`
FROM node:alpine
CMD [ "executable" ]
CMD [ "executable" ]
ENTRYPOINT [ "executable" ]
ENTRYPOINT [ "executable" ]
HEALTHCHECK --interval=30s --timeout=30s --start-period=5s --retries=3 CMD [ "executable" ]
HEALTHCHECK --interval=30s --timeout=30s --start-period=5s --retries=3 CMD [ "executable" ]
RUN <<FILE1 cat > file1 && <<FILE2 cat > file2
first heredoc
FILE1
second heredoc
FILE2
ADD <<EOF /test.txt
echo "Hello …
```
=> Upgrade to language server 0.6.0

CHANGELOG.md, package.json
Since it doesn't do very much, we're going to turn the language server off by default for this release.
=> Set the language server to off-by-default for this release

package.json, package.nls.json, src/commands/containers/stats.ts, src/commands/registerCommands.ts, webpack.config.js
Fixes #3063.
Unrelatedly, it fixes some warnings in webpack.config.js itself, along with some warnings produced by webpack about `ssh2` that was causing VSCode to think webpack did not finish--and it wouldn't <kbd>F5</kbd> the extension.
=> Add a simple `docker stats` palette command

package-lock.json, package.json
The 0.7.1 release of the Dockerfile language server has the following improvements:
- updates linter to consider syntax valid in BuildKit
- improve robustness of the parser to not get in invalid loops (inadvertently discovered by https://github.com/microsoft/vscode-docker/issues/3189#issuecomment-913979668)
- ignore valid instructions but to instead only flag the incorrect duplicates
Please use the following Dockerfiles for testing purposes. As always, please just copy/paste the content in to a `Dockerfile` without saving to preserve the formatting (to reproduce the incorrect parsing behaviour).
```Dockerfile
#escape=`
#escape=`
FROM node:alpine
CMD [ "executable" ]
ENTRYPOINT [ "executable" ]
HEALTHCHECK --interval=30s --timeout=30s --start-period=5s --retries=3 CMD [ "executable" ]
CMD …
```
=> Upgrade Dockerfile language server to 0.7.1

src/tree/registries/gitLab/GitLabAccountTreeItem.ts, src/tree/registries/gitLab/gitLabRegistryProvider.ts
Fixes #3199 (the unhelpful error message, that is--we still require an `api` or `read_api` token, I updated the prompt text to indicate that)
=> Fix unhelpful error from GitLab registry provider

package-lock.json, package.json
`vscode-nls-dev` is a tool for extracting strings, but we're not currently using it in any capacity. It has several dependency vulnerabilities so removing it is the easiest way to get back to 0.
=> Remove unused dev package with vulnerable dependencies

.gitattributes
Learned about this from https://github.com/microsoft/vscode-azurestaticwebapps/pull/576. Marking this file as generated means it will no longer appear as part of the repo's language, here:
I chose specifically to use `linguist-vendored` instead of `linguist-generated`, because I still want this file to appear in PRs by default when it is altered.
=> Mark some files as generated

src/commands/containers/removeContainer.ts, src/commands/containers/stopContainer.ts, src/commands/images/pushImage.ts, src/commands/images/removeImage.ts, src/commands/networks/removeNetwork.ts, src/commands/registries/azure/DockerAssignAcrPullRoleStep.ts, src/commands/registries/azure/DockerSiteCreateStep.ts, src/commands/registries/azure/DockerWebhookCreateStep.ts, src/commands/registries/azure/deployImageToAzure.ts, src/commands/registries/azure/tasks/runAzureTask.ts, src/commands/registries/azure/tasks/scheduleRunRequest.ts, src/commands/volumes/removeVolume.ts, src/docker/DockerodeApiClient/DockerodeApiClient.ts, src/docker/DockerodeApiClient/DockerodeUtils.ts, src/dockerfileCompletionItemProvider.ts, src/test/commands/selectCommandTemplate.test.ts, src/tree/registries/azure/AzureRegistryTreeItem.ts, src/tree/registries/azure/AzureTaskRunTreeItem.ts, src/tree/registries/azure/AzureTaskTreeItem.ts, src/tree/registries/azure/AzureTasksTreeItem.ts, src/tree/registries/azure/SubscriptionTreeItem.ts, src/tree/registries/azure/createWizard/AzureRegistryNameStep.ts, src/tree/registries/azure/createWizard/AzureRegistrySkuStep.ts, src/tree/registries/azure/createWizard/IAzureRegistryWizardContext.ts, src/utils/getHandlebarsWithHelpers.ts, src/utils/quickPickFile.ts, src/utils/suggestSupportHelper.ts
Fixes #3319. Using `import type` will prevent these dev-time imports from accidentally becoming runtime imports. Also turns some `require`s into `import`s.
=> Convert dev imports to true dev imports only

package.json, package.nls.json, src/commands/images/showDanglingImages.ts, src/commands/registerCommands.ts, src/tree/images/ImagesTreeItem.ts
Fixes #3270. I intentionally did _not_ include #3290 due to [this](https://github.com/microsoft/vscode-docker/issues/3290#issuecomment-981920116).
The icons (and their tooltips) look like this:
=> Change show/hide dangling to a proper toggle

src/commands/containers/attachShellContainer.ts, src/commands/containers/viewContainerLogs.ts
Fixes #3340, standardizing on "Action: container_name". Also makes both localizable; they weren't before.
Here's how it looks now:
=> Match shell terminal name and make localizable

resources/python/launcher.py, src/commands/registries/logInToDockerCli.ts, src/debugging/netcore/NetCoreDebugHelper.ts, src/debugging/python/PythonDebugHelper.ts, src/docker/Contexts.ts, src/docker/DockerodeApiClient/DockerodeApiClient.ts, src/tasks/DockerBuildTaskProvider.ts, src/tasks/DockerRunTaskProvider.ts
Fixes #3281. Scenarios I've tested:
=> Use `dockerExePath()` for tasks and some others

src/docker/files/ContainerFilesUtils.ts
Fixes #3282. The diff that Git produces is pretty ugly, so it may be easier to just look at the rewritten `statWindowsContainerItem()` function as a whole: https://github.com/microsoft/vscode-docker/blob/29aa5d45f25834ac180bb7a5d9eafe897e1155f0/src/docker/files/ContainerFilesUtils.ts#L224-L266
---
The PowerShell stat script is pretty complex and worth breaking down.
```powershell
$finfo = Get-Item -Path '${itemPath}'; Write-Output ('{0};{1};{2};{3}' -f ([System.DateTimeOffset]$finfo.CreationTimeUtc).ToUnixTimeMilliseconds(), ([System.DateTimeOffset]$finfo.LastWriteTimeUtc).ToUnixTimeMilliseconds(), $finfo.Length, @('file','directory')[$finfo.PSIsContainer])
```
Gets and stores the FS info in a variable, `$finfo`:
```powershell
$finfo = Get-Item -Path '${itemPath}'; 
```
Outputs the data …
=> Use PowerShell instead of WMI in Windows container file stat

package.json, package.nls.json, src/tasks/DockerRunTaskDefinitionBase.ts, src/tasks/DockerRunTaskProvider.ts, src/tasks/netcore/NetCoreTaskHelper.ts, src/tasks/python/PythonTaskHelper.ts
The volumes mounted by the plugin are not accessible in the container on SELinux systems like Fedora and RHEL.
They need to be relabeled.
For more info see the _Labeling Volume Mounts_ section in https://docs.podman.io/en/latest/markdown/podman-run.1.html.
@bwateratmsft ptal.
=> Make volumes accessible on SELinux systems by adding relabel option.

package-lock.json, package.json
This update to the Dockerfile language server fixes three issues that have been raised by the community:
- the formatter will now ignore heredocs (https://github.com/microsoft/vscode-docker/issues/3327)
- the server will no longer enter an infinite loop when using Intellisense in `ADD` or `COPY` instructions (https://github.com/microsoft/vscode-docker/issues/3347)
- errors will no longer be thrown when using Intellisense after a `--chown` or `--from` flag in `ADD` or `COPY` instructions (https://github.com/microsoft/vscode-docker/issues/3349)
```Dockerfile
FROM alpine as alpine
COPY . . 
```
```Dockerfile
FROM node:alpine
ADD --chown=user:group
COPY --chown=user:group
RUN <<EOT
cat
EOT
```
=> Upgrade Dockerfile language server to 0.7.3

package-lock.json, package.json
This new release improves the semantic highlighting support for variables in addition to correcting a false positive linting error about empty continuation lines on here-documents. Please test these two new changes with the Dockerfile below.
```Dockerfile
FROM node:alpine
RUN echo ${variable:+word}
RUN echo ${variable:-word}
RUN <<EOT
abc
def
EOT
```
Screenshot taken with the "Tomorrow Night Blue" theme:
=> Upgrade Dockerfile language server to 0.8.0

src/commands/images/buildImage.ts, src/commands/registries/azure/tasks/scheduleRunRequest.ts, src/tree/containers/ContainersTreeItem.ts
Fixes #3396. Here's the new look:
Once @ucheNkadiCode approves I'll submit.
This PR also contains some minor unrelated changes to use workspace memento instead of global memento.
=> Adjust "Getting started with Docker" link text

package-lock.json, package.json, src/tasks/DockerBuildTaskProvider.ts, src/tasks/TaskHelper.ts, src/utils/pathNormalize.ts
Fixes #3400. Additionally, this includes an `npm audit fix` and `npm update` to clear some more alerts.
There's a few changes encompassed in this.
- I tried to make the task's required properties equivalent to the CLI's required properties--namely, context for `docker build` needed to be the only required parameter. Tag and Dockerfile should be optional.
- Required properties should show up in `tasks.json` now.
- I changed the logic for official build task resolution to consider default arguments better.
=> Infer more default args, show as required correctly

src/commands/containers/browseContainer.ts, src/scaffolding/wizard/ChoosePortsStep.ts, src/scaffolding/wizard/ScaffoldingWizardContext.ts, src/scaffolding/wizard/netCore/NetCoreScaffoldingWizardContext.ts, src/scaffolding/wizard/netCore/NetCoreTryGetRandomPortStep.ts, src/utils/pythonUtils.ts
Fixes #3381.
TODO:
- ~~Django, FastAPI? Use 8000~~
- ~~Node? Uses 3000~~
=> Try to get port from launch settings

src/telemetry/ActivityMeasurementService.ts, src/test/telemetry/ActivityMeasurementService.test.ts
In VSCode 1.64, `vscode.env.isTelemetryEnabled` is now `false` in test sessions and extension debug sessions. For our unit tests, we do not need to enforce telemetry being enabled.
=> Fix unit tests failing in new VSCode version

src/docker/files/ContainerFilesUtils.ts
In case that Windows container is created with different localization function `parseWindowsDirectoryItems` won't return any folder.
Tested on container created using German localization.
=> Include different delimiter for Date

src/scaffolding/wizard/python/ChoosePythonArtifactStep.ts, src/scaffolding/wizard/python/PythonGatherInformationStep.ts
Fixes #3410. Two things in this:
- For Django apps only, when asking for input on the primary artifact we will no longer suggest WSGI/ASGI files.
- When searching for the WSGI file for Django apps, now look in any immediate subfolder from the primary artifact, rather than one of the exact name of the workspace folder.
=> Improve Django scaffolding experience

src/utils/resolveVariables.ts
I saw in the 1.65 release notes that a new [`${userHome}` task variable has been added](https://code.visualstudio.com/updates/v1_65#_tasks). It seems likely this could get used so I'm adding support for it in our variable resolver.
=> Support `${userHome}` task variable

src/commands/registries/copyRemoteFullTag.ts
Should have done this with #3487 but forgot. Fixes #3491.
=> Allow copying tags from Docker Hub

resources/templates/.dockerignore.template
Be more compatible with `.dockerignore` created by Visual Studio 2022
=> Add LICENSE to `.dockerignore`

src/commands/images/tagImage.ts
Request from @ucheNkadiCode. In our telemetry for image tagging this adds support for GitHub Container Registry, so it doesn't all go into the "Other" category.
Related to #3506. Fixes #3510.
=> Detect GHCR images in tagging telemetry

src/scaffolding/wizard/netCore/NetCoreGatherInformationStep.ts
~~With the release of Ubuntu 22.04, the new Ubuntu tag for images is `-jammy` instead of `-focal`. There is no `7.0-focal` at all, only `7.0-jammy`. There is both for 6.0, so we do not need to service a fix.~~
Undoes #2996, #3029. The .NET attach scenario no longer relies on `ps` so we don't need to use Ubuntu-based images by default.
Fixes #3512.
=> Switch back to default .NET images (undo #2996, #3029)

src/debugging/python/PythonDebugHelper.ts, src/docker/Common.ts
Fixes #3514. On Docker Desktop for Linux, they use the same VM setup as on Mac and Windows, so it is necessary to use `localhost` as the `debugAdapterHost`.
=> Use `debugAdapterHost: localhost` on Docker Desktop for Linux

src/debugging/netcore/VsDbgHelper.ts, src/tree/containers/ContainerTreeItem.ts, src/tree/volumes/VolumeTreeItem.ts
Along with an upcoming new release of the VSDBG scripts, this will fix #3527.
Also includes unrelated addition of some interfaces to explicitly codify some things used by the Remote - Containers extension, so that if the property was accidentally removed, TypeScript would complain (because the class would no longer implement the interface).
=> Use `-u` flag with `GetVsDbg.sh`

package-lock.json
Fixes CVE-2022-25878 and associated CG alert
=> Update `protobufjs` to 6.11.3

src/runtimes/docker/clients/DockerClientBase/DockerClientBase.ts, src/runtimes/docker/contracts/ContainerClient.ts, src/tree/RefreshManager.ts
=> Restart the event listener every 5 minutes

src/commands/registries/azure/tasks/buildImageInAzure.ts, src/commands/registries/azure/tasks/scheduleRunRequest.ts, src/utils/sleep.ts
This PR adds a return to the `buildImageInAzure` command. We want to use this command in the [Azure/aks-devx-tools](https://github.com/Azure/aks-devx-tools) extension and need run information returned to do this. Anything returned by the `buildImageInAzure` command can be retrieved by a calling extension with the `vscode.commands.executeCommand` function. 
For more background on why we need run information returned, we specifically need whether or not the command succeeded and the full image path that was built. Our goal is to easily let users go from source code to an AKS deployment with `Generate Dockerfile` -> `Build Dockerfile` -> `Generate K8s Manifests` -> `Run on AKS`. Instead of rebuilding the `Build Dockerfile` step we thought it would make sense to consume this extension. We …
=> Add return to Build ACR Command

src/tree/images/imageChecker/OutdatedImageChecker.ts
Fixes #3696. I noticed that when using `Accept: application/vnd.docker.distribution.manifest.v2+json`, the expected result was returned for the MSSQL images, but not for the dotnet images. In contrast, when using `application/vnd.docker.distribution.manifest.list.v2+json` (which is what the current code does), it worked for dotnet but not MSSQL. When trying _both_, as suggested [here](https://docs.docker.com/registry/spec/manifest-v2-2/#backward-compatibility), everything worked for both types (and for Docker Hub too).
=> Add another `Accept` header to image out-of-date check

src/runtimes/docker/utils/spawnStreamAsync.ts, src/utils/netCoreUtils.ts
Fixes https://github.com/microsoft/vscode-docker/issues/3709 by:
- increasing the timeout to 20 seconds (the previous 10 seconds might be a bit short in a case of a freshly-started machine with low RAM and slow disk)
- improving error handling in case a process is terminated due to a signal
=> Fix issue 3709

src/runtimes/docker/clients/DockerClientBase/DockerClientBase.ts, src/runtimes/docker/test/DockerClient.test.ts
This applies the custom date parsing string for all list commands (image, network, etc.) to ensure we properly handle the specific custom date format docker returns for those commands (vs. inspect).
Fixes #3718.
=> Apply the custom date parsing string to all list commands

src/debugging/netcore/NetCoreDebugHelper.ts, src/runtimes/docker/clients/DockerClientBase/DockerClientBase.ts, src/runtimes/docker/clients/DockerComposeClient/DockerComposeClient.ts, src/runtimes/docker/test/DockerClient.test.ts, src/runtimes/docker/test/DockerComposeClient.test.ts, src/runtimes/docker/utils/commandLineBuilder.ts, src/runtimes/docker/utils/spawnStreamAsync.ts, src/runtimes/runners/TaskCommandRunnerFactory.ts
Fixes the `customOptions` and `command` issues reported in #3722. Creating as draft until the upstream changes are done.
=> Don't escape `customOptions` or single-string `command` options

src/debugging/netcore/NetCoreDebugHelper.ts, src/runtimes/docker/clients/DockerClientBase/DockerClientBase.ts, src/runtimes/docker/clients/DockerClientBase/withDockerFilterArg.ts, src/runtimes/docker/clients/DockerClientBase/withDockerJsonFormatArg.ts, src/runtimes/docker/clients/DockerClientBase/withDockerLabelFilterArgs.ts, src/runtimes/docker/utils/spawnStreamAsync.ts, src/tree/containers/ContainerTreeItem.ts
Fixes #3758. Creating as draft since the upstream PR isn't merged yet.
Things to test:
=> Fix some "shell" quoting bugs

src/tasks/DockerBuildTaskProvider.ts, src/tasks/DockerComposeTaskProvider.ts, src/tasks/DockerPseudoterminal.ts, src/tasks/DockerRunTaskProvider.ts, src/utils/execAsync.ts
=> Don't reject on stderr for `docker run`

resources/templates/python/Dockerfile.template
resolves #3736 by changing the image from python 3.8-slim to 3.10-slim
=> Bumps default python version to Python 3.10

src/debugging/DockerDebugConfigurationProvider.ts, src/tasks/DockerRunTaskProvider.ts, src/tasks/TaskHelper.ts
Fixes #3641, fixes #2327
Tests:
=> Scope task config lookup to workspace folder

src/runtimes/clients/AutoConfigurableDockerClient.ts, src/utils/diagnostics.ts, src/utils/execAsync.ts
Ran into some issues testing the new execAsync diagnostic logging on Linux, so backing those specific changes out for now.
=> Remove the extra diagnostic logging from execAsync

src/commands/registries/azure/deployImageToAca.ts, src/tree/registries/dockerHub/DockerHubNamespaceTreeItem.ts
See title.
Also reverted the Docker Hub registry path addition from my previous PR since we don't need it with this method
=> Change ACA contract to support `registryName` instead of `loginServer`

resources/templates/netCore/Dockerfile.template, src/scaffolding/wizard/netCore/NetCoreGatherInformationStep.ts, src/scaffolding/wizard/netCore/NetCoreScaffoldingWizardContext.ts, src/tasks/netcore/NetCoreTaskHelper.ts
This PR addresses issue #3834 . 
This PR supports the change in naming convention for .NET 8 Docker tags & the change in `adduser` command for Debian 12.
=> Changes to Scaffolding for .NET 8 Preview #3834

.vscode/settings.json
This one-line change in `settings.json` allows VSCode to automatically organize imports when you save a `.ts` file in the repository. 
This change came to me while completing this [API change](https://github.com/microsoft/vscode-docker/pull/3846), which required changes to import statements in over 100 files. Instead of running the command `TypeScript: Organize imports` every time I add a new import to a file, I can just save the file and have VSCode do its magic. I think this will ensure imports are organized every time someone edits a file, creates a file without having to remember to run the command.
=> Organize imports on save 

src/tasks/DockerPseudoterminal.ts
This fixes #3691 as far as we can reasonably go without dumping `Pseudoterminal` / `CustomExecution`.
=> Slightly improve terminal output

src/commands/registries/azure/tasks/scheduleRunRequest.ts
Fixes #3616.
This will do something more closely resembling actual streaming--rather than downloading the entire log file to a buffer every 1 second--and also breaks apart the lines to log them individually (so VSCode's attached timestamps appear on every line)~~, and also removes the redundant timestamps from the source log (which is less accurate but looks so much better)~~.
IMO the PR is easier to read with [whitespace off](https://github.com/microsoft/vscode-docker/pull/3858/files?w=1).
=> Actually stream logs and clean up format

package.json, package.nls.json, src/runtimes/docker/clients/DockerClientBase/DockerClientBase.ts, src/runtimes/docker/contracts/ContainerClient.ts, src/tasks/DockerBuildTaskDefinitionBase.ts, src/tasks/DockerBuildTaskProvider.ts, src/tasks/netcore/NetCoreTaskHelper.ts
=> Add support for `--platform` flag in `docker-build` task

src/scaffolding/wizard/netCore/NetCoreGatherInformationStep.ts
This PR addresses issue #3889 by changing the scaffolding for Docker Windows .NET 8 base image by changing tag from ltsc2022 to 1809 to be compatible with Windows 10 machines
=> Changed .NET8 Windows Image tag to be compatible with Windows 10 & 11

package.json, package.nls.json, src/extension.ts, src/extensionVariables.ts, src/utils/registerDockerContextStatusBarItems.ts
This PR closes issue #3690 by adding an option to display the current Docker context in VSCode's status bar.
=> Add Docker Context to Status Bar

resources/templates/netCore/Dockerfile.template, resources/templates/netCore/docker-compose.debug.yml.template
Closes #3912 
Configuration is set to `Release` by default, but is overwritten to `Debug` when debugging
Tested:
=> Fixed .NET Debugging with Docker Compose 

package.json
Previously we rely on the inferred activation event for `dockerfile`, but https://github.com/microsoft/vscode/pull/179287 breaks this behavior for us.
This PR adds back the `onLanguage:dockerfile` activation event in package.json.
Fixes https://github.com/microsoft/vscode-docker/issues/3899
=> Add back `onLanguage:dockerfile` activation event

package-lock.json, package.json, src/commands/registries/azure/DockerAssignAcrPullRoleStep.ts, src/utils/lazyPackages.ts
https://github.com/Azure/azure-sdk-for-js/issues/21210 has been fixed. Version 9.0.0 of `@azure/arm-authorization` has been released and has the fix we needed. Reverts part of #3910. Tested appsvc deploy and it works as expected.
=> Revert back to normal ARM auth package

package-lock.json, package.json
First of all, apologies to everyone for having just disappeared into thin air and also thank you to everyone for your continued bug reports (even if I did not respond to them until now...) as it helps me identify things to fix to make everyone's Dockerfile editing experience a little better. I can't promise any turnaround times but I hope to be more responsive than I have been in the last year or so after seemingly dropping off the face of the earth. :P
---
This update adds heredoc support for `COPY` so that it does not try to format it or lint it for Dockerfile-specific errors. The update also includes a fix caused by quotes in comments that can cause the semantic highlighter to get into an infinite loop.
This should fix the following issues:
- #3576
- #3836
- #3950
This does *not* fix …
=> Update Dockerfile language server to 0.10.1

CHANGELOG.md, package-lock.json, package.json, src/tree/resolveTooltipMarkdown.ts
=> Bump version, changelog for 1.25.2 and cherry pick #3983

package.json, src/debugging/netSdk/NetSdkDebugHelper.ts, src/scaffolding/wizard/net/NetContainerBuild.ts, src/scaffolding/wizard/net/NetSdkChooseBuildStep.ts
This change allows our debugger to be discoverable when users `f5` on more .NET files. (.vb, fsharp). 
(It also includes a name change of `NetContainerBuildOptions` to `NetContainerBuildOption` since it should be singular)
=> Added Discoveribility .NET SDK Build feature 

package.json, src/commands/images/buildImage.ts, src/commands/images/tagImage.ts, src/commands/registerCommands.ts, src/commands/registries/azure/deleteAzureRegistry.ts, src/commands/registries/azure/deleteAzureRepository.ts, src/commands/registries/azure/openInAzurePortal.ts, src/commands/registries/azure/tasks/buildImageInAzure.ts, src/commands/registries/azure/tasks/scheduleRunRequest.ts, src/commands/registries/copyRemoteFullTag.ts, src/commands/registries/pullImages.ts, src/tree/registries/Azure/AzureRegistryDataProvider.ts, src/tree/registries/getInformationFromRegistryItem.ts, src/tree/registries/registryTreeUtils.ts
This PR addresses the following commands
=> Made Some ACR Commands Work

package-lock.json, package.json, src/commands/images/pushImage.ts, src/commands/images/tagImage.ts, src/commands/registerCommands.ts, src/commands/registries/copyRemoteImageDigest.ts, src/commands/registries/deleteRemoteImage.ts, src/tree/registries/Azure/AzureRegistryDataProvider.ts, src/tree/registries/registryTreeUtils.ts, src/utils/registryExperience.ts
This PR completes command 
This PR also address a few things that I broke in my previous changes
- A bug with push image that I broke from refactoring the registries util functions
This PR also improves experience for `registryExperience()` 
I also realized I mixed up "Untag Azure Image" with "Delete Azure Image", so I'm going to work on "Untag Azure Image" as delete is already done.
=> Implemented Delete Remote Image for GenericV2 

package-lock.json, package.json, src/commands/registries/azure/untagAzureImage.ts, src/commands/registries/deleteRemoteImage.ts, src/tree/registries/Azure/AzureRegistryDataProvider.ts
Related to https://github.com/microsoft/vscode-docker/pull/4026
=> Added Untag Image Command for Azure RDP

package.json
Update package.json with a 'filenamePatterns' of "*.dockerignore" since that is the convention to use when using multiple .dockerignore files when having multiple Dockerfiles.
Fixes #4059
=> Support multiple .dockerignore files for language id discovery

src/commands/images/pushImage.ts, src/commands/images/tagImage.ts, src/commands/registries/azure/DockerAssignAcrPullRoleStep.ts, src/tree/registries/UnifiedRegistryTreeDataProvider.ts, src/tree/registries/registryTreeUtils.ts
This PR addresses this comment https://github.com/microsoft/vscode-docker/pull/4026#discussion_r1317749608
It fixes 2 tiny bugs
1. push a local image to a Github Registry: previously `ghcr.io/testapp:dev` when it should be `ghcr.io/alexyaang/testapp:dev` when tagging
2. copy the full tag command: previously `ghcr.io/alexyaang/alexyaang/testapp:dev` when it should be `ghcr.io/alexyaang/testapp:dev`
Tested:
=> Fixes pushImage() 

src/tree/registries/Azure/AzureRegistryDataProvider.ts
Related to https://github.com/microsoft/vscode-docker/pull/4026
=> Added fire soon function to AzureRDP

package-lock.json, package.json, src/commands/images/pushImage.ts, src/commands/registries/azure/createAzureRegistry.ts, src/commands/registries/azure/deleteAzureRegistry.ts, src/commands/registries/azure/deleteAzureRepository.ts, src/commands/registries/azure/deployImageToAca.ts, src/commands/registries/azure/deployImageToAzure.ts, src/commands/registries/azure/openInAzurePortal.ts, src/commands/registries/azure/tasks/scheduleRunRequest.ts, src/commands/registries/azure/untagAzureImage.ts, src/commands/registries/azure/viewAzureProperties.ts, src/commands/registries/copyRemoteFullTag.ts, src/commands/registries/copyRemoteImageDigest.ts, src/commands/registries/deleteRemoteImage.ts, src/commands/registries/disconnectRegistry.ts, src/commands/registries/dockerHub/openDockerHubInBrowser.ts, src/commands/registries/genericV2/removeTrackedGenericV2Registry.ts, src/commands/registries/logInToDockerCli.ts, src/commands/registries/logOutOfDockerCli.ts, src/commands/registries/pullImages.ts, src/commands/registries/reconnectRegistry.ts, src/tree/registries/Azure/AzureRegistryDataProvider.ts, src/tree/registries/UnifiedRegistryTreeDataProvider.ts, src/utils/registryExperience.ts
=> Improve Registry Experience & Simplify Context Values

package-lock.json, package.json
This update adds support for a few new flags that have been added to Dockerfile so that they no longer get flagged as errors. The other big change is the introduction of a comment that can be inserted into the Dockerfile to instruct the linter to not flag something as an error. While most errors can be ignored this way, clearly fatal errors that suggest the Dockerfile is completely broken cannot be ignored.
This release fixes the following issues. As always, thank you all for your bug reports and suggestions!
- #4012
- #4051
- #4054
- #4056
Please use the following Dockerfile to test the new features and bug fixes.
```Dockerfile
FROM scratch
HEALTHCHECK --start-
HEALTHCHECK --start-interval=5s CMD ls
UNKNOWN instruction
HEALTHCHECK \
--interval=30s \
--retries=3 \
--start-interval-typo=5s …
```
=> Update Dockerfile language server to 0.11.0

src/tree/registries/Azure/AzureRegistryDataProvider.ts, src/tree/registries/UnifiedRegistryTreeDataProvider.ts
This is incomplete. Still need to stop using `.map` in `getTags` in AzureRegistryDataProvider
=> Asynchronously fetch createdAt info

src/tasks/netSdk/netSdkTaskUtils.ts
With .NET 8 SDK RC1, images that are built has existing expose ports logic so we no longer need to export 8080 and 80 manually. 
This also closes https://github.com/microsoft/vscode-docker/issues/4006 since the old behavior in `browseContainer()` would just choose `80` by default and open a port that is not published for .NET 8. However, with the new SDK exposing ports change and us not exposing ports manually, the only available port is the port auto exposed by the .NET SDK (8080), therefore, fixing the problem.
=> No Longer Expose Ports Manually During Sdk Build & Launch

src/commands/images/tagImage.ts
This PR fixes the tag image command. A lot of the times, registry is undefined, so `registry.wrappedItem` will throw an error.
=> added chaining operator to registry

src/tree/registries/UnifiedRegistryTreeDataProvider.ts
Closes https://github.com/microsoft/vscode-docker/issues/4094
=> Show Connect Registry Command when No Registries are Connected

package-lock.json, package.json, src/commands/registries/genericV2/addTrackedGenericV2Registry.ts, src/commands/registries/genericV2/removeTrackedGenericV2Registry.ts, src/tree/registries/ConnectRegistryTreeItem.ts, src/tree/registries/UnifiedRegistryTreeDataProvider.ts, src/utils/registryExperience.ts
Closes https://github.com/microsoft/vscode-docker/issues/4098
Closes https://github.com/microsoft/vscode-docker/issues/4097
Closes https://github.com/microsoft/vscode-docker/issues/4099
Also closes these as we have updated the registries package
Closes https://github.com/microsoft/vscode-docker/issues/4094
Closes https://github.com/microsoft/vscode-docker/issues/4092
TODO:
=> Throw Better Error when running registries commands when No Registries are Connected

CHANGELOG.md, package-lock.json, package.json
I will generate NOTICE.html in the next PR.
=> Prep for v1.27.0 Release

package-lock.json, package.json, package.nls.json, src/commands/registerCommands.ts, src/commands/registries/inspectRemoteImageManifest.ts
=> Add a way to view image manifest

CHANGELOG.md, package-lock.json, package.json
NOTICE file generation is still busted.
=> Update version, changelog for 1.28.0

src/tree/registries/Azure/AzureRegistryDataProvider.ts
The Azure Account extension is no longer used by the Docker extension and the `updateSubscriptionsAndTenants` event it had is relied upon to generate Azure-subscription-related telemetry. We need to mimic the old event so that Kusto queries can be minimally changed.
=> Add telemetry for capturing Azure subscription information

resources/netCore/GetProjectProperties.targets
Fixes #4199
Closes #3988 since the debugging Just Works (TM) with .NET 8 console projects as long as the `EnableSdkContainerSupport` property is manually set to `true` (e.g. in the .csproj file)
/cc @baronfel does this look about right?
=> Update targets to work correctly with 8.0.100-rc2 and up

resources/python/launcher.py, resources/templates/python/Dockerfile.template, resources/templates/python/requirements.txt.template, src/debugging/python/PythonDebugHelper.ts, src/tasks/python/PythonTaskHelper.ts
=> Go back to using `python` instead of `python3` and bump Python dependency versions

resources/python/launcher.py, src/debugging/python/PythonDebugHelper.ts, src/tasks/python/PythonTaskHelper.ts
This partially reverts commit 7b57512a3f57419880c401fceef4cf35e71038ab.
We'll go back to `python3` as that works on Mac and Linux. The `python3` command opening the Windows store page seems to be new and may have caused this regression in Insiders. Still not clear why only Insiders is affected.
=> Partially revert "Go back to using `python` instead of `python3`

CHANGELOG.md
https://github.com/microsoft/vscode-docker/pull/4228 reverted the change from `python` to `python3`, need to update the changelog too.
=> Fix changelog inaccuracy

resources/templates/python/Dockerfile.template
Uses a floatier tag for scaffolding Python apps. So we don't have to update this every year when a new Python release comes out.
=> Scaffold Python Dockerfile with a floatier tag

src/tasks/netcore/NetCoreTaskHelper.ts
Currently the extension employs this simple regex /UserSecretsId/i to detect if .NET project file uses values stored in Secret Manager. If this string is found in the project file, than the "docker-run" task generates a command that attempts to mount the secrets folder onto the container. If this folder does not exist than the command fails.
Problem is that this regex doesn't consider that the tag may be commented out.
I propose removing all commented sections from the .csproj contents before testing UserSecretsId regex against it.
=> Ignore commented <UserSecretsId> tag in .csproj

src/debugging/python/PythonDebugHelper.ts, src/tasks/python/PythonExtensionHelper.ts
Closes #4221 
Because the core Python extension is going to keep its API, just returning a `ms-python.debugpy` path, we do not need to update anything in the extension helper. The only change needed is to update the debug type that we resolve.
=> Support debugging Python using the new Python Debugger extension

src/debugging/netcore/NetCoreDebugHelper.ts, src/utils/osUtils.ts
If my hunch is right this should fix #4312
/cc @dbreshears @danegsta
=> Fetch arm64 debugger anytime on any arm64 OS

package-lock.json, package.json
This update includes a small linting fix as well as highlighting support for heredocs. You can use the file below to test the changes.
1. The `:-` syntax provides a default so we should not be flagging the `FROM` as an error (see https://github.com/rcjsuen/dockerfile-language-server/issues/269).
2. The language server now provides proper support for the start and end of a heredoc by highlighting the two ends and allowing you to jump from the end of the document to the original definition at the top.
```Dockerfile
FROM ${VAR:-alpine}
RUN echo <<file
abc
file
```
=> Update the language server to 0.13.0

.azure-pipelines/1esmain.yml, .azure-pipelines/SignExtension.signproj
Preparing for these changes: https://github.com/microsoft/vscode-azuretools/pull/1775
=> Sign extension with MS Build

.azure-pipelines/release.yml
To make a release, you'll manually run the pipeline and need to fill out the parameters:
A version string is required at pipeline run time that will be matched against the version present in the package.json downloaded from the build pipeline artifacts. The "Dry Run" parameter will skip the last step that actually publishes the extension.
Under Resources you can change target build pipeline. It defaults to the latest successful build.
Releases will need to be approved by one member of the deployment environment. View the environment I created: https://dev.azure.com/devdiv/DevDiv/_environments/1258?view=checks. For now I've left the "allow self approval" setting enabled.
=> Add release pipeline

src/utils/httpRequest.ts
Fixes #4378 
This PR is much clearer if viewed without whitespace: https://github.com/microsoft/vscode-docker/pull/4383/files?w=1
=> Log more in vsdbg script download error case

src/commands/images/buildImage.ts, src/commands/selectCommandTemplate.ts
If a task command template has the default value, this attempts to parse it and convert into a ShellQuotedString format so that VSCode will perform appropriate argument escaping for the selected shell. The current logic will only run if a task is configured with the default value as the current parsing logic assumes certain conditions that may not be true for a user customized value.
This should resolve #4291.
=> Convert default command template values into ShellQuotedString format

src/tasks/netSdk/NetSdkRunTaskProvider.ts, src/tasks/netSdk/netSdkTaskUtils.ts
In https://github.com/dotnet/sdk/pull/47064, console apps will get `EnableSdkContainerSupport` set to true by default. Consequently, we no longer need to have different image build command lines for console vs. web apps. This true for .NET 8 and 9 as well, so we can remove the code to use `-p:PublishProfile=DefaultContainer` altogether. It was only needed for .NET 7 which is out of support.
/cc @baronfel @patverb @danegsta
=> Support new .NET SDK image build changes

package-lock.json, package.json
This update includes some general fixes as well as one to prevent the language server crashing (#4408). It also includes an update to how we handle links so that we no longer just blindly route everything to Docker Hub.
Please use the Dockerfile below to reproduce the crash and verify the fix.
```Dockerfile
FROM scratch
RUN <<<CRASH
CRASH
FROM scratch
```
Please use the Dockerfile below to test the other fixes and the update to the URL links.
```Dockerfile
FROM alpine
FROM hello AS alpine
FROM busybox AS base
FROM base
FROM busybox
COPY --from=base . .
FROM busybox
FROM ghcr.io/super-linter/super-linter
FROM ghcr.io/super-linter/super-linter:latest-buildcache
FROM mcr.microsoft.com/powershell
FROM mcr.microsoft.com/powershell:3.17
FROM mcr.microsoft.com/windows/servercore
FROM …
```
=> Update the Dockerfile Language Server to 0.14.0

package.json
There are other extensions called "Docker Extension Pack" and VSCE won't let us upload. Rolling back the name for now, we'll try to fix it later.
=> Roll back the display name
