- configureWorkspace/configure.ts
- dockerfile/dockerfileKeyInfo.ts
- package.json
- snippets/dockerfile.json
removed MAINTAINER and updated dockerfile_lint version
> remove maintainer as its deprecated

- README.md
- commands/start-container.ts
i should have bunched up other fixes into a single pull request. this fix got a little bigger so would appreciate a review, thx.
> check to ensure running linux containers on windows

- CHANGELOG.md
- package.json
Bumps the version and updates the changelog.
> Prep for publishing 0.0.15

- commands/build-image.ts
- commands/docker-compose.ts
- configureWorkspace/configure.ts
> Adopt new multi root APIs

- CHANGELOG.md
Signed-off-by: Remy Suen <remy.suen@gmail.com>
> Fix a small typo

- configureWorkspace/configure.ts
> update to use LTS 8.9 of node.js

- explorer/models/rootNode.ts
As per this issue https://github.com/Microsoft/vscode-docker/issues/169
> Only show images that are not dangling

- package-lock.json
- package.json
You want to be able to check logs for dead containers as well
(from the left side context menu)
> adding show logs command to dead containers

- commands/build-image.ts
- commands/docker-compose.ts
- commands/inspect-image.ts
- commands/open-shell-container.ts
- commands/push-image.ts
- commands/remove-container.ts
- commands/remove-image.ts
- commands/restart-container.ts
- commands/showlogs-container.ts
- commands/start-container.ts
- commands/stop-container.ts
- commands/system-prune.ts
- commands/tag-image.ts
- configureWorkspace/configure.ts
For your convenience: Adding GDPR annotations for automated extraction of meta-data of telemetry events. Pls see https://github.com/Microsoft/vscode/pull/34997 for an in-depth overview. The tooling can be found here: https://github.com/Microsoft/vscode-gdpr-tooling.
> Adding GDPR annotations

- dockerExtension.ts
- package-lock.json
This simply fixes a TypeScript build issue I introduced with #247.
> Using correct DocumentSelector type

- gulpfile.js
> Skip VSIX upload if ENV vars not set

- configureWorkspace/configure.ts
> Fix docker workspace files generation

- CHANGELOG.md
- README.md
See https://github.com/Microsoft/vscode-docs/pull/1667.
> Update Linux post install link

- .vscode/settings.json
- README.md
- commands/build-image.ts
- commands/docker-compose.ts
- commands/open-shell-container.ts
- commands/push-image.ts
- commands/showlogs-container.ts
- commands/start-container.ts
- commands/system-prune.ts
- commands/utils/create-terminal.ts
- commands/utils/docker-endpoint.ts
- dockerExtension.ts
- explorer/dockerExplorer.ts
- package.json
- typings/dockerode.d.ts
This introduces a new setting which allows to set the docker endpoint like the env variable DOCKER_HOST
> Implement configurable endpoint setting

- commands/build-image.ts
- commands/docker-compose.ts
- commands/inspect-image.ts
- commands/remove-container.ts
- commands/utils/quick-pick-container.ts
- commands/utils/quick-pick-image.ts
- configureWorkspace/configure.ts
- dockerCompose/dockerComposeCompletionItemProvider.ts
- dockerCompose/dockerComposeHoverProvider.ts
- dockerExtension.ts
- dockerHubApi.ts
- dockerfile/dockerfileCompletionItemProvider.ts
- documentContentProviders/dockerInspect.ts
- explorer/deploy/util.ts
- explorer/deploy/wizard.ts
- explorer/models/azureRegistryNodes.ts
- explorer/models/dockerHubNodes.ts
- explorer/models/registryRootNode.ts
- explorer/models/rootNode.ts
- helpers/suggestSupportHelper.ts
- tslint.json
Mostly grandfathered in (not worth the risk of mistakes)
> Lint: promise-function-async, prefer-for-of, no-unused-expression

- package.json
See https://github.com/Microsoft/vscode-languageserver-node/issues/378
> Fix issue with languageclient 4.4.0

- dockerExtension.ts
> Change debugOptions so that Dockerfil Language server starts.

- configureWorkspace/configure.ts
https://github.com/docker-library/docs/commit/e19ba52efe31aefb75f6753da40d0a2d68fe571f
> Remove deprecated "go-wrapper" script

- explorer/dockerExplorer.ts
Related to #371, which I can't seem to repro now.  This would not fix that, but it's definitely a bug (although it should be moot because of the auto-refresh).
> refresh issue

- explorer/utils/dockerHubUtils.ts
> Better docker username prompt

- commands/build-image.ts
- commands/utils/quick-pick-container.ts
- dockerCompose/dockerComposeParser.ts
- dockerExtension.ts
- dockerHubApi.ts
- explorer/dockerExplorer.ts
- helpers/suggestSupportHelper.ts
- test/asyncpool.test.ts
- test/global.test.ts
> Improve build-image and fix some strict typescript issues 

- .vscode/launch.json
- configureWorkspace/configure.ts
- dockerExtension.ts
- explorer/utils/azureUtils.ts
- explorer/utils/dockerHubUtils.ts
- package.json
- test/buildAndRun.test.ts
- test/configure.test.ts
- test/global.test.ts
- test/index.ts
Fixes https://github.com/Microsoft/vscode-docker/issues/362.
Will provide documentation in a separate PR.
> Add API to control Add dockerfiles command

- docs/api.md
- package.json
> Add documentation for configure API

- explorer/models/rootNode.ts
Fixes #371 
The old code only compared images, but we also need to compare tags, and might as well compare everything for better reliability.
> Fix image refresh

- test/customRegistries.test.ts
… Since https://github.com/Microsoft/vscode-azuretools/pull/239 was fixed.
> User empty user name in test

- commands/tag-image.ts
> Check to see if path already contains '/' before prepending

- package.json
> Connect menu only on 'Private registries'

- explorer/models/rootNode.ts
- package.json
- test/customRegistries.test.ts
> Correct menu casings

- commands/azureCommands/delete-repository.ts
- commands/utils/quick-pick-azure.ts
Tiny PR updating registry management confirmations
Fixes issues raised in #421
> updated prompts

- explorer/models/dockerHubNodes.ts
> Sort docker repository nodes

- commands/build-image.ts
- dockerExtension.ts
> Pass in dockerfile param to build

- commands/inspect-image.ts
- commands/open-shell-container.ts
- commands/push-image.ts
- commands/remove-container.ts
- commands/remove-image.ts
- commands/restart-container.ts
- commands/showlogs-container.ts
- commands/start-container.ts
- commands/stop-container.ts
- commands/tag-image.ts
- commands/utils/quick-pick-container.ts
- commands/utils/quick-pick-image.ts
- dockerExtension.ts
> Fix remove all images and add related telemetry

- commands/utils/quick-pick-image.ts
Narrow scope of try catch.
Fix #440
> Add ui.Quickpick to handle UserCancelledError.

- explorer/models/customRegistryNodes.ts
> Fix v2 registry version call

- test/configure.test.ts
- test/global.test.ts
Minor refactoring of configure tests, no product changes.
> Refactor configure tests

- configureWorkspace/configure.ts
- configureWorkspace/configure_asp.net.core.ts
- configureWorkspace/configure_go.ts
- configureWorkspace/configure_java.ts
- configureWorkspace/configure_net.core.console.ts
- configureWorkspace/configure_node.ts
- configureWorkspace/configure_python.ts
- configureWorkspace/configure_ruby.ts
No code changes.  In preparation for some, well, code changes.
Okay, one change:  This was added to .NET core Linux dockerfiles (came from VS's version):
```
#Depending on the operating system of the host machines(s) that will build or run the containers, the image specified in the FROM statement may need to be changed.
#For more information, please see http://aka.ms/containercompat
```
> Refactor add-docker-files for easier reading/maintenance

- package.json
> Remove dup delete-ACR-Image

- commands/start-container.ts
- commands/utils/docker-endpoint.ts
Fixes #482 
Check for data.Config.ExposedPorts = undefined
> Run interactive not working if no exposed ports

- configureWorkspace/configure_node.ts
> Fix Node.js debug compose file

- configureWorkspace/config-utils.ts
- configureWorkspace/configure.ts
- configureWorkspace/configure_dotnetcore.ts
- configureWorkspace/configure_go.ts
- configureWorkspace/configure_java.ts
- configureWorkspace/configure_node.ts
- configureWorkspace/configure_python.ts
- configureWorkspace/configure_ruby.ts
- test/configure.test.ts
Fixes #391 
For next milestone.
>  Don't output EXPOSE if empty port specified

- package.json
> Change default shell from /bin/sh to /bin/bash

- commands/build-image.ts
- commands/docker-compose.ts
- commands/utils/quickPickWorkspaceFolder.ts
- configureWorkspace/configure.ts
Improves message for #532.
Also combines the code and correctly throws rather than just showing messages.
> Improve message that opening a folder is required for some commands

- explorer/models/containerNode.ts
- explorer/models/getImageOrContainerDisplayName.ts
- explorer/models/imageNode.ts
- test/getImageOrContainerDisplayName.test.ts
- test/trimWithElipsis.test.ts
> Fix truncation of multi-level image IDs

- configureWorkspace/configure.ts
- test/configure.test.ts
See https://github.com/Microsoft/vscode-docker/issues/536
> Better error message for .csproj not found.

- configureWorkspace/configure.ts
- configureWorkspace/configure_dotnetcore.ts
- test/configure.test.ts
> Allow configure template to specify not to ask for a port

- package.json
> Fix casing of Pull Image from Azure

- .vscode/launch.json
- .vscode/tasks.json
Detail: https://code.visualstudio.com/docs/editor/variables-reference#_why-isnt-workspaceroot-documented
> Update variables reference

- gulpfile.js
- package.json
This fixes 5 vulnerabilities reported by `npm audit`. 4 of them are with high severity.
Upgrading `gulp` from `3.9.1` to `4.0.0` doesn't require any changes to the tasks. Only [breaking change](https://codeburst.io/switching-to-gulp-4-0-271ae63530c0) is with task dependency list parameter, which is not used in the gulpfile. 
**Edit:** Actually, tasks now require a stream, promise, event emitter, child process or observable to be returned. I modified the `upload-vsix`task to always call the callback function to achieve that. I didn't know how to test the task, so I'm not sure if this solution is sufficient. Please let me know. 🙂
<details>
<summary>npm audit security report</summary>
```
=== npm audit security report ===
SEMVER WARNING: Recommended action is a potentially breaking change …
```
> Upgrade gulp to v4

- package.json
> Remove vscode telemetry from deps

- package.json
Fixes #619. These got broken in recent merge
> Fix some broken menus

- commands/open-shell-container.ts
- package.json
Fixes #518
Powershell: 
CMD: 
Bash on Mac:
> Change default bash command for attaching the shell in Linux container

- explorer/models/rootNode.ts
- images/dark/unhealthyContainer.svg
- images/light/runningContainer.svg
- images/light/unhealthyContainer.svg
Added the ability to have the icons change from green to yellow if a container is running but is in an "unhealthy" state.
> Different icons for unhealthy containers

- explorer/models/taskNode.ts
> Fix Learn How button

- CHANGELOG.md
- README.md
- package.json
This also contains some settings changes that were supposed to be in the useCertificateStore PR.
> Prepare for 0.4.0 release

- commands/utils/quick-pick-azure.ts
Will merge after 0.4.0. Couldn't find any other instances of this problem.
> Don't use string constant for msg item comparison

- commands/system-prune.ts
- dockerExtension.ts
> Fix null ref show connection error during prune

- commands/utils/quick-pick-container.ts
- commands/utils/quick-pick-image.ts
> Fix casing of All *

- dockerExtension.ts
- entrypoint.js
- explorer/models/errorNode.ts
- explorer/models/taskNode.ts
- extension.ts
- webpack.config.js
> Fix some images, plus a few minor changes

- commands/azureCommands/acr-logs-utils/logFileManager.ts
- commands/azureCommands/acr-logs-utils/tableViewManager.ts
- commands/azureCommands/pull-from-azure.ts
- commands/utils/SourceArchiveUtility.ts
- dockerExtension.ts
This closes #639, closes #640, closes #648, and closes #666 
Unhandled error if you cancel saving Azure log #639
Save Azure log dialog shows "log..log" as the filename extension #640
docker.acr.pullimage issue #648
> ACR Fixes (Logs & Docker Pull)

- commands/utils/quick-pick-azure.ts
Improve message from #695 so that it does not incorrectly say you must create subscriptions when not logged in.
> Fix no subscriptions msg

- CHANGELOG.md
- package.json
- webpack.config.js
> Ready for 0.5.0 release and fix 696

- CHANGELOG.md
- package.json
> Update vscode version required by language client 5.0.0:

- commands/open-shell-container.ts
- commands/remove-container.ts
- commands/restart-container.ts
- commands/showlogs-container.ts
- commands/stop-container.ts
- commands/utils/docker-endpoint.ts
- commands/utils/quick-pick-container.ts
- explorer/models/rootNode.ts
- package-lock.json
Fixes #739 by removing "running" filter for show logs.
Also improves code quality.
> Filter issues

- package-lock.json
- package.json
Fixes #779 
Forgot to check in update of win-ca version for the hotfix.
> Update version of win-ca to get fallback code

- debugging/coreclr/registerDebugger.ts
- explorer/deploy/util.ts
- extension.ts
> Create only one output channel

- commands/registrySettings.ts
Fixes #822 
Adds more info to error for #806
> Don't ask to save registry path if no workspace

- .vscode/settings.json
- commands/azureCommands/acr-logs.ts
- commands/start-container.ts
- commands/utils/quick-pick-image.ts
> Fix run/run interactive

- explorer/dockerExplorerProvider.ts
- explorer/models/azureRegistryNodes.ts
- explorer/models/customRegistryNodes.ts
- explorer/models/dockerHubNodes.ts
- explorer/models/registryRootNode.ts
- explorer/models/rootNode.ts
- explorer/models/taskNode.ts
For next release...
Fixes #818
> Handle errors in getchildren

- style/acr-logs/stylesheet.css
Last release broke the UI for viewLogs
Fixes #851
> theme color text fixes for view logs

- package-lock.json
- package.json
- test/configure.test.ts
> Update to UI 0.23.1

- package-lock.json
- package.json
Builds on https://github.com/Microsoft/vscode-docker/pull/886
> Update to UI 0.23.2

- README.md
> Update README.md to point out workaround

- explorer/models/azureRegistryNodes.ts
> Fix casing of Sign In

- package.json
- src/commands/containers/inspectContainer.ts
- src/commands/registerCommands.ts
More low-hanging fruit. Modeled after "Inspect Image"
Fixes https://github.com/microsoft/vscode-docker/issues/714
> Add inspect container

- src/tree/registries/private/PrivateRegistriesTreeItem.ts
Fixes https://github.com/microsoft/vscode-docker/issues/980
> Fix casing of Connect Registry

- CHANGELOG.md
- README.md
- package-lock.json
- package.json
Already merged to rel/0.6.3 branch (https://github.com/microsoft/vscode-docker/pull/1004) - just moving over to master.
> Change publisher from "PeterJausovec" to "ms-azuretools"

- src/tree/LocalRootTreeItemBase.ts
- src/tree/settings/TreeSettingListStep.ts
- src/tree/settings/TreeSettingStep.ts
Fixes https://github.com/microsoft/vscode-docker/issues/1012
> Add option to reset settings

- src/commands/volumes/inspectVolume.ts
Fixes https://github.com/microsoft/vscode-docker/issues/1092
> Fix inspect volume

- package.json
Old (see the title on the right and the list of extensions on the left):
New:
> Fix Docker settings title

- src/utils/quick-pick-file.ts
We've got a number of issues/PRs out for people wanting support for Dockerfile.\<something\>. The most common workaround is to do something like this:
```
"files.associations": {
"[Dd]ockerfile*": "dockerfile",
"docker-compose*": "yaml"
}
```
That works great for icons/intellisense, but not command palette commands like "Build Image" (as mentioned [here](https://github.com/microsoft/vscode-docker/issues/102#issuecomment-462759346) by @crstamps2). This PR fixes that.
Note: I'm intentionally take a different approach than PRs like https://github.com/microsoft/vscode-docker/pull/904 which add custom settings. I'm also not dealing with docker-compose files at all. I wanted to unblock a good chunk of users as fast as possible with hopefully an uncontroversial fix.
> Respect `file.associations` for Dockerfile commands

- src/extension.ts
Hopefully this message is hardly ever shown - it only applies for the people that haven't updated the Docker extension to the new publisher and also don't have the latest version of VS Code.
The old extension should continue to work for them until they reload and there should be minimal effects from the new extension. The most noticeable is the new explorers will look like this:
Fixes #1093
> Validate old publisher id

- src/tree/registries/dockerV2/GenericDockerV2RegistryTreeItem.ts
Welp knew there would be some regressions from the refactor
Fixes https://github.com/microsoft/vscode-docker/issues/1142
> Fix v2 check

- .azure-pipelines/common/build.yml
- package-lock.json
- package.json
- test/buildAndRun.test.ts
- test/configure.test.ts
- test/global.test.ts
Moved `Test*` classes to dev package and other minor improvements to test code
Also had to change default version of node for Azure Dev Ops. I was running into build failures on Linux only, and narrowed it down to an old version of npm causing issues. Node 10 is LTS anyways
> Bump shared packages

- package.json
- src/constants.ts
- src/debugging/coreclr/ChildProcessProvider.ts
- src/debugging/coreclr/CommandLineDotNetClient.ts
- src/debugging/coreclr/LocalAspNetCoreSslManager.ts
- src/debugging/coreclr/dockerDebugConfigurationProvider.ts
- src/debugging/coreclr/dockerManager.ts
- src/debugging/coreclr/registerDebugConfigurationProvider.ts
- src/utils/quick-pick-file.ts
> Supporting SSL in ASP.NET Core web apps

- src/configureWorkspace/configure.ts
Updating of the .dockerignore file to match what is created by VS. There are also corresponding changes in VS.
> Update .dockerignore to match VS

- package-lock.json
- package.json
- src/commands/registries/azure/deployImageToAzure.ts
- src/tree/registries/azure/SubscriptionTreeItem.ts
Mostly doing it for the icon changes here: https://github.com/microsoft/vscode-azuretools/pull/574
Relies on https://github.com/microsoft/vscode-azuretools/pull/577 - @nturinski made some changes to how `LocationListStep` works that didn't quite work for Docker
Also fixes https://github.com/microsoft/vscode-docker/issues/1220
> Bump shared npm packages

- src/commands/containers/pruneContainers.ts
- src/commands/images/pruneImages.ts
- src/commands/networks/pruneNetworks.ts
- src/commands/pruneSystem.ts
- src/commands/registerCommands.ts
- src/commands/volumes/pruneVolumes.ts
- src/utils/osUtils.ts
- src/utils/wrapError.ts
> Better showing of ENOENT error for commands

- test/TestTerminalProvider.ts
> Remove usage of deprecated API

- src/commands/images/runAzureCliImage.ts
> Use ext.terminalProvider for Run AzCLI Image

- package.json
- src/tasks/DockerBuildTaskProvider.ts
- src/tasks/DockerRunTaskProvider.ts
> Allow non-platform-specific tasks

- src/commands/registries/logInToDockerCli.ts
> Don't fail on warning for insecure creds

- .azure-pipelines/common/test.yml
- resources/GetBlazorManifestLocations.targets
- resources/GetTargetPath.proj
- src/debugging/coreclr/netCoreProjectProvider.ts
- src/debugging/netcore/NetCoreDebugHelper.ts
- src/tasks/netcore/NetCoreTaskHelper.ts
- src/tasks/netcore/updateBlazorManifest.ts
> Containerize Blazor static web assets manifest

- .gitattributes
- src/debugging/DockerDebugConfigurationProvider.ts
- src/debugging/coreclr/dockerNetCoreDebugConfigurationProvider.ts
- src/debugging/netcore/NetCoreDebugHelper.ts
- src/tasks/netcore/updateBlazorManifest.ts
- src/utils/nps.ts
Resolves #1419
Resolves #1421
Also resolves the path issue @haniamr ran into.
> Miscellaneous fixes

- README.md
- package.json
This link is easier way to view the Readme: https://github.com/microsoft/vscode-docker/blob/40f175ba2358687178488cf9dcda41973f22e4bb/README.md
Also resolves #1435
> Change the pipeline status badge to nightly

- package-lock.json
- src/utils/nps.ts
(Also updates previously missed `package-lock.json`.)
> Revert NPS session count back to 10.

- src/debugging/DockerServerReadyAction.ts
Allows users to specify a fixed (i.e. with no substitutions) URI format string in the `dockerServerReadyAction` configuration object.  Also now displays an error if substitutions *are* made in the URI format string, but do not match the number of substitutions the extension expects (i.e. two, for protocol and port).
Resolves #1448
> Allow fixed URI format string in dockerServerReadyAction.

- src/tree/registries/azure/AzureAccountTreeItem.ts
Fix lint issues that was introduced by my previous change.
> Fix lint issues

- CHANGELOG.md
- package-lock.json
- package.json
> Update version and change log for 0.10.0

- src/commands/registries/azure/deployImageToAzure.ts
Adds an 'Open Link' action to the notification that is displayed upon successful deployment of an image to azure app service.
Addresses #1507.
> Add an "Open" button to open the Azure website

- .azure-pipelines/linux/xvfb.init
Copying @EricJizbaMSFT's fix from this PR: https://github.com/microsoft/vscode-azureappservice/pull/1391
> Port the fix for Xvfb to ensure Linux tests run

- README.md
Fixes https://github.com/microsoft/vscode-docker/issues/1578
> Use aka.ms links to VSCode docs in README

- package.json
Fixes https://github.com/microsoft/vscode-docker/issues/1641
> Add Docker help command to command palette

- src/configureWorkspace/configureGo.ts
- src/configureWorkspace/configureJava.ts
- src/configureWorkspace/configureNode.ts
- src/configureWorkspace/configureOther.ts
- src/configureWorkspace/configureRuby.ts
- src/dockerCompose/dockerComposeKeyInfo.ts
- test/configure.test.ts
Switch from scaffolding 2.1 to 3.4 to be consistent with the VS tooling.
> Bump compose version to 3.4

- .vscodeignore
- README.md
Fixes #1654
Out of curiosity I compared the VSIX size before and after, it only gained about 200 KB which is pretty inconsequential.
> Include readme images in VSIX

- src/tree/registries/gitLab/GitLabRepositoryTreeItem.ts
> Fix GitLab repository missing name

- src/debugging/coreclr/CliDockerClient.ts
- src/debugging/netcore/NetCoreDebugHelper.ts
Capture and output of docker exec and show it in the output during vsdbg installation.
> Show vsdbg install progress

- package.json
> Require VSCode 1.41

- src/tasks/DockerBuildTaskProvider.ts
- src/tasks/DockerPseudoterminal.ts
- src/tasks/DockerTaskProvider.ts
> Improved task resolution

- src/configureWorkspace/configureDotNetCore.ts
- src/configureWorkspace/configurePython.ts
- src/debugging/python/PythonDebugHelper.ts
- src/tasks/python/PythonExtensionHelper.ts
- src/tasks/python/PythonTaskHelper.ts
- src/utils/pythonUtils.ts
- Fixes the generated image name in the main compose file
- Fixes the temp directory path issue on Mac
> [Python] Fix for the compose image name + temp dir on Mac

- src/configureWorkspace/configureDotNetCore.ts
- src/configureWorkspace/configurePython.ts
- src/debugging/python/PythonDebugHelper.ts
- src/tasks/python/PythonExtensionHelper.ts
- src/tasks/python/PythonTaskHelper.ts
- src/utils/pythonUtils.ts
* [Python] Fix for the compose image name + temp dir on Mac
* Image/Service name normalization for netcore
* Remove the imageName since it is no longer needed
> Cherry-pick for (#1703) to master

- src/configureWorkspace/configureDotNetCore.ts
(Cherry Pick) Do not add https port to ASPNETCORE_URLS (#1705)
> (Cherry Pick) Do not add https port to ASPNETCORE_URLS (#1705)

- CHANGELOG.md
- src/configureWorkspace/configureDotNetCore.ts
* Fix slash
* Change to projected release date
(Fixes #1711)
> Cherry pick: Fix slash (#1712)

- src/debugging/netcore/NetCoreDebugHelper.ts
* Reuse an existing debugger if present
* updated a comment
> (CherryPick) Reuse an existing debugger if present (#1704)

- package.json
> Use cmd on Windows containers

- src/debugging/netcore/NetCoreDebugHelper.ts
Do not install Unzip on non-alpine flavor
> Don't install unzip

- src/configureWorkspace/configureDotNetCore.ts
> Fix missing os: Windows in dockerRun config

- src/debugging/netcore/NetCoreDebugHelper.ts
> Use single-equals because sh likes it

- src/utils/spawnAsync.ts
Fixes #1744 
We will output the command line that was executed along with the stderr output.
> Better error message output

- src/commands/registries/azure/deployImageToAzure.ts
- src/commands/selectCommandTemplate.ts
- src/tree/registries/IRegistryProvider.ts
- src/tree/registries/RegistriesTreeItem.ts
- src/tree/registries/auth/AzureOAuthProvider.ts
- src/tree/registries/auth/BasicOAuthProvider.ts
- src/tree/registries/auth/IAuthProvider.ts
- src/tree/registries/auth/oAuthUtils.ts
- src/tree/registries/azure/AzureAccountTreeItem.ts
- src/tree/registries/azure/AzureRegistryTreeItem.ts
- src/tree/registries/azure/AzureRepositoryTreeItem.ts
- src/tree/registries/azure/SubscriptionTreeItem.ts
- src/tree/registries/azure/azureRegistryProvider.ts
- src/tree/registries/connectWizard/IConnectRegistryWizardContext.ts
- src/tree/registries/connectWizard/RegistryPasswordStep.ts
- src/tree/registries/dockerHub/dockerHubRegistryProvider.ts
- src/tree/registries/dockerV2/DockerV2RegistryTreeItemBase.ts
- src/tree/registries/dockerV2/DockerV2RepositoryTreeItem.ts
- src/tree/registries/dockerV2/GenericDockerV2RegistryTreeItem.ts
- src/tree/registries/dockerV2/genericDockerV2RegistryProvider.ts
- src/tree/registries/gitLab/gitLabRegistryProvider.ts
- src/utils/azureUtils.ts
> OAuth implementation and refactoring

- src/configureWorkspace/configure.ts
- src/configureWorkspace/configureCompose.ts
- src/configureWorkspace/scaffolding.ts
Show the created compose file to user.
> open the compose file created by 'Add docker compose..' command

- src/debugging/DebugHelper.ts
- src/debugging/DockerDebugConfigurationProvider.ts
- src/debugging/netcore/NetCoreDebugHelper.ts
- src/debugging/node/NodeDebugHelper.ts
- src/debugging/python/PythonDebugHelper.ts
Resolves #1602
The output looks like this:
> Emit application host ports to output window

- src/tree/settings/TreeSettingListStep.ts
- src/tree/settings/TreeSettingStep.ts
Fixes #1770.
Also fixes a missed call to `localize()`.
> Fix NLS regression in configure explorer

- package.json
- package.nls.json
Same as https://github.com/microsoft/vscode-dapr/pull/78
> Description will not show in marketplace

- src/configureWorkspace/configureDotNetCore.ts
When scaffolding docker-compose.debug.yml for asp net core app, added a comment that points to a document explaining how to setup the dev cert.
Fixes: #1724
> Add a comment on setting up https dev cert

- src/utils/azureUtils.ts
Remove ansi escape sequence characters.
Fixes #1511
> Remove ansi escape characters

- src/utils/azureUtils.ts
- test/global.test.ts
Added more logging and also verification with retry. Hopefully this fixes the transient error.
Fixes: 1788
> Add more logging and retry logic in test setup

- src/commands/dockerInstaller.ts
> Install on Mac via terminal

- src/commands/installDocker.ts
> Fix platform check

- src/commands/dockerInstaller.ts
update docker installer message to include start Docker Desktop.
> update docker installer message

- src/extension.ts
- src/telemetry/surveys/activeUseSurvey.ts
- test/telemetry/surveys/activeUseSurvey.test.ts
> Temporarily disable active use survey

- src/configureWorkspace/configureDotNetCore.ts
> Capture the net core version in telemetry

- src/tasks/netcore/updateBlazorManifest.ts
- src/tree/registries/azure/AzureTaskTreeItem.ts
> Require Blazor manifest to be a file

- package.json
- test/TestTerminalProvider.ts
> Unblock engine upgrade

- package.json
Adding a default value for the "pattern" property to be used as a starting point.
> Add default value for dockerServerReady.pattern

- src/debugging/coreclr/CommandLineDotNetClient.ts
- src/debugging/coreclr/LocalAspNetCoreSslManager.ts
- src/debugging/coreclr/dockerManager.ts
- src/debugging/coreclr/prereqManager.ts
- src/utils/LocalOSProvider.ts
- src/utils/platform.ts
- test/debugging/coreclr/prereqManager.test.ts
Reverts microsoft/vscode-docker#1849
> Revert "Revert "osProvider.Os to include Mac (#1843)""

- src/utils/refreshDockerode.ts
> Fix Dockerode setup issue

- package.json
> Add Dockerfile.* file association

- package-lock.json
- package.json
- src/telemetry/TelemetryReporterProxy.ts
- test/telemetry/TelemetryReporterProxy.test.ts
Please refer #1925 . I will revert this until the vscode-extension-telemetry is fixed.
> Revert "telemetry changes for vscodespace"

- src/commands/containers/browseContainer.ts
This fixes #1943 (which is happening due to https://github.com/microsoft/vscode-extension-telemetry/issues/45)
> Fix telemetry error

- src/tree/registries/RegistriesTreeItem.ts
Removing this entry from the registry provider pick list, since we're working on developing a new extensibility model.
> Remove "Learn how to contribute..." from pick list

- src/commands/selectCommandTemplate.ts
> fix default compose up command

- src/configureWorkspace/configureDotNetCore.ts
> Cherry-pick change repo for .NET 5.0+

- src/extension.ts
- src/telemetry/ExperimentationServiceAdapter.ts
- src/telemetry/surveys/SurveyManager.ts
- src/telemetry/surveys/nps2.ts
Fixes #1854 (will need cherry-pick to master)
> Add new NPS survey

- src/extension.ts
- src/telemetry/ExperimentationServiceAdapter.ts
- src/telemetry/surveys/SurveyManager.ts
- src/telemetry/surveys/nps2.ts
> Cherry-pick add new NPS survey (#1984)

- package.nls.json
- src/tree/registries/dockerHub/dockerHubRegistryProvider.ts
> Change text in a few spots

- src/debugging/netcore/NetCoreDebugHelper.ts
> Use right OS while constructing the path

- package-lock.json
- package.json
Fixes bug wherein tas client always returns false for cached flighting info.
> Update tas client

- src/extension.ts
The install ID lookup is a bit slow, about 100 ms. It happens during extension activation, which is the most critical path for performance. Caching it speeds it up after the first time. The install ID can never change (even after uninstalling/reinstalling Docker Desktop), so it's safe enough to cache forever.
> Cache install ID lookup

- package-lock.json
- package.json
- src/extension.ts
- src/telemetry/ExperimentationServiceAdapter.ts
> Use latest version of TAS package

- src/telemetry/surveys/SurveyManager.ts
This maybe needs to go into 1.3.0.
> Capture eligibility state

- src/telemetry/surveys/SurveyManager.ts
> Maximize to one awareness toast per session

- src/telemetry/surveys/SurveyManager.ts
Fixes #2064. Cherry-picked from #2070.
> Cherry-pick maximize to one awareness toast per session (#2070)

- src/configureWorkspace/configureDotNetCore.ts
- src/debugging/DockerDebugScaffoldingProvider.ts
- src/tasks/netcore/NetCoreTaskHelper.ts
> Scaffold with configureSsl false when it's clear

- src/debugging/node/NodeDebugHelper.ts
- src/debugging/python/PythonDebugHelper.ts
> Apply all passed-in debug options

- src/docker/ContextManager.ts
- src/docker/DockerodeApiClient/DockerodeApiClient.ts
Fixes #2124, fixes #2125, fixes #2121
> Fix several bugs with new client API

- resources/python/launcher.py
> Use python3 explicitly

- package-lock.json
- package.json
- src/telemetry/surveys/awareness.ts
This will give us the language traffic filter
> Use latest TAS client

- src/commands/containers/restartContainer.ts
- src/commands/containers/startContainer.ts
- src/commands/containers/stopContainer.ts
> Fix wrong variable referenced

- src/commands/registries/azure/DockerWebhookCreateStep.ts
- src/debugging/coreclr/CommandLineDotNetClient.ts
- src/extension.ts
- src/utils/cryptoUtils.ts
The unhashed ID is automatically discarded by the telemetry system, so change to a hashed ID. We only need it for uniqueness anyway.
> Change to hashed Docker Desktop ID

- src/docker/ContextManager.ts
- src/extension.ts
> Fix error on contexts file / folder not existing

- .azure-pipelines/compliance/PoliCheckExclusions.xml
- .azure-pipelines/compliance/compliance.yml
- .azure-pipelines/main.yml
> Enable Policheck

- src/debugging/DockerDebugConfigurationProvider.ts
- src/debugging/DockerServerReadyAction.ts
Fixes #2050, fixes #2148.
Definitely for 1.5.0 (not 1.4.0)
> Fix some Python hot reload issues

- src/utils/executeAsTask.ts
Partial fix for #2177. The other part should be fixed by https://github.com/microsoft/vscode/commit/8c1aba0d95fe745fa71e7a9dd44b540beb37e86d; will verify that in tomorrow's Insiders build.
> Use home as default cwd for tasks

- CHANGELOG.md
- package-lock.json
- package.json
- src/docker/ContextManager.ts
> Make context switch listeners even more best-effort

- CHANGELOG.md
- src/docker/ContextManager.ts
Fixes #2181. Cherry pick of #2182.
> Cherry-pick Make context switch listeners even more best-effort (#2182)

- src/tree/containers/ContainersTreeItem.ts
> Fix network logic in containers tree view

- src/commands/containers/attachShellContainer.ts
- src/commands/images/runImage.ts
- src/utils/executeAsTask.ts
> Always run new task for attach / run interactive

- src/docker/ContextManager.ts
> Fix context type issue

- src/docker/ContextManager.ts
Fixes #2204. I don't think the error is widespread enough to warrant another servicing release; only about .1%.
> Change how tree init errors are caught

- src/tree/registries/registryPasswords.ts
Fixes https://github.com/microsoft/vscode-docker/issues/722
It took me some time to convince myself that this (ignoring keytar errors) is both sufficient and safe to fix the issue above, but at the end I think it is.
> Allow authentication to registries without gnome-keyring

- src/utils/executeAsTask.ts
Fixes https://github.com/microsoft/vscode-docker/issues/2231
> Wait for task execution properly

- package.json
- src/tree/help/HelpsTreeItem.ts
> Collapse some views by default, updates to help

- src/debugging/DockerDebugConfigurationProvider.ts
Seems to be what causes #2249.
> Robustness to common user error

- package.json
- package.nls.json
- src/commands/containers/aciContainerActionWarning.ts
- src/commands/containers/confirmAllAffectedContainers.ts
- src/commands/containers/removeContainer.ts
- src/commands/containers/restartContainer.ts
- src/commands/containers/startContainer.ts
- src/commands/containers/stopContainer.ts
- src/commands/context/inspectDockerContext.ts
- src/commands/context/removeDockerContext.ts
- src/commands/context/useDockerContext.ts
- src/commands/images/tagImage.ts
- src/commands/registerCommands.ts
- src/commands/registries/azure/deployImageToAci.ts
- src/commands/registries/azure/deployImageToAzure.ts
- src/docker/DockerServeClient/DockerServeClient.ts
- src/tree/containers/ContainerTreeItem.ts
- src/tree/containers/ContainersTreeItem.ts
- src/tree/contexts/ContextTreeItem.ts
- src/tree/contexts/ContextsTreeItem.ts
- src/tree/contexts/aci/AciContextCreateStep.ts
- src/tree/contexts/aci/ContextNameStep.ts
- src/tree/contexts/aci/IAciWizardContext.ts
- src/tree/registries/RemoteTagTreeItem.ts
- src/utils/executeAsTask.ts
Fixes #1718. Also implements a few of the now-available APIs in the new Docker Serve client.
> Add ability to deploy from ACR / Docker Hub to ACI

- src/telemetry/surveys/SurveyManager.ts
- src/telemetry/surveys/awareness.ts
- src/telemetry/surveys/nps2.ts
> Add button to awareness toast; broaden eligibility

- package.json
> Disable outdated image check by default

- src/commands/registries/azure/deployImageToAci.ts
- src/utils/executeAsTask.ts
> Option for rejecting on error

- src/tasks/netcore/updateBlazorManifest.ts
> Reduce case sensitivity on Blazor manifest update

- src/debugging/netcore/NetCoreDebugHelper.ts
Partly fixes #2248, the rest is covered by #840.
> Respect input processId if it is present

- resources/templates/netCore/docker-compose.debug.yml.template
- resources/templates/netCore/docker-compose.yml.template
> Cherry-pick Template change to make .NET scaffolding better (#2314)

- package.nls.json
- src/debugging/netcore/NetCoreDebugHelper.ts
- src/debugging/netcore/VsDbgHelper.ts
Fixes #2233
Also some other improvements to the debugger installation experience, and increased robustness.
> Unconditionally install VSDBG for .NET launch configs

- src/tree/LocalRootTreeItemBase.ts
> Clear message to replace operation cancelled error

- src/debugging/python/PythonDebugHelper.ts
- test/index.ts
- test/nonNull.test.ts
- test/runTest.ts
Fixes #2302. Also unrelatedly, slightly improves the fix for #2313.
> Fix tests silently failing

- src/commands/context/useDockerContext.ts
Might fix the root cause of #2358
I wondered if these events were happening out of order. This way if the `onContextChanged` event fires before control returns to this method, it won't get stuck.
> Fix possible cause of UI getting stuck saying "Switching"

- src/tree/contexts/aci/ContextNameStep.ts
> Resource group name sugggestion

- package.json
- src/commands/selectCommandTemplate.ts
> Use tail param in logs command

- src/tree/contexts/aci/ContextNameStep.ts
> Prevent duplicate context names

- .vscodeignore
These updates don't seem strictly necessary as the files referenced aren't showing up in the vsix, but this file was out-of-date anyway so I thought it would be harmless to update it.
> Minor updates to vscodeignore

- src/commands/images/pushImage.ts
> Change error handling on image push

- src/commands/context/useDockerContext.ts
> Force refresh of Docker context after 10 seconds

- src/commands/images/pullImage.ts
> Skip pulling images with <none> tags

- src/tree/contexts/aci/AciContextCreateStep.ts
Part of #2391. Uses the interactive terminal for auth if needed.
> Use interactive terminal for Azure login

- src/debugging/netcore/VsDbgHelper.ts
> chmod +x the GetVsDbg.sh script

- src/commands/compose.ts
- src/commands/containers/attachShellContainer.ts
- src/commands/containers/confirmAllAffectedContainers.ts
- src/commands/selectCommandTemplate.ts
- src/docker/ContextManager.ts
- src/docker/Contexts.ts
- src/tree/contexts/ContextTreeItem.ts
- src/tree/contexts/ContextsTreeItem.ts
- test/commands/selectCommandTemplate.test.ts
> Change context type determination

- src/commands/dockerInstaller.ts
> Fix installer file extension

- src/docker/files/ContainerFilesUtils.ts
Some Windows containers (e.g. Nanoserver based) do not have the WMI installed, which means we cannot obtain the file metadata needed by our file system provider (used by VS Code prior to enumerating directories or opening files).
Until a better mechanism is identified, the solution is to simply "fake" the metadata (indicating that the file/directory was just modified a millisecond ago).  This will allow users to explore and open files, but at the cost of VS Code aggressively refreshing the contents of the file (e.g. when switching tabs within VS Code or switching focus to VS Code from another application) because we (and therefore it) doesn't know whether or when it may have been modified.  For the exceedingly few users of Windows containers, this is likely good enough and we'll see if we …
> Fallback to "recently modified" in Windows stat() failures.

- src/tree/containers/files/DirectoryTreeItem.ts
> Sort files/folders with folders first

- src/tree/containers/ContainerTreeItem.ts
> Hide containers for which an action is invalid

- src/scaffolding/wizard/node/NodeScaffoldingWizardContext.ts
> Prompt for node ports when scaffolding only compose

- src/tree/containers/ContainersTreeItem.ts
> Show image ID for containers

- package.json
- package.nls.json
- src/commands/containers/composeGroup.ts
- src/commands/registerCommands.ts
> Add compose option for viewing logs

- package.json
> Show deploy to ACI and create ACI context only when AzAccount extension installed

- src/docker/ContextManager.ts
Fixes #2493. @webdog what do you think?
> Emit some info about Docker target

- src/tree/registries/gitLab/GitLabAccountTreeItem.ts
> Fix missing GitLab icon on Linux

- package.nls.json
- src/docker/ContextManager.ts
Fixes https://github.com/microsoft/vscode-docker/issues/2555
> Improve docker.host setting hints

- CHANGELOG.md
I made a few minor changes to maintain consistency with past changelogs, and also fixes the Markdown links in the first section.
> Minor changes and link fixes in changelog

- package-lock.json
- package.json
Fixes https://github.com/microsoft/vscode-docker/issues/2575
> Revert change to semver lib

- src/scaffolding/wizard/netCore/NetCoreGatherInformationStep.ts
> Fix null iterable error

- src/docker/DockerodeApiClient/DockerodeApiClient.ts
> Correct space reclaimed stat + message for volumes

- src/commands/compose/compose.ts
- src/commands/images/buildImage.ts
- src/commands/registries/azure/tasks/scheduleRunRequest.ts
- src/scaffolding/wizard/ChooseWorkspaceFolderStep.ts
- src/scaffolding/wizard/OpenDockerfileStep.ts
- src/utils/quickPickWorkspaceFolder.ts
Fixes #2512. Some examples of this in action:
> Prompt to open a workspace folder

- package-lock.json
- package.json
- src/commands/images/pruneImages.ts
- src/commands/networks/pruneNetworks.ts
- src/commands/volumes/pruneVolumes.ts
Fixes #2596. Also fixes unrelated #2603.
> Fix semantic highlighting issue

- NOTICE.html
The last PR (#2607) included some new package versions, so I've generated a new notices file that matches what was submitted there.
> Minor notices update

- package-lock.json
- package.json
Fixes #2601, fixes #2628. Also, extra fixes #2575.
> Update language server to fix "unknown parameter structure..." error

- CHANGELOG.md
- NOTICE.html
Update changelog to celebrate Codespaces making debugging possible. Also updates the notices file since there's some new versions of things.
> Update changelog (notices too) for GHCS

- src/commands/containers/composeGroup.ts
> Use path basename only as config file(s)

- src/tree/help/HelpsTreeItem.ts
> Add video link in help tree

- src/constants.ts
- src/dockerHubSearch.ts
- src/tree/images/imageChecker/OutdatedImageChecker.ts
- src/utils/registryRequestUtils.ts
> Add OCI `X-Meta-Source-Client` header to registry requests

- src/scaffolding/wizard/python/ChoosePythonArtifactStep.ts
- src/utils/quickPickFile.ts
Fixes #2664. Also, this ignores python files in the .venv folder since they are not relevant.
> Push manage.py and app.py to the top of the search list

- package-lock.json
- package.json
> Fix tooltip stuck on "Loading..."

- src/debugging/python/PythonDebugHelper.ts
- src/tasks/python/PythonTaskHelper.ts
> Fix `portsPublishAll` behavior on Python

- src/tree/LocalRootTreeItemBase.ts
> Include status in tree ID concat so nodes update their uptime

- src/tree/images/imageChecker/OutdatedImageChecker.ts
> Check all image RepoDigest values

- resources/startPage.html.template
- src/commands/startPage/StartPage.ts
- src/commands/startPage/openStartPage.ts
Spoke with @BigMorty and we are happy with the start page, so we will make it not-an-experiment.
> Start page no longer an experiment

- CHANGELOG.md
- package-lock.json
- package.json
Need to update NOTICE.html separately, since this PR will affect what goes into it.
> Update version, changelog for 1.11.0

- resources/templates/python/Dockerfile.template
> Update the Python template text about non-root users

- package.json
- package.nls.json
- src/commands/compose/compose.ts
- src/commands/registerCommands.ts
I think @ucheNkadiCode is also planning some updates to the welcome page, to address #2647.
> Make the compose up subset feature no longer an experiment

- .azure-pipelines/main.yml
Temporarily lowering Mac build pipeline version due to https://github.com/microsoft/vscode/issues/118253
> Temporarily lower Mac build pipeline version

- resources/startPage.html.template
- src/commands/startPage/StartPage.ts
- src/tree/AzExtParentTreeItemIntermediate.ts
- src/tree/containers/ContainerTreeItem.ts
- src/tree/contexts/ContextTreeItem.ts
- src/tree/images/ImageTreeItem.ts
- src/tree/networks/NetworkTreeItem.ts
- src/tree/volumes/VolumeTreeItem.ts
> Add a What's New blurb to the start page

- resources/templates/python/Dockerfile.template
Along with https://github.com/microsoft/vscode-docs/pull/4391, this fixes #2724
> Update Python Dockerfile template to use explicit UID

- src/debugging/DockerDebugConfigurationProvider.ts
Fixes #2676
On start: emit ports
On stop: remove debug container (if `removeContainerAfterDebugging` is `true` or `undefined`)
> Use global listener for debug start/stop

- src/tree/containers/ContainerTreeItem.ts
> Use NetworkSettings.Ports instead of HostConfig.PortBindings

- resources/templates/go/Dockerfile.template
Related to https://github.com/microsoft/vscode-docker/issues/2764
> Fix Go Dockerfile template

- gulpfile.ts
Should fix #2838. @philliphoff this may affect Dapr as well.
> Use main branch as base content URL

- NOTICE.html
#2848 updated a lot of dependencies so this includes updates to the notices file for those.
> Updates to notices file

- package.nls.json
- src/extension.ts
Fixes #2851. Also unrelatedly, disables the `SurveyManager` code since it is not in use and may not be in the future.
> Add ellipsis to download

- CHANGELOG.md
- package-lock.json
- package.json
- src/scaffolding/wizard/netCore/NetCoreGatherInformationStep.ts
- src/tasks/python/PythonExtensionHelper.ts
Fixes #2867. Cherry-picked from #2870.
> Cherry-pick #2870: Fix semver comparisons

- CHANGELOG.md
- package.json
Updated version and change log
> Prepare for release

- package-lock.json
- package.json
Upgrade the vsce to 1.88 to get latest underscore
> Upgrade the vsce to 1.88 to get latest underscore

- .azure-pipelines/compliance/compliance.yml
Adds malware scanning as part of our CI process, per compliance requirements.
> Add malware scan

- package-lock.json
- package.json
Updates the UI dependency to pull in the new Azure icon.
Resolves #2928.
> Update UI dependency for new icon.

- CHANGELOG.md
Update change log to include latest features
> Update change log to include latest features

- package-lock.json
- package.json
Update version to 1.13.1-alpha
> Update version to 1.13.1-alpha

- package.json
Addresses [issue 2922](https://github.com/microsoft/vscode-docker/issues/2922)
> Opt out of virtual workspaces

- src/commands/containers/inspectContainer.ts
- src/commands/images/inspectImage.ts
- src/commands/installDocker.ts
- src/commands/startPage/openStartPage.ts
- src/extension.ts
- src/scaffolding/scaffold.ts
- src/scaffolding/scaffoldCompose.ts
- src/scaffolding/wizard/OpenStartPageStep.ts
- src/telemetry/registerListeners.ts
- src/tree/LocalRootTreeItemBase.ts
Fixes [issue 2953](https://github.com/microsoft/vscode-docker/issues/2953)
> Narrow the set of cases when we pop up start page after extension upgrade

- src/commands/dockerInstaller.ts
I had the sources open so I thought I might as well just fix this one too ☺️
> Use correct binary to install Docker on ARM64 Mac machines

- resources/templates/node/Dockerfile.template
Fixes https://github.com/microsoft/vscode-docker/issues/3034
> Use Node 14 (LTS) for Dockerfile scaffolding

- resources/startPage.html.template
Fixes https://github.com/microsoft/vscode-docker/issues/2952
> Fix start page icons

- package-lock.json
- src/tree/registries/dockerV2/DockerV2RepositoryTreeItem.ts
- src/utils/httpRequest.ts
- src/utils/registryRequestUtils.ts
Fixes https://github.com/microsoft/vscode-docker/issues/2968
> Handle repositories that return 404 when all tags are removed

- src/tree/registries/azure/createWizard/AzureRegistryCreateStep.ts
Fixes https://github.com/microsoft/vscode-docker/issues/3002
> Do not offer to report issue on missing subscription registration

- src/tree/registries/dockerV2/DockerV2TagTreeItem.ts
- src/utils/httpRequest.ts
Fixes https://github.com/microsoft/vscode-docker/issues/3059
> Fix HTTP response header handling

- src/tree/images/imageChecker/OutdatedImageChecker.ts
Fixes https://github.com/microsoft/vscode-docker/issues/3066
> Fix outdated image checker

- src/commands/compose/compose.ts
> Infer compose folder from file URI

- resources/templates/.dockerignore.template
> Remove Azure DevSpaces reference

- package.json
- src/commands/selectCommandTemplate.ts
- src/docker/DockerServeClient/DockerServeClient.ts
- src/test/commands/selectCommandTemplate.test.ts
Fixes #2858. Also fixes an unrelated compile error that came up sometimes.
> Use the inspect API to get user settings vs. defaults

- src/scaffolding/scaffold.ts
- src/scaffolding/scaffoldCompose.ts
- src/scaffolding/wizard/ScaffoldFileStep.ts
- src/scaffolding/wizard/python/PythonScaffoldingWizardContext.ts
> Don't overwrite requirements.txt files

- src/docker/ContextLoadingClient/ContextLoadingClient.ts
- src/docker/ContextManager.ts
- src/extension.ts
> Use big-brain tactics to defer loading of Docker context

- resources/templates/node/Dockerfile.template
> Use low-rights `node` user in Node.js apps

- src/tree/registries/dockerHub/DockerHubAccountTreeItem.ts
Fixes #2954. This does remove paging support for orgs+namespaces, which is probably ok--nobody seems to have 100+ namespaces.
Action shot:
There's my personal namespace (bwater***), the org I am an owner in (bwaterorg***), and an org I am not an owner in (zpk***).
> Show orgs in Docker Hub namespaces list

- src/commands/containers/files/downloadContainerFile.ts
- src/commands/containers/files/openContainerFile.ts
> Add support for cancelling file open

- resources/templates/node/Dockerfile.template
Fixes #3134. I did some sanity testing on both Codespaces and Windows, validating F5, compose up, and debug compose up + attach.
> Change ordering of node Dockerfile's USER directive

- package.json
- src/debugging/netcore/AspNetSslHelper.ts
- src/utils/netCoreUtils.ts
> Drop code specific to .NET Core 2.1

- src/scaffolding/wizard/netCore/NetCoreGatherInformationStep.ts
> Add link to extension page in C#-ext-missing error

- resources/netCore/GetBlazorManifestLocations.targets
- src/tasks/netcore/NetCoreTaskHelper.ts
- src/tasks/netcore/updateBlazorManifest.ts
Fixes #3126.
To verify:
**Under .NET Core 3 CLI:**
**Under .NET 5 CLI:**
**Under .NET 6 CLI:**
> Containerize Blazor JSON manifest

- package.json
- src/constants.ts
Fixes #3163, also makes the right-click menu item for "Build Image" consistent with compose where it's targeted to language.
> Update glob file pattern for file picker

- src/utils/httpRequest.ts
> Handle empty response body

- package-lock.json
- package.json
> Update `vscode-azureappservice` to fix Azure Arc issue

- package.json
Oops, I forgot to do this in #3286.
> Turn on the compose language service by default

- resources/templates/node/Dockerfile.template
- resources/templates/python/Dockerfile.template
- resources/templates/ruby/Dockerfile.template
Fixes #3287 and also updates Python and Ruby, because why not. I did test Node Express, and Python Flask and Django without issue, not that I expected any. I wouldn't even know how to test Ruby.
> Use more general tags because why not

- src/tasks/netcore/NetCoreTaskHelper.ts
> Double-map the nuget path

- src/commands/containers/composeGroup.ts
> Include env file in compose group commands

- package-lock.json
- package.json
> Update UI package to fix masking

- src/commands/registries/azure/tasks/scheduleRunRequest.ts
I'm tired of seeing #702 every time I look at the Future bucket so I'm just gonna fix it. Super easy. I verified things work as expected.
This diff view is much easier to interpret since it hides whitespace; there's a large amount of indentation-only change to push the code into a `try` block: https://github.com/microsoft/vscode-docker/pull/3354/files?diff=unified&w=1
> Clean up temp file

- README.md
> Update readme to refer to new telemetry setting

- resources/templates/netCore/Dockerfile.template
> Set `UseAppHost=false` in publish

- CHANGELOG.md
- NOTICE.html
- package-lock.json
- package.json
> Update version, changelog for 1.19.0

- webpack.config.js
> Add warning suppression for optional `ssh2` dependency

- src/commands/containers/composeGroup.ts
> If `config_files` is absolute use it unconditionally

- package.json
> Expose compose start and stop commands to palette

- CHANGELOG.md
- NOTICE.html
- package-lock.json
- package.json
The changelog is still a WIP so may receive updates.
> Update version, changelog, notices for 1.20.0

- src/docker/ContextManager.ts
- src/tasks/python/PythonTaskHelper.ts
- src/test/utils/commandLineBuilder.test.ts
- src/tree/contexts/ContextTreeItem.ts
- src/utils/quickPickFile.ts
- tsconfig.json
Turned on a couple of TS rules and put in fixes for them.
> Change some TS rules and fix

- src/tasks/DockerPseudoterminal.ts
Fixes a silly regression from #3452
> Fix silly regression

- CHANGELOG.md
- NOTICE.html
- package-lock.json
- package.json
Also updates `@microsoft/vscode-azext-azureappservice` and `@microsoft/vscode-azext-azureutils` to pick up some bug fixes.
> Update version, changelog, notices for 1.21.0

- package-lock.json
- package.json
- src/debugging/netcore/NetCoreDebugHelper.ts
- src/dockerHubSearch.ts
- src/tasks/TaskDefinitionBase.ts
- src/tree/images/imageChecker/OutdatedImageChecker.ts
- src/tree/images/imageChecker/registries.ts
- src/tree/registries/dockerHub/DockerHubAccountTreeItem.ts
- src/utils/registryRequestUtils.ts
Also fixes linter errors that appeared as a result of the `npm update`.
> Bump version and `npm update`

- resources/templates/.dockerignore.template
> Add the `.venv` dir to .dockerignore

- package-lock.json
- package.json
> Update `@microsoft/vscode-azext-azureappservice` package

- package-lock.json
- package.json
Picks up some fixes in the compose language service.
> Update `@microsoft/compose-language-service` to `0.1.1`

- package.json
> Allow copying tags from DockerHub as well

- src/commands/images/tagImage.ts
> Fix Docker Hub tag match

- src/debugging/python/PythonDebugHelper.ts
> Support non-Docker Desktop setups in WSL for Python debug

- package-lock.json
- package.json
This won't fully remove `string_decoder` (which is supplying us with a CG alert), but is a necessary step toward it.
In order to fully remove it, we will also need to remove `dockerode` and `tar-stream`.
> Update the `@microsoft/vscode-azext-utils` package

- package-lock.json
- package.json
Updates `@microsoft/vscode-azext-utils` _again_, to fix telemetry being busted, _again_
> Update `@microsoft/vscode-azext-utils` again

- src/tree/containers/ContainerGroupTreeItem.ts
- src/tree/containers/files/DirectoryTreeItem.ts
Adds a missed part of #3521 that is needed.
> Update tree item collapsible state

- .azure-pipelines/main.yml
> Shut off the Mac pipeline because it's failing so much

- .azure-pipelines/main.yml
- package-lock.json
- package.json
> Try upgrading `@vscode/test-electron` and reenabling Mac pipeline

- .vscode/settings.json
> Enable branch protection settings

- src/commands/registries/azure/untagAzureImage.ts
> Add 'image' to untag prompt

- package.json
- package.nls.json
- src/docker/ContextManager.ts
- src/docker/DockerodeApiClient/DockerodeApiClient.ts
- src/docker/DockerodeApiClient/DockerodeUtils.ts
- src/extension.ts
- src/tasks/DockerPseudoterminal.ts
- src/utils/addDockerSettingsToEnv.ts
- src/utils/executeAsTask.ts
- src/utils/migrateOldEnvironmentSettingsIfNeeded.ts
> Rename back to `docker.environment`

- src/commands/registries/azure/tasks/scheduleRunRequest.ts
> Change upload message

- resources/netCore/GetBlazorManifestLocations.targets
> Update to the targets file to get absolute Blazor manifest path

- CHANGELOG.md
- resources/netCore/GetBlazorManifestLocations.targets
Cherry pick of:
- #3643
- #3644
> Cherry pick `rel/1.22.2` items

- src/scaffolding/wizard/netCore/NetCoreGatherInformationStep.ts
Fixes #3647. Cherry pick of #3516.
> Cherry-pick Switch back to default .NET images (#3516)

- package-lock.json
- package.json
> Bump minimum VSCode version

- src/commands/dockerInstaller.ts
- src/utils/execAsync.ts
> Fix Docker Desktop install

- src/extension.ts
- src/runtimes/ContainerRuntimeManager.ts
- src/runtimes/OrchestratorRuntimeManager.ts
- src/runtimes/clients/AutoConfigurableClient.ts
- src/runtimes/clients/AutoConfigurableDockerClient.ts
- src/runtimes/clients/AutoConfigurableDockerComposeClient.ts
- src/utils/execAsync.ts
> Autodetect compose configuration

- src/runtimes/docker/clients/DockerComposeClient/DockerComposeClient.ts
> Pull upstream changes to fix compose down issue

- CHANGELOG.md
- NOTICE.html
- package-lock.json
- package.json
To see the changelog in an easier-to-read form, go here: https://github.com/microsoft/vscode-docker/blob/bmw/1.23.0/CHANGELOG.md
> Update version, changelog, notices for 1.23.0 release

- src/tree/RefreshManager.ts
> Listen for volume prune events

- src/runtimes/docker/clients/DockerClientBase/parseDockerLikeImageName.ts
- src/runtimes/docker/contracts/ContainerClient.ts
- src/runtimes/docker/test/parseDockerLikeImageName.test.ts
> Pull upstream changes to support images with digest

- src/runtimes/docker/clients/DockerComposeClient/DockerComposeClient.ts
> Don't overescape compose service list

- CHANGELOG.md
- package-lock.json
- package.json
The date and bugs that are fixed is a bit speculative at the moment.
> Update version, changelog for 1.23.2

- src/definitions/tar.d.ts
- src/runtimes/docker/clients/DockerClientBase/DockerClientBase.ts
- src/runtimes/docker/clients/DockerClientBase/parseListFilesCommandOutput.ts
- src/runtimes/docker/contracts/ContainerClient.ts
- src/runtimes/docker/test/DockerComposeClient.test.ts
- src/runtimes/docker/utils/spawnStreamAsync.ts
- src/runtimes/files/ContainerFilesProvider.ts
- src/runtimes/files/DockerUri.ts
- src/runtimes/runners/runWithDefaults.ts
- src/utils/tarUtils.ts
Fixes #3740
Fixes #3761 
Updates the files module and generalizes special no shell behavior for Windows.
> Update our files provider and implement a NoShell IShell provider

- src/tasks/netcore/NetCoreTaskHelper.ts
> Check whether local nuget packages folder exists before volume mounting

- package-lock.json
- package.json
> Change to `@vscode/vsce` and do `npm audit fix`

- resources/templates/python/requirements.txt.template
Also resolves #3736.
Things I tested:
> Update scaffolded Python dependencies in `requirements.txt`

- package.json
- src/commands/registries/azure/deployImageToAca.ts
- src/tree/registries/dockerHub/DockerHubNamespaceTreeItem.ts
To merge into #3794 
@bwateratmsft Let me know if you think something like this could work, thanks!
> Update ACA deployment contract & use `registryPath` as `loginServer`

- src/commands/registries/azure/deployImageToAca.ts
- src/utils/installExtension.ts
> Install ACA extension on prompt

- package.json
- package.nls.json
- src/tasks/netcore/NetCoreTaskHelper.ts
This PR closes #3831 by adding a customs entry point option in `tasks.json`
> Enabled Custom Entrypoint

- CHANGELOG.md
- package-lock.json
- package.json
Also update version, changelog for 1.25.1
> Cherry-pick #3928: Add back `onLanguage:dockerfile` activation event

- CHANGELOG.md
Cherry-picking the changelog updates from #3943
> Cherry-pick Update version, changelog for 1.25.1 (#3943)

- package-lock.json
- package.json
- package.nls.json
- src/commands/registerCommands.ts
- src/commands/registries/genericV2/addTrackedGenericV2Registry.ts
- src/commands/registries/genericV2/removeTrackedGenericV2Registry.ts
Related to https://github.com/microsoft/vscode-docker/pull/4026
> Improve UX for Connecting & Disconnecting Generic V2 Registries

- resources/templates/netCore/Dockerfile.template
- src/tasks/netcore/NetCoreTaskHelper.ts
Closes https://github.com/microsoft/vscode-docker/issues/4040
> Use native platform for debug 

- package-lock.json
- src/commands/registries/azure/DockerSiteCreateStep.ts
- src/commands/registries/azure/deployImageToAzure.ts
Addresses https://github.com/microsoft/vscode-docker/pull/4026#discussion_r1313161662
> Simplify logic in deploy to Azure app service

- resources/templates/netCore/Dockerfile.template
Closes https://github.com/microsoft/vscode-docker/issues/4058
TODO:
> Only scaffold `--platform` flag for linux containers

- src/extensionVariables.ts
- src/tree/registerTrees.ts
- src/tree/registries/Azure/AzureRegistryDataProvider.ts
- src/tree/registries/UnifiedRegistryTreeDataProvider.ts
Addresses these comments
- https://github.com/microsoft/vscode-docker/pull/4026#discussion_r1323176255
- https://github.com/microsoft/vscode-docker/pull/4026#discussion_r1323268322
> Change fireSoon to take callback function

- package-lock.json
- package.json
- src/tree/registries/UnifiedRegistryTreeDataProvider.ts
- src/utils/registryExperience.ts
Closes https://github.com/microsoft/vscode-docker/issues/4082
Closes https://github.com/microsoft/vscode-docker/issues/4083
Closes https://github.com/microsoft/vscode-docker/issues/4087
> Minor Registry UX enhancements

- package-lock.json
- package.json
> Update auth package

- package-lock.json
- package.json
Closes https://github.com/microsoft/vscode-docker/issues/4117
> Allow Empty Username for Registries Auth

- resources/templates/python/requirements.txt.template
Closes https://github.com/microsoft/vscode-docker/issues/4119
Tested:
> Bump Scaffolded Flask version to 3.0.0

- package-lock.json
- package.json
Closes https://github.com/microsoft/vscode-docker/issues/4120
> Add Scope details to Secret Prompt for Dockerhub Registry 

- package-lock.json
- package.json
- src/tree/registries/Azure/AzureRegistryDataProvider.ts
Fixes #4141 (seems to anyway)
Fixes #4131
> Fix some Azure sign in issues

- package.json
> Allow disconnecting from generic registry V2 to escape broken state

- src/utils/httpRequest.ts
Fixes #4176. I'm not sure why this worked when I originally tried it but it works for sure now.
> Fix `streamToFile` implementation

- package-lock.json
- package.json
- src/commands/images/pushImage/RefreshRegistriesViewStep.ts
- src/commands/images/pushImage/pushImage.ts
- src/tree/registerTrees.ts
- src/tree/registries/Azure/AzureRegistryDataProvider.ts
> Update `@microsoft/vscode-docker-registries` and clean up `registerTrees.ts`

- package-lock.json
- package.json
> Bump `@microsoft/vscode-docker-registries`

- .vscode/settings.json
- package-lock.json
- package.json
Update `@microsoft/vscode-docker-registries` to fix #4192
> Update `@microsoft/vscode-docker-registries` and do `npm audit fix`

- src/utils/resolveVariables.ts
> Resolve environment variables in tasks

- CHANGELOG.md
- package-lock.json
- package.json
- src/tree/registries/Azure/ACROAuthProvider.ts
- src/tree/registries/Azure/AzureRegistryDataProvider.ts
- src/utils/azureUtils.ts
> Make ACR feature work with sovereign clouds

- src/scaffolding/wizard/netCore/NetCoreGatherInformationStep.ts
> Update .NET preview version to 10

- src/tree/containers/ContainerTreeItem.ts
> Different icon for starting container vs. one that is healthy

- package.json
- src/commands/help.ts
- src/commands/registerCommands.ts
- src/extension.ts
> Use built-in issue reporter to hopefully get higher quality issues

- package-lock.json
- package.json
> Update `@microsoft/vscode-docker-registries` to 0.2.0

- src/commands/compose/compose.ts
- src/commands/compose/getComposeSubsetList.ts
Proposed fix for #4468.
This is just a first draft and needs additional validation, but I wanted to get some eyes on it before I sink to much time into this PR vs. reverting the other PR that caused the regression.
> Add implementations of service/profile expansion for default commands

- resources/templates/docker-compose.debug.yml.template
- resources/templates/docker-compose.yml.template
- resources/templates/java/docker-compose.debug.yml.template
- resources/templates/netCore/docker-compose.debug.yml.template
- resources/templates/netCore/docker-compose.yml.template
- resources/templates/node/docker-compose.debug.yml.template
- resources/templates/node/docker-compose.yml.template
- resources/templates/python/docker-compose.debug.yml.template
- resources/templates/python/docker-compose.yml.template
> Remove version from scaffolded compose documents

- CHANGELOG.md
> Update 1.29.4 CHANGELOG.md

- package-lock.json
- package.json
> Update `@microsoft/vscode-container-client` to fix stats command

- src/commands/containers/attachShellContainer.ts
> Fix attach shell bug

- package.json
> Add Docker DX to extension pack

- resources/netCore/GetProjectProperties.targets
Fixes #4558
I tested
With .NET 10 P3 installed:
- .NET 9 app, SDK build
- .NET 9 app, Dockerfile build
- .NET 10 app, SDK build
- .NET 10 app, Dockerfile build
With only .NET 9 installed:
- .NET 9 app, SDK build
- .NET 9 app, Dockerfile build
> Fix .NET 10 preview 3 debugging bug
